---
title: "备份"
weight: 20
---
企业云平台提供备份服务，支持对云服务器及云硬盘进行在线全量或增量备份，并支持基于备份新建或恢复场景。

== 制作备份

根据备份场景，制作备份分为在线备份和离线备份。

* 离线备份：备份关机状态的主机系统盘、没被挂载到主机的数据盘以及挂载到关机状态主机上的数据盘。
* 在线备份：备份开机状态的主机系统盘以及挂载到开机状态的数据盘。

[discrete]
=== 实现方式

制作备份主要通过 QCOW2 和 NeonSAN 两种方式实现。

* QCOW2：利用 QCOW2 文件的 backingfile 机制，在制作备份时新建并切换 “head” 文件，切换后其剩余的 backingfile 即是该时刻的数据。一般用于系统盘的备份。
* NeonSAN：利用 NeonSAN 提供的 snapshot 功能进行备份制作，再通过 export_diff 将备份数据保存。一般用于 NeonSAN 硬盘的备份。

[discrete]
=== 实现逻辑

*QCOW2 备份*

** 离线制作备份
+
云服务器关机状态时，即可对云服务器做离线备份操作。
+
. 通过 qumu-img 命令生成备份任务，同时 touch 一个 head 文件用于主机启动时标明所使用的系统盘。
. 当备份任务结束时，系统会自动清理 container 目录下的垃圾文件，释放磁盘资源。

** 在线制作备份
+
qemu-img 相关命令只能操作“只读”状态的文件，对于正在运行的云服务器需要借助 virsh 工具进行备份。
+
. 首先 suspend 主机，通过 sync 防止执行备份期间出现 io error 的问题。
. 然后通过 virsh 工具开启备份任务，任务过程中会生成 img 和 head 文件内容，再 resume 主机，将主机数据写入 img 文件中。
. 当备份任务结束时，与离线备份一样，会清理 container 目录中的垃圾文件，释放磁盘资源。

*NeonSAN 备份*

通过 NeonSAN `create_snapshot` 命令即可完成对 NeonSAN 数据盘的备份功能。


== 保存备份

保存备份分为增量备份和全量备份。

* 全量备份：保存资源当前的全部数据作为一个备份链的头链。
* 增量备份：保存资源当前数据和上一次备份中间的差异作为一个备份链的备份点。

[discrete]
=== 保存位置

备份文件可通过 disk 和 qingstor 两种方式保存。

* disk：通过 snapshot 节点的物理硬盘保存备份文件。
* qingstor：使用对象存储保存备份文件。

[discrete]
=== 实现逻辑

*QCOW2 保存备份*

. 在使用 QCOW2 创建备份任务时，新生成了很多 img 文件，选择不同的备份模式时（全量备份或增量备份）会保存至相应的 img 文件。
. QCOW2 的备份文件如果小于 `2*snap_split_size`（“server.yaml” 文件下的 `compute_server` 配置，默认为 1G），则直接调用脚本，将 qcow2 文件拷贝到 snapshot 节点；否则需要先分片并拷贝到 vbr 节点，再利用 vbr 节点的异步线程，把各个分片上传到 snapshot 节点。

*NeonSAN 保存备份*

. 用 `neonsan export_diff` 将数据导出到标准输。
. 用 `lz4` 捕捉压缩成文件，传输到 vbr 节点。
. 传输到 vbr 节点后，利用 vbr 线程，把文件异步传输到 snapshot 节点。


