title: "企业云文档"

markup:
  asciidocExt:
    attributes:
      toc:
      toclevels: 2
      file_output_type: html
      # 全局变量
      product_name: 企业云平台
      platform_name: Console
      platform_name_boss: BOSS
      company_short_name: 青云
      brand_full_name: 青云QingCloud
      brand_name_cap: QingCloud
      brand_name_low: qingcloud
      # 产品变量
      qingstor_cap: QingStor
      qingstor_low: qingstor
      k8s_engine_fullname: 容器引擎 QKE
      k8s_engine_shortname: QKE
      qingstor_neon: NeonSAN
params:
  description: "这是企业云文档中心"
  favicon: "/images/favicon.ico"
  keywords: "青云,QingCloud,企业云,云平台,云计算"
  logo: "/images/qingcloud-logo.svg"
  logoInfo: "企业云"
  logoLink: "/v6.2/"
  disableVersions: false

  # PDF 配置
  pdf:
    pdf_projectName: 企业云平台
    pdf_docVersion: 01
    pdf_copyright: 版权所有 © 北京青云科技股份有限公司
    pdf_legalInfo: 版权所有 © 北京青云科技股份有限公司 2023。保留所有权利。
    pdf_projectVersion: v6.2
#    pdf_releaseDate: 2023-03-01
    pdf_companyFullName: 北京青云科技股份有限公司
    pdf_companyName: 青云
    pdf_companyUrl: https://www.qingcloud.com
    pdf_companyIcon: /images/pdf/qingcloud-logo-icon.png
    pdf_coverDocName: 企业云平台 v6.2
    pdf_coverDocLogo: /images/pdf/qingcloud-logo-color.png
    pdf_coverDocImage: /images/pdf/cover_doc_image.svg
    # 40 minutes
    pdf_timeout: 40
    toclevels: 3
    sectnumlevels: 5
