title: KubeSphere  # 此为学习路径上面的 title
markup:
  asciidocExt:
    attributes:
      toc: null
      toclevels: 2
      file_output_type: html
      relfilesuffix: /
      ks_product_left:  KubeSphere 企业版 # 4.2.0 及以后不再使用
      ks_product_right: KubeSphere 企业版 # 4.2.0 及以后不再使用
      ks_product_both:  KubeSphere 企业版 # 4.2.0 及以后不再使用
      ks_product: KubeSphere
      ks_product_ver: "v3.4.0" # 仅用于 3.4.0 的文档

params:
  disableVersions: false # 此为是否显示版本索引
  description: 这是 KubeSphere 文档页面
  favicon: /images/favicon.ico
  keywords: 云计算,青云,QingCloud,文档,KubeSphere
  logo: /images/qingcloud-logo.svg
  logoInfo: KubeSphere # 此为最上方版本索引左边的 title
  logoLink: /
  disablePdf: true
  navLink:
  - title: 英文文档
    url: https://docs.kubesphere.co
  pdf:
    toclevels: 4
    sectnumlevels: 6
    pdf_timeout: 60
    pdf_projectName: KubeSphere 容器平台
    pdf_docVersion: '01'
    pdf_copyright: 版权所有 © 北京青云科技集团股份有限公司
    pdf_legalInfo: 版权所有 © 北京青云科技集团股份有限公司 2025。保留所有权利。
    # pdf_projectVersion: '3.4.0'
    # pdf_releaseDate: '2023-08-21'
    pdf_companyFullName: 北京青云科技集团股份有限公司
    pdf_companyName: 青云
    pdf_companyUrl: https://www.qingcloud.com
    pdf_companyIcon: /images/pdf/qingcloud-logo-icon.png
    pdf_coverDocName: KubeSphere 容器平台
    pdf_coverDocLogo: /images/pdf/qingcloud-logo-color.png
    pdf_coverDocImage: /images/pdf/cover_doc_image.svg
