---
title: "SDN 控制平面"
weight: 20
---

[discrete]
=== SDN 控制组件

企业云云平台 SDN 控制平面是一套完全分布式的管理系统，由一系列分布在云平台管理节点及计算节点的多个 SDN 组件组成。

* DVR controller：DVR 控制节点。每个 vxnet 的 DVR 集群会选举出其中一个 DVR 作为控制节点，用于将 SDN 消息同步至 DVR 集群所有节点，当 DVR controller 出现故障时，会自动从集群中选举其他节点作为 controller 接管。
* rs-node：BGP 路由同步节点。每个 VBC/VPC 都由分布在两台 Hyper 上的 namespace 组成，用于同步 VBC/VPC BGP EVPN 路由，使得每个 DVR 节点都可获悉同一网络云服务器（下文简称 VM） 的 IP、MAC、所在 Hyper、DVR、VNI 等信息。
* rs-server：VBC 基础网络路由同步节点。由云平台管理节点上的 2~4 台 VM 组成，用于将云平台内基础网络 IP 路由通过 BGP IPv4 传递给云平台外部物理交换机。
* swctl：Border 控制器。由云平台管理节点上的 2 台 VM 组成，通过 netconf 及 BGP EVPN 向 VPC/BM Border 交换机同步配置信息及路由。
* eipctl：EIP 控制器。由云平台管理节点上的 2 台 VM 组成，通过 netconf 及 BGP EVPN 向 VG 交换机同步配置信息及路由。

当云平台任务调度系统将虚拟资源（VM/NFV）调度到计算节点时，计算节点将根据虚拟资源加入/离开的网络信息通过云平台消息接口通知对应的 SDN 组件，并通过云平台 SDN 同步机制将消息同步至同一网络的其他节点，其他计算节点接收到消息之后，会自动生成对应的 SDN 转发规则。

[discrete]
=== 架构设计特点

* SDN 控制组件均采用多节点高可用设计，分布在不同的物理节点上，单一节点故障不会影响 SDN 控制面正常工作。
* SDN 控制组件宕机，不会导致转发规则老化，不会影响正常的业务转发。
* 采用转控分离设计，控制平面组件不承担业务流量转发，故障不会导致业务中断。
* 完全分布式的 SDN 数据转发平面，无集中式网元，虚拟网元会随着 VM 的安置而自动分布，无单点性能瓶颈。
* 所有 DVR 节点都拥有同一网络所有 VM 的明细路由、ARP 表项、VXLAN 封包规则等转发表项，实现点对点最短访问路径。