---
title: "应用管理"
keywords: "Kubernetes, {ks_product}, 应用, 安装, 应用模板,应用商店"
description: "介绍应用管理全过程。"
weight: 12
draft: true
---

// 只修改了此 index 的内容，调整了其他目录的层级，以及目录层级变化造成的交叉链接的路径变化

在{ks_product_both}平台，应用特指由一个或多个工作负载、服务、应用路由等资源组成的业务程序。

{ks_product_right}平台目前支持创建基于模板的应用，即通过已有的应用模板安装应用。安装应用所使用的应用模板可以是已发布到应用商店的应用模板、上传到企业空间的应用模板、或第三方应用仓库中的应用模板。您可以在{ks_product_left} Web 控制台的多个入口将应用安装到项目中，如直接在应用商店安装应用（需存在已上架的应用模板）、link:01-app-templates/05-install-an-app-by-using-an-app-template/[使用企业空间的应用模板安装应用]、 link:03-app-store-management/05-app-deployment/08-deploy-an-app-from-the-app-store/[在应用商店管理页面安装应用]、link:05-apps/01-install-an-app-from-the-app-store/[在项目中安装应用]。

本节介绍从创建应用模板、发布应用模板到应用商店、管理应用商店、以及安装管理应用的整个过程。在此过程中，您需要安装“KubeSphere 应用商店管理”扩展组件。

安装“KubeSphere 应用商店管理”扩展组件后，企业空间左侧导航栏的**应⽤管理**菜单下将显⽰**应用模板**选项，页面右上角的扩展组件快捷入口中将显⽰**应⽤商店管理**选项。

使用该扩展组件：

- 企业空间管理员可以管理应用模板，提交应用模板中定义的应用到应用商店。待应用商店管理员审批通过并上架后，即可发布应用程序到应用商店，供{ks_product_both}平台的所有项目安装该应用。
- 应用商店管理员可以对应用商店中的应用模板进行分类、审核、上架、下架等操作，管理平台的应用仓库和所有已部署的应用实例，并直接部署应用到项目。

ifeval::["{file_output_type}" == "pdf"]
== 产品版本

本文档适用于{ks_product_left} v4.1.2 版本。

== 读者对象

本文档主要适用于以下读者：

* {ks_product_right}用户

* 交付工程师

* 运维工程师

* 售后工程师


== 修订记录

[%header,cols="1a,1a,3a"]
|===
|文档版本 |发布日期 |修改说明

|01
|{pdf_releaseDate}
|第一次正式发布。
|===
endif::[]