---
title: "Virtual SAN"
description: 本小节主要介绍共享存储简介。
draft: false
keywords: 云计算, 青云, QingCloud, 共享存储, Virtual SAN, NeonSAN
weight: 1
---


{platform_name_cn} 提供 Virtual SAN（vSAN）共享存储服务，可满足不同业务场景需求，实现稳定高效、安全可靠、灵活便捷的存储服务。

== 产品优势

* **低成本**：与企业采购价格昂贵的存储柜相比，QingCloud 基于 iSCSI 协议推出的 Virtual SAN，可以让用户在极低的 IT 投入下享受专业的企业级存储服务。
* **支持最大容量**：vSAN 添加的存储如果是容量盘支持最大容量 50T。如果是性能盘或者超高性能盘支持最大容量 1.5T。
* **图像化界面**：{brand_name_cap} 提供可视化的操作界面，用户可以方便快捷的在 Virtual SAN 的图形化界面里进行创建目标、添加硬盘、切换网络等操作。
* **高可用性**：{brand_name_cap} 能够通过实时异地副本、备份等多重方式保障数据安全，同时其独特的 P2P 机器人社区协作可以确保物理设备故障无害。数据可用性达 99.999%，服务可用性达 99.95%。
* **高安全性**：作为国内首家通过云端 SDN 实现私有网络 (VPC) 的云服务商，{brand_name_cap} 在提供组网功能的同时实现 100% 的二层隔离。Virtual SAN 服务运行于私有网络中，严格确保企业的数据安全。
* **高性能**：{brand_name_cap} 提供性能型存储和 SSD 超高性能存储，虚拟资源性能突出，达到或接近物理设备水平，适用于对 I/O 要求较高的应用。Virtual SAN 服务同时支持 QingCloud 的大容量存储。

== 产品功能

* 设置 iSCSI 客户端
+ 
为了 Virtual SAN 的安全性，可以设置 iSCSI 客户端来指定可以登录到目标的客户端。
* 实时监控
+
目前 Virtual SAN 服务支持对硬盘 IOPS 和硬盘吞吐量的实时监控，每 10 秒钟获取一次监控数据，亦支持对历史监控数据的查询。
* 共享存储目标
+
在 Virtual SAN 服务上可以创建多个共享存储目标，每个目标下可以添加多块硬盘。用户通过主机客户端登录目标以使用 Virtual SAN 服务。

* 提供两种主机类型
+
vSAN 提供两种主机类型：基础型和企业型。基础型主机可以使用容量型硬盘和性能型硬盘，企业型主机可以使用容量型硬盘和超高性能型硬盘。

== 应用场景

* 共享文件系统
+ 
对于需要部署共享文件系统 (如：OCFS、Redhat GFS) 的业务，QingCloud 通过 Virtual SAN 更好地满足用户的各种需求。

* 数据库高可用
+
对于 Oracle RAC 和 Microsoft SQL Server 集群等需要共享存储的大型分布式数据库，用户可以通过 Virtual SAN 轻松部署，并且通过 QingCloud 的 VPC 和分布式防火墙可以对数据库进行安全的保护。同时，通过应用市场的数据库审计产品，用户可以实现云上核心数据访问状态的可视化、可控化，提供智能化报告。
