---
title: 获取资源绑定的通知列表（DescribeResourceNotificationList）
weight: 5
---

== 基本信息

=== Path
/iaas

=== Method
GET

== 请求参数
[cols="1,1,1,2", options="header"]
|===
| 参数名 | 类型 | 是否必须 | 描述

| limit
| Integer
| false
| 查询数量

| offset
| Integer
| false
| 查询偏移量

| owner
| Integer
| false
| 所属用户id

| resource_type
| String
| false
| 资源类型

| resources
| Array
| false
| 资源id列表
|===

== 返回数据
此接口除以下返回参数外，还包含公共响应头。关于公共响应头的更多信息，请参见link:../../../../overview/#_api_返回结构[前文内容]。
[cols="1,1,1,2", options="header"]
|===
| 参数名 | 类型 | 是否必须 | 描述

| resource_notification_list_set
| Array
| false
| 资源消息集合

| resource_notification_list_set[].console_id
| String
| false
| 控制台

| resource_notification_list_set[].create_time
| String
| false
| 创建时间

| resource_notification_list_set[].notification_list_id
| String
| false
| 通知列表id

| resource_notification_list_set[].owner
| String
| false
| 用户id

| resource_notification_list_set[].resource_id
| String
| false
| 资源id

| resource_notification_list_set[].resource_type
| String
| false
| 资源类型

| resource_notification_list_set[].root_user_id
| String
| false
| 根用户id

| total_count
| Integer
| false
| 查询结果总数
|===

== 请求示例
[,javascript]
----
{
  "action": "DescribeResourceNotificationList",
  "resource_type": "cluster"
}
----

== 返回示例
[,javascript]
----
{
  "action": "DescribeResourceNotificationListResponse",
  "resource_notification_list_set": [
    {
      "console_id": "alphacloud",
      "create_time": "2020-05-28T02:31:38Z",
      "notification_list_id": "nl-xxxxxxxx",
      "owner": "usr-xxxxxxxx",
      "resource_id": "cl-xxxxxxxx",
      "resource_type": "cluster",
      "root_user_id": "usr-xxxxxxxx"
    },
    {
      "console_id": "alphacloud",
      "create_time": "2020-05-28T02:34:08Z",
      "notification_list_id": "nl-xxxxxxxx",
      "owner": "usr-xxxxxxxx",
      "resource_id": "cl-xxxxxxxx",
      "resource_type": "cluster",
      "root_user_id": "usr-xxxxxxxx"
    }
  ],
  "ret_code": 0,
  "total_count": 2
}
----
