---
title: 获取定时器列表（DescribeSchedulers）
weight: 8
---

== 基本信息

=== Path
/iaas

=== Method
GET

== 请求参数
[cols="1,1,1,2", options="header"]
|===
| 参数名 | 类型 | 是否必须 | 描述

| controller
| String
| false
| 资源的控制者

| limit
| Integer
| false
| 返回数量

| offset
| Integer
| false
| 偏移量

| owner
| String
| false
| 资源的所有者

| schedulers
| Array
| false
| 定时器id列表

| verbose
| Integer
| false
| 是否返回详细信息

| zone
| String
| true
| 请求区ID
|===

== 返回数据
此接口除以下返回参数外，还包含公共响应头。关于公共响应头的更多信息，请参见link:../../../../overview/#_api_返回结构[前文内容]。
[cols="1,1,1,2", options="header"]
|===
| 参数名 | 类型 | 是否必须 | 描述

| console_id
| String
| false
| 控制台id

| create_time
| String
| false
| 创建时间

| description
| String
| false
| 描述

| hhmm
| String
| false
| 时分

| is_mine
| String
| false
| 是否是自己的

| items
| Array
| false
| 通知列表

| notification_lists
| Array
| false
| 通知列表

| notify_event
| String
| false
| 通知事件1通知/0不通知

| period
| Integer
| false
| 周期

| repeat
| Integer
| false
| 重复次数

| resource_project_info
| Array
| false
| 资源项目信息

| resource_project_info[].meta
| String
| false
| 项目元数据

| resource_project_info[].project_id
| String
| false
| 项目ID

| resource_project_info[].project_name
| String
| false
| 项目名称

| root_user_id
| String
| false
| 资源主账户id

| scheduler_id
| String
| false
| 定时器id

| scheduler_name
| String
| false
| 定时器名称

| scheduler_set
| Array
| false
| 定时器列表

| snapshot_task_count
| Integer
| false
| 快照任务数量

| total_count
| Integer
| false
| 定时器总数

| update_time
| String
| false
| 更新时间

| ymd
| String
| false
| 年月日
|===

== 请求示例
[,javascript]
----
{
  "action": "DescribeSchedulers",
  "controller": [
    "self"
  ],
  "limit": 10,
  "offset": 0,
  "owner": "usr-BnnisHWR",
  "schedulers": [
    "schd-8rzuyrmr"
  ],
  "status": [],
  "verbose": 1,
  "zone": "testing"
}
----

== 返回示例
[,javascript]
----
{
  "action": "DescribeSchedulersResponse",
  "ret_code": 0,
  "scheduler_set": [
    {
      "console_id": "testingcloud",
      "create_time": "2023-07-05T00:13:08Z",
      "description": "",
      "hhmm": "00:13",
      "notification_lists": [
        {
          "console_id": "testingcloud",
          "create_time": "2021-12-28T09:48:18Z",
          "is_account_contacts": 1,
          "is_mine": "false",
          "items": [
            {
              "console_id": "testingcloud",
              "content": "66-15123123",
              "create_time": "2022-08-03T16:06:10",
              "notification_item_id": "ni-gesu2bio",
              "notification_item_type": "phone",
              "owner": "usr-BnnisHWR",
              "remarks": "",
              "root_user_id": "usr-BnnisHWR",
              "verification_code": "",
              "verified": 1,
              "verify_time": "2022-08-03T16:06:10"
            }
          ],
          "notification_list_id": "nl-x3u8y13n",
          "notification_list_name": "Account Contacts",
          "owner": "usr-BnnisHWR",
          "owner_info": {
            "email": "account2@testing.com",
            "user_id": "usr-BnnisHWR"
          },
          "remarks": "",
          "root_user_id": "usr-BnnisHWR",
          "shared": "false",
          "visibility": "private"
        }
      ],
      "notify_event": 1,
      "owner": "usr-BnnisHWR",
      "period": "daily",
      "repeat": 1,
      "resource_project_info": [],
      "root_user_id": "usr-BnnisHWR",
      "scheduler_id": "schd-8rzuyrmr",
      "scheduler_name": "fafdfds",
      "snapshot_task_count": 0,
      "update_time": "2023-07-05T00:13:08Z",
      "ymd": ""
    }
  ],
  "total_count": 1,
  "trace_id": "1DGqEQOV"
}
----
