title: "Express 文档中心"

markup:
  asciidocExt:
    attributes:
      toc:
      toclevels: 4
      product_name: CloudExpress 云易捷
      product_name_cn: 云易捷
      product_installer_name: CloudExpress Installer
      product_console_name: 云易捷管理控制台
      product_console_name_en: 云易捷 Console
      platform_name_cn: 青云QingCloud

params:
  description: "这是 CloudExpress 云易捷文档页面"
  favicon: "/images/favicon.ico"
  keywords: "云计算,青云,QingCloud,文档,CloudExpress 云易捷,Express,云易捷"
  logo: "/images/qingcloud-logo.svg"
  logoInfo: "云易捷"
  logoLink: "/v4.3/product_use/console_guide/"
  enableExportWord: true

  # PDF 配置
  pdf:
    toclevels: 4
    sectnumlevels: 6
    pdf_projectName: 云易捷
    pdf_docVersion: 01
    pdf_copyright: 版权所有 © 北京青云科技股份有限公司
    pdf_legalInfo: 版权所有 © 北京青云科技股份有限公司 2023。保留所有权利。
    pdf_projectVersion: v1.2.2
    #pdf_releaseDate: 2022-07-13
    pdf_companyFullName: 北京青云科技股份有限公司
    pdf_companyName: 青云
    pdf_companyUrl: https://www.qingcloud.com
    pdf_companyIcon: /images/pdf/qingcloud-logo-icon.png
    pdf_coverDocName: QingCloud 云易捷 v4.1
    pdf_coverDocLogo: /images/pdf/qingcloud-logo-color.png
    pdf_coverDocImage: /images/pdf/cover_doc_image.svg
