---
title: "TerminateInstances"
description: 
draft: false
weight: 19
---

销毁一台或多台{instance_product_name_cn}。

销毁{instance_product_name_cn}的前提，是此{instance_product_name_cn}已建立租用信息（租用信息是在创建{instance_product_name_cn}成功后， 几秒钟内系统自动建立的）。所以正在创建的{instance_product_name_cn}（状态为 pending ）， 以及刚刚创建成功但还没有建立租用信息的{instance_product_name_cn}，是不能被销毁的。

include::../../../../../_components/note.adoc[]
已销毁的{instance_product_name_cn}会在回收站保留一段时间，具体保存时长可以在全局配置里修改，也可以在回收站清空资源。
include::../../../../../_components/table_footer.adoc[]

*Request Parameters*

[option="header",cols="1,1,2,1"]
|===
| Parameter name | Type | Description | Required

| instances.n
| String
| 一个或多个{instance_product_name_cn}ID
| Yes

| direct_cease
| Integer
| 是否直接彻底销毁{instance_product_name_cn}，如果指定 `1` 则不会进入回收站直接销毁，默认是 `0`
| No

| zone
| String
| 区域 ID，注意要小写
| Yes
|===

link:../../../introduction/parameters/[公共参数]

*Response Elements*

[option="header",cols="1,1,2"]
|===
| Name | Type | Description

| action
| String
| 响应动作

| job_id
| String
| 执行任务的 Job ID

| ret_code
| Integer
| 执行成功与否，0 表示成功，其他值则为错误代码
|===

*Example*

Example Request

----
https://api.domain.com/iaas/?action=TerminateInstances
&instances.1=i-rtyv0968
&zone=testa
&COMMON_PARAMS
----

Example Response

----
{
  "action":"TerminateInstancesResponse",
  "job_id":"j-ybnoeitr",
  "ret_code":0
}
----
