---
title: "Workspace Management"
linkTitle: "Workspace Management"
keywords: "Kubernetes, KubeSphere, Workspace Management"
description: "Learn how to manage resources within a single workspace."
weight: 08
---

This section explains how to manage resources within a workspace.

In KubeSphere, a workspace is used to group resources for management. Cluster administrators can authorize one or more clusters to a workspace, allowing resources within the workspace to run on the cluster. Each workspace can contain multiple projects. Users can be invited to join a workspace and gain view and management permissions for workspace resources based on their workspace roles.

After the {ks_product-en} installation is complete, the system will automatically create the **system-workspace** workspace, which includes system projects for managing system resources.

ifeval::["{file_output_type}" == "pdf"]

== Product Version

This document is applicable to {ks_product-en} v4.1.2.

== Target Readers

This document is primarily intended for the following readers:

* {ks_product-en} users
* Delivery engineers
* Operations engineers
* Post-sales engineers

== Revision History

[%header,cols="1a,1a,3a"]
|===
|Document Version |Release Date |Description

|01
|{pdf_releaseDate}
|Initial release.
|===
endif::[]