---
title: "Create a physical subnet"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, physical subnets, creation"
description: "Describes how to create a physical subnet in the {ks_product} web console."
weight: 01
logo: ""
downloadUrl: ""
---

// :ks_include_id: 39d145bf122b46e1b8d96587a1869e98
:ks_xref_id: cea707fe3f2245ebb017ac3bb450754f
:ks_comp: ../../../../components/
:ks_title: Create a physical subnet
:ks_description: Describes how to create a physical subnet in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, physical subnets, creation
:ks_weight: 01
:ks_logo:
:ks_download_url:


This topic describes how to create a physical subnet in the {ks_product_abbr_full} web console.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=8af32b1eabb54d208e21b1d37e763987]

* The user that you use has been granted the permissions to use the **Physical Resources** module.  The **Physical Resources** module is available only to user **admin**.
* A physical network is created in the system.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Procedurelink:[id=868904ea95cc479aac2af649c1bd4745]

include::../../../../_custom-en/networks/physical-subnet-steps.adoc[]

. On the **Subnets** page, click **Create** in the upper-right corner.
. In the dialog box that appears, configure basic information for the physical subnet, and then click **Next**.
+
--
[cols='1a,3a']
|===
|Parameter |Description

|Name
|The name of the physical subnet.

include::../../../../_custom-en/networks/physical-network-naming-convention.adoc[]

|Description
|The description of the subnet.

include::../../../../_custom-en/networks/description-convention.adoc[]
|===
--
. In the **Network Info** step, configure network parameters for the subnet.  The following table describes the parameters.
+
--
include::../../../../_custom-en/networks/physical-subnet-parameters.adoc[]
--
. Click **OK**.  The subnet appears in the physical subnet list after it is created.