---
title: "Edit a physical subnet"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, physical subnets, edit"
description: "Describes how to edit a physical subnet in the {ks_product} web console."
weight: 04
logo: ""
downloadUrl: ""
---

// :ks_include_id: 82c617301419441389666cd4b627794e
:ks_xref_id: fecb07062dd4450f805d5f83d5bd0033
:ks_comp: ../../../../components/
:ks_title: Edit a physical subnet
:ks_description: Describes how to edit a physical subnet in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, physical subnets, edit
:ks_weight: 04
:ks_logo:
:ks_download_url:


This topic describes how to edit a physical subnet in the {ks_product_abbr_full} web console. The edit operation allows you to modify the name and description of a physical subnet.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=dd9314a275b84e1fa6712168c500e492]

include::../../../../_custom-en/nodes/prerequisites-view.adoc[]

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Edit from the list of physical subnetslink:[id=db60c754e79e46f3923437e972b730e5]

include::../../../../_custom-en/networks/physical-subnet-steps.adoc[]

. Find the physical subnet that you want to edit, click image:/images/ksv/en/icons/more.svg[operation-menu,13] on the right side, and then select **Edit** from the drop-down list.
. In the dialog box that appears, modify **Name** and **Description** of the physical subnet, and click **OK**.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Edit from the physical subnet details pagelink:[id=787fcfe4cd0c4529b28769282f362d74]

include::../../../../_custom-en/networks/physical-subnet-steps.adoc[]

. On the **Subnets** page, click the name of the physical subnet that you want to view. The details page of the physical subnet appears.
. On the left side of the physical subnet details page, click **Edit** in the upper-left corner.
. In the dialog box that appears, modify **Name** and **Description** of the physical subnet, and click **OK**.