---
title: "Delete physical subnets"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, physical subnets, deletion"
description: "Describes how to delete physical subnets in the {ks_product} web console."
weight: 05
logo: ""
downloadUrl: ""
---

// :ks_include_id: d1564aaa74744489af64a0b8b0f07be5
:ks_xref_id: 59c2bb8da59a4f9e8e9096078417f4ce
:ks_comp: ../../../../components/
:ks_title: Delete physical subnets
:ks_description: Describes how to delete physical subnets in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, physical subnets, deletion
:ks_weight: 05
:ks_logo:
:ks_download_url:


This topic describes how to delete physical subnets in the {ks_product_abbr_full} web console.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=fb69bb1baa5f4c11b5bde0e05d66b8e7]

* The user that you use has been granted the permissions to use the **Physical Resources** module.  The **Physical Resources** module is available only to user **admin**.
* A subnet in use cannot be deleted.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Delete a physical subnetlink:[id=a5d515f78db7470a8d4c0f2401e3120e]

include::../../../../_custom-en/networks/physical-subnet-steps.adoc[]

. Find the physical subnet that you want to delete, click image:/images/ksv/en/icons/more.svg[operation-menu,13] on the right side, and then select **Delete** from the drop-down list.
. In the dialog box that appears, click **OK**.
+
--
// Warning

include::../../../../../_ks_components/admonitions/warning.adoc[]

The physical subnet cannot be restored after it is deleted. Exercise caution when you perform this operation.

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]
--

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Delete multiple physical subnets at a timelink:[id=e66f1c49cba04c79a130a1e2ef42db34]

include::../../../../_custom-en/networks/physical-subnet-steps.adoc[]

. On the **Subnets** page, select the check boxes next to the physical subnets that you want to delete, and click **Delete**.
. In the dialog box that appears, click **OK**.
+
--
// Warning

include::../../../../../_ks_components/admonitions/warning.adoc[]

The physical subnets cannot be restored after they are deleted. Exercise caution when you perform this operation.

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]
--