---
title: "Edit a port forwarding rule"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, ports, forwarding, rules, edit"
description: "Describes how to edit a port forwarding rule in the {ks_product} web console."
weight: 05
logo: ""
downloadUrl: ""
---

// :ks_include_id: 6268a10733b346318914306e21eecdad
:ks_xref_id: f6b0f8d0aaf543c4b52dd4664fd971b9
:ks_comp: ../../../../components/
:ks_title: Edit a port forwarding rule
:ks_description: Describes how to edit a port forwarding rule in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, ports, forwarding, rules, edit
:ks_weight: 05
:ks_logo:
:ks_download_url:


This topic describes how to edit a port forwarding rule in the {ks_product_abbr_full} web console.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=8021aa00f5eb4d658ac58178fe076952]

* The user that you use has been granted permissions to manage VPCs.  User **admin** can manage all VPCs in your cluster. Project administrators and operators can manage the VPCs created on their own and have read-only permissions on the VPCs created by other users. Project viewers can view only the VPCs created in the projects to which they belong.
* If you log in as a non-admin user, you can only edit a port forwarding rule created on your own.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Procedurelink:[id=17a41b04958e4f50b5cde504075af476]

include::../../../../_custom-en/networks/vpc-steps.adoc[]

. On the **VPCs** page, click the name of a VPC to view its details.
. On the right side of the details page, click the **Port Forwarding** tab to view the port forwarding rules created for the VPC.
. Find the port forwarding rule that you want to edit, click image:/images/ksv/en/icons/more.svg[operation-menu,13] on the right side, and then select **Edit** from the drop-down list.
. In the dialog box that appears, configure parameters for the port forwarding rule.  For more information about parameters, see link:../04-add-port-forwarding-rule/[Add a port forwarding rule].
. Click **OK**.