---
title: "Edit a VPC"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, VPCs, edit"
description: "Describes how to edit a VPC in the {ks_product} web console."
weight: 08
logo: ""
downloadUrl: ""
---

// :ks_include_id: d6d59bce0c5a4f468b3ad2980639115d
:ks_xref_id: f351816697bf47439e2d34ad99009fc8
:ks_comp: ../../../../components/
:ks_title: Edit a VPC
:ks_description: Describes how to edit a VPC in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, VPCs, edit
:ks_weight: 08
:ks_logo:
:ks_download_url:


This topic describes how to edit a virtual private cloud (VPC) in the {ks_product_abbr_full} web console. The edit operation allows you to modify the name and description of a VPC. 

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=59a2dab34e07430b8a0ea951cac1a9e9]

include::../../../../_custom-en/networks/vpc-manage-prerequisites.adoc[]

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Edit from the list of VPCslink:[id=1cf8507a4bfc433bbe0638b74e18ab6e]

include::../../../../_custom-en/networks/vpc-steps.adoc[]

. Find the VPC that you want to edit, click image:/images/ksv/en/icons/more.svg[operation-menu,13] on the right side, and then select **Edit** from the drop-down list.
. In the dialog box that appears, modify **Name** and **Description** of the VPC, and click **OK**.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Edit from the VPC details pagelink:[id=357c332f628144e0b4a416068fdace30]

include::../../../../_custom-en/networks/vpc-steps.adoc[]

. On the **VPCs** page, click the name of a VPC to view its details.
. On the left side of the details page, click **Edit** in the upper-left corner.
. In the dialog box that appears, modify **Name** and **Description** of the VPC, and click **OK**.