---
title: "功能特性"
keywords: 视频点播, VOD, 视频点播
description: 本章节介绍云点播的功能特性。
draft: false
collapsible: false
weight: 20
---
本章节介绍云点播的功能特性。

== 音视频存储
[cols="1,3"]
|===
| 功能 | 功能说明

| 音视频上传
a| * 云点播支持多种方式上传，可通过控制台本地批量上传，也可以通过 SDK 上传。

* 单个上传文件最大支持 5GB，超出该大小可提交工单申请。
* 支持的上传格式：
** 视频：WMV、RM、MOV、MPEG、MP4、3GP、FLV、AVI、RMVB、TS、ASF、MPG、WEBM、MKV 、M3U8、WM、ASX、RAM、MPE、VOB、DAT、MP4V、M4V、F4V、MXF、QT、OGV。
** 音频：MP3、M4A、FLAC、OGG、WAV、RA、AAC、AMR。
| 音视频存储
a| * 音视频支持无限水平扩展，对存储空间与文件数量均无限制。

* 提供可靠的存储，数据持久性达 99.999999999%，服务可用性达 99.99%。

| 媒资管理
a| 支持针对媒资进行结构化管理，包含编辑媒资元数据信息、下载、播放URL查看等功能。

* 批量启动音视频处理，转码、水印、截取等。
* 一键禁播与解禁音视频播放。
* 多维度媒资筛选。
|===

== 音视频处理

音视频处理将音视频源文件进行转码、水印、截取等操作，在此过程中您可以改变音视频文件的封装格式、编码格式、码率、分辨率、帧率等参数，从而使音视频文件可以在不同的终端设备（手机、电脑、电视、大屏等）上进行播放。

* 可配置视频转码、自适应转码、音频转码、水印、裁剪模板；系统预置数十种模板，满足基础转码诉求。
* 支持配置任务流，将多模板组合发起转码任务。
* 转码完成后，自动进行存储，并生成播放 URL 供播放使用。

[cols="1,3,2"]
|===
| 类型 | 输入格式 | 输出格式

| 封装格式
| WMV、RM、MOV、MPEG、MP4、3GP、FLV、AVI、RMVB、TS、ASF、MPG、WEBM、MKV 、M3U8、WM、ASX、RAM、MPE、VOB、DAT、MP4V、M4V、F4V、MXF、QT、OGG
a| * 视频：FLV、MP4、HLS（m3u8+ts）、MPEG-DASH
* 音频：MP3、OGG、FLAC、m4a

| 视频编码格式
a| // AV1、AVS2、

H.264/AVC、H.263、 H.263+、H.265、MPEG-1、MPEG-2、MPEG-4、MJPEG、VP8、VP9、Quicktime、RealVideo、Windows Media Video
| H.264/AVC、 H.265/HEVC

| 音频编码格式
| AAC、ADPCM、AMR、DSD、MP1、MP2、MP3、PCM、RealAudio、Windows Media Audio、VORBIS
| MP3、AAC、FLAC
|===

== 音视频加速播放

[cols="1,2"]
|===
| 功能 | 功能说明

| 域名管理
a| * 平台提供默认域名可直接使用或自定义添加域名。
* 支持针对不同域名进行单独配置安全策略。

| 访问控制
a| * Referer防盗链可配置请求播放用户黑白名单。
* 支持针对不同自有域名设置证书。
| 播放器 SDK
| 提供 iOS/Android 播放器 SDK，支持播放、暂停、倍速播放、锁屏等功能。
|===
