---
title: "Cluster Management"
linkTitle: "Cluster Management"
keywords: "Kubernetes, KubeSphere, Cluster Management"
description: "Learn how to manage resources in a cluster."
weight: 07
---

This chapter explains how to manage all resources in individual or multiple clusters within KubeSphere as a cluster member.

KubeSphere supports the management of multiple clusters. Each cluster can be authorized for multiple workspaces. Each workspace can include multiple regular projects. As a multi-tenant system, KubeSphere supports role-based access control for user permissions at the platform, cluster, workspace, and project levels.

ifeval::["{file_output_type}" == "pdf"]

== Product Version

This document is applicable to {ks_product-en} v4.1.2.

== Target Readers

This document is primarily intended for the following readers:

* {ks_product-en} users
* Delivery engineers
* Operations engineers
* Post-sales engineers

== Revision History

[%header,cols="1a,1a,3a"]
|===
|Document Version |Release Date |Description

|01
|{pdf_releaseDate}
|Initial release.
|===
endif::[]