---
title: "View SSH keys"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, SSH, keys, list, view"
description: "Describes how to view SSH keys in the {ks_product} web console."
weight: 02
logo: ""
downloadUrl: ""
---

// :ks_include_id: e3926231fbf84a679a454079fcab264f
:ks_xref_id: 5b373e419657421fa9977726cb306d32
:ks_comp: ../../../components/
:ks_title: View SSH keys
:ks_description: Describes how to view SSH keys in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, SSH, keys, list, view
:ks_weight: 02
:ks_logo:
:ks_download_url:


This topic describes how to view SSH keys in the {ks_product_abbr_full} web console. For security purposes, each user can view only the SSH keys created on their own.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Procedurelink:[id=585409efec5b453ba49e5b0c7e5c1008]

include::../../../_custom-en/ssh/ssh-key-steps.adoc[]

+

--
You can view all SSH keys created on your own. The following table describes the parameters.

[cols="1a,4a"]
|===
|Parameter |Description

|Name
|The name of the SSH key.

include::../../../_custom-en/networks/naming-convention.adoc[]

|Encryption Method
|The encryption method of the SSH key.  By default, RSA is used for encryption.

|Created by
|The username that is used to create the SSH key.
|===
--

. (Optional) Click the search box above the SSH key list and specify query conditions to search for SSH keys by name. For example, use **Name:ab** to search for SSH keys whose name contains the string **ab**.
. (Optional) In the upper-right corner of the page, click image:/images/ksv/en/icons/refresh-light.svg[refresh,15] to refresh data.