---
title: "功能特性"
description: 本小节主要介绍 KubeSphere 企业版产品特性。 
keyword: KubeSphere 企业版,产品特性,功能简介 
weight: 03
collapsible: false
draft: false
---

KubeSphere 企业版提供以下丰富的功能。

== 丰富的可观测性

基于租户的跨集群、多维度监控，深度集成各种监控面板，为不同角色提供不同的监控维度。同时深度集成多种开源项目，提供多渠道、多配置的监控告警，丰富的日志、事件、审计等。

== 微服务治理

深度集成 Istio，内置微服务流量拓扑图，支持调整细颗粒度的流量治理策略，内置微服务链路追踪，无需手动配置。

== 集群与多租户

提供 Solo和 Federation 双模式集群管理方式，支持联邦应用框架，提供多租户的业务资源隔离管理、多层级的权限控制体系。

== 边缘节点

采用 KubeEdge 进行边缘节点纳管、组件部署和日志数据采集，结合 KubeEdge 边缘自治和 KubeSphere 多云多集群功能，实现“云、边、端”一体化管控。

== DevOps

深度集成 Jenkins 、Argo CD， ⽆需编写 Jenkinsfile 图形化流⽔线，内置流⽔线模板，支持基于代码（S2I）/制品（B2I）构建容器镜像。

== 应用全生命周期管理

在企业内部提供应用全生命周期的管理，包括应用的上架、下架、审核等，同时默认提供多种内置应用。

== RadonDB 容器化数据库

提供企业级 RadonDB 数据库服务，支持高可用架构、安全、自动备份、监控告警、自动扩容等全套管理功能。

== DMP 云原生数据库管理平台

解决多种数据库的跨云部署、多云管理难题，助力客户迈向多元混合的数据库新时代。覆盖 MySQL、PostgreSQL、Redis、MongoDB 等，构建高性能、备份、容灾、交换、流转等数据库生态闭环，实现数据库即服务（DBaaS）。

== 云原生安全

提供开箱即用的安全加固能力，覆盖安全编译、系统加固、应用安全、敏感数据保护、运维安全等领域。同时在安全能力上做了进一步增强，实现全链路覆盖，保障产品生命周期的持续安全更新。

== 企业运营

提升企业运营能力，提供自研租户企业空间，从组织架构维度隔离用户资源，同时支持多维度、多角度的计量与计费，满足企业内部结算需求。