title: "RadonDB DMP 数据库管理平台"

markup:
  asciidocExt:
    attributes:
      toc:
      toclevels: 2
      file_output_type: html
      relfilesuffix: /
      ks_product:  KubeSphere 企业版
      ks_product_left:  KubeSphere 企业版
      ks_product_right: KubeSphere 企业版
      ks_product_both:  KubeSphere 企业版

params:
  description: 这是 RadonDB DMP 数据库管理平台文档页面
  favicon: /images/favicon.ico
  keywords: 云计算,青云,QingCloud,文档,KubeSphere 企业版,KubeSphere, DMP, 数据库管理
  logo: /images/qingcloud-logo.svg
  logoInfo: RadonDB DMP 数据库管理平台
  logoLink: /       # 当前项目默认版本

  # PDF 配置
  pdf:
    toclevels: 4
    sectnumlevels: 6
    pdf_projectName: RadonDB DMP 数据库管理平台
    pdf_docVersion: '01'
    pdf_copyright: 版权所有 © 北京青云科技股份有限公司
    pdf_legalInfo: 版权所有 © 北京青云科技股份有限公司 2024。保留所有权利。
    pdf_projectVersion: '2.0.0'
    pdf_releaseDate: '2023-11-21'
    pdf_companyFullName: 北京青云科技股份有限公司
    pdf_companyName: 青云
    pdf_companyUrl: https://www.qingcloud.com
    pdf_companyIcon: /images/pdf/qingcloud-logo-icon.png
    pdf_coverDocName: RadonDB DMP 数据库管理平台 v2.0
    pdf_coverDocLogo: /images/pdf/qingcloud-logo-color.png
    pdf_coverDocImage: /images/pdf/cover_doc_image.svg
