---
title: "View the license agreement"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, license agreement, view"
description: "Describes how to view the end user software license agreement in the {ks_product} web console."
weight: 05
logo: ""
downloadUrl: ""
---

// :ks_include_id: adb501fbb5924dbe886b39d8ca363ebd
:ks_xref_id: d741429aeaa6478b95ece9af2842e2e3
:ks_comp: ../../../components/
:ks_title: View the license agreement
:ks_description: Describes how to view the end user software license agreement in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, license agreement, view
:ks_weight: 05
:ks_logo:
:ks_download_url:


This section describes how to view the license agreement of {ks_product_abbr_full}.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Procedurelink:[id=3ab75c6211704a7781abb1f67ddf838c]

. Log in to the {ks_product} web console.
. (Optional) Click image:/images/ksv/en/icons/cogwheel.svg[set-login-user,18px] in the upper-right corner, and select **About {ks_product}** from the drop-down list.
. In the dialog box that appears, click **End-user Software License Agreement**.
+
--
// Note

include::../../../../_ks_components/admonitions/note.adoc[]

If you have downloaded, copied, or installed the {ks_product} software or used it in any other way, you are deemed to have accepted the *End-user Software License Agreement*. Before you use the {ks_product} software, carefully read and fully understand the content of the *End-user Software License Agreement*.

include::../../../../_ks_components/admonitions/admonEnd.adoc[]
--