title: "QingStor U10000 文档"

markup:
  asciidocExt:
    attributes:
      toc:
      toclevels: 2
      file_output_type: html
      product_name: "QingStor U10000"

params:
  description: "这里是 QingStor U10000 文档中心页面"
  favicon: "/images/favicon.ico"
  keywords: "云计算,青云,QingCloud,文档"
  logo: "/images/qingcloud-logo.svg"
  logoInfo: "QingStor U10000"
  logoLink: /v5.0/        # 当前项目默认版本

  # PDF 配置
  pdf:
    pdf_projectName: QingStor U10000
    pdf_docVersion: 01
    pdf_copyright: 版权所有 © 北京青云科技股份有限公司
    pdf_legalInfo: 版权所有 © 北京青云科技股份有限公司 2022。保留所有权利。
    pdf_projectVersion: v4.1
    pdf_companyFullName: 北京青云科技股份有限公司
    pdf_companyName: 青云
    pdf_companyUrl: https://www.qingcloud.com
    pdf_companyIcon: /images/pdf/qingcloud-logo-icon.png
    pdf_coverDocName: QingStor U10000 v5.0
    pdf_coverDocLogo: /images/pdf/qingcloud-logo-color.png
    pdf_coverDocImage: /images/pdf/cover_doc_image.svg
    # pdf_only:
    #   -
    #     - /v4.1
    #     - /v4.1/installation/
    #     - /v4.1/qa/
    # pdf_only:
    #   -
    #     - /v4.1/_index.adoc
    #     - /v4.1/installation
    #     - /v4.1/qa
