---
title: "Edit a virtual subnet"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, virtual subnets, edit"
description: "Describes how to edit a virtual subnet in the {ks_product} web console."
weight: 04
logo: ""
downloadUrl: ""
---

// :ks_include_id: f491343bbedf4428b6cdcfcbe6426ca4
:ks_xref_id: 0132601b58964a11b4e6d2ec11492086
:ks_comp: ../../../../components/
:ks_title: Edit a virtual subnet
:ks_description: Describes how to edit a virtual subnet in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, virtual subnets, edit
:ks_weight: 04
:ks_logo:
:ks_download_url:


This topic describes how to edit a virtual subnet in the {ks_product_abbr_full} web console. The edit operation allows you to modify the name and description of a virtual subnet.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=028276c08b9340649ab34ad1702752f4]

include::../../../../_custom-en/networks/virtual-subnet-manage-prerequisites.adoc[]

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Edit from the list of virtual subnetslink:[id=9943bf8937674c5c97afb472577f27ec]

include::../../../../_custom-en/networks/virtual-subnet-steps.adoc[]

. Find the virtual subnet that you want to edit, click image:/images/ksv/en/icons/more.svg[operation-menu,13] on the right side, and then select **Edit** from the drop-down list.
. In the dialog box that appears, modify **Name** and **Description** of the virtual subnet, and click **OK**.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Edit from the virtual subnet details pagelink:[id=50a2d245338848279fedd260bc4f4cc1]

include::../../../../_custom-en/networks/virtual-subnet-steps.adoc[]

. On the **Subnets** page, click the name of the virtual subnet that you want to edit. The details page of the virtual subnet appears.
. On the left side of the subnet details page, click **Edit** in the upper-left corner.
. In the dialog box that appears, modify **Name** and **Description** of the virtual subnet, and click **OK**.