---
title: IAAS
weight: 10
---

== 支持本地盘迁移到云盘

目前企业云已经上线了 4 个不同的架构：SDS 1.0、SDS 2.0、SDS 3.0 和 SDS 4.0。

v6.1 版本支持从 SDS 1.0、SDS2.0 向 SDS 3.0 进行迁移，即 SDS 1.0、SDS 2.0 架构下的虚拟机可以向 SDS 3.0 架构进行离线迁移。

功能规则如下：

* 如果老的 SDS 架构中仅有系统盘，可以在线迁移；若挂有数据盘，仅支持离线迁移。
* 若想从老的架构迁移至最新的 SDS 4.0 架构，需要先将老的架构迁移至 SDS 3.0，然后再从 SDS 3.0 迁移至 SDS 4.0。

== 第三方存储支持多 VG

企业云 v6.1 版本之前，一个计算资源池只能对接一个存储池类型，但通常情况下，第三方存储的一个存储池内存在多个存储类型。

v6.1 版本支持一个计算资源池对接多个存储池类型（多个 VG），在选择主机系统盘规格和硬盘规格时，可以指定存储池。

== 支持 GPU 主机绑定到正确的 NUMA

主机通常有多个 NUMA 节点，创建的 GPU 云服务器需要绑定到正确的 NUMA 节点，才能正确绑定节点中的 CPU。

== 支持三网分离功能

支持“指定某个特定流量走哪个网络”的功能。满足安全审计要求：业务数据和管理数据必须隔离，备份流量、迁移流量走隔离网络，与虚拟机业务网络隔离开。

== Hyper 宕机检测功能优化

之前版本对 Hyper 的宕机检测，依赖 Hyper 的 pair 来定期远程检测，发现 Hyper 有问题，发起对 Hyper 的迁移。但是这种方式可能出现问题，当检查不及时，并且迁移后 Hyper 上资源可能没有销毁，网络可能还有残留，会影响迁移后的资源。

优化点：

* 复用当前远程检查宕机的逻辑 check_rescue_status() 函数，在本地也进行一次检查，主要检查每种存储类型的磁盘，系统盘和数据盘是否正常。
* 针对 sanc 类型，相比之前增加了 disk 的判断，最终实现是看 NeonSAN 的 qfcip 是否正常，正常表示存储正常，否则异常。
* 如果是远端存储，还会增加一些网络探测，探测到 leader/mirror/secmon 节点的网络是否可用。如果本身的管理网络正常，但是到 leader/mirror/secmon 节点都异常，也认为异常。

== 主机安置策略组优化

* 优化提示信息：当安置策略组的云服务器数量多大于 1 时，可能会根据资源分散策略对云服务器进行迁移，迁移操作可能会因为资源不足造成迁移失败，但迁移失败不会影响业务。
* 优化迁移逻辑：优化后的安置策略组的底层逻辑不会再对组内的 VM 进行迁移操作，会采用相对分散的逻辑在组内继续安置 VM。
