---
title: "计费说明"
description: 弹性容器实例计费说明。
keywords: 弹性容器实例,计费
draft: false
weight: 10
---
== 计费项

使用弹性容器实例 {qci_shortname}，涉及收费的资源项如下：

* *{qci_shortname} 实例*
+
创建 {qci_shortname} 实例时，对实例所使用的计算资源规格（CPU、内存）进行收费。

* *镜像缓存*
+
如果您需要使用镜像缓存，则需要支付缓存空间的费用。

* *其他资源*
+
{qci_shortname} 创建时指定的外部资源，如：硬盘、公网 IP、 VPC 网络资源费用将会另行收取费用。

== {qci_shortname} 实例计费

{qci_shortname} 实例费用即创建 {qci_shortname} 实例时，创建页面中显示的费用预览，指 {qci_shortname}  实例所使用的计算资源（CPU、内存）费用。

{qci_shortname} 实例才用按量付费，按小时扣费，计费时长从 {qci_shortname} 实例创建开始到 {qci_shortname} 实例销毁为止。

include::../../../../../_components/note.adoc[]

创建或启动失败的 {qci_shortname} 实例不会收取费用。

include::../../../../../_components/table_footer.adoc[]


== 镜像缓存计费

镜像缓存可以加速拉取镜像，减少 {qci_shortname} 实例启动的耗时。关于如何创建和使用镜像缓存，请参见link:../../manual/image_cache/introduction/[镜像缓存概述]。

镜像缓存与 {qci_shortname} 实例的计费相互独立。镜像缓存镜根据创建镜像缓存时所指定的缓存大小进行收费，按小时扣费，计费时长以镜像缓存创建时间为起点，镜像缓存销毁时间为终点。镜像缓存支持的大小区间为 [20G, 500G] ，默认大小 20G。

== 其他资源计费

根据业务需要，您可能需要用到青云云平台的网络和存储资源，相关说明如下：

[cols="1,3,2"]
|===
| 相关资源 | 说明 | 相关文档

| 公网 IP
| 如果您的 {qci_shortname} 实例需要进行公网通信，则需要配置公网 IP。
| link:/user_guide/network/eip/billing/[公网 IP 计费说明]

| VPC 网络
| {qci_shortname} 部署在 VPC 网络内，您需要创建 VPC 网络并支付相应费用。
| link:/user_guide/network/vpc/billing/price/[VPC 网络计费说明]

| 硬盘
| {qci_shortname} 实例支持挂载云硬盘实现持久化存储。根据您选择的存储类型，需要支付相应的存储费用。
| link:/user_guide/storage/disk/billing/price/[硬盘计费说明]
|===
