---
title: "产品简介"
description: "介绍 KubeSphere 及 v4.2 的核心特性。"
weight: 01
---

link:https://kubesphere.com.cn/kse/[KubeSphere]，是基于 Kubernetes 的分布式多租户商用云原生操作系统。在开源能力的基础上，在多云集群管理、微服务治理、应用管理、可观测等多个核心业务场景进行功能延伸。各功能实现高度模块化，满足不同场景的业务需求。以强大的企业级云原生底座，完善的专家级解决方案和服务支持，赋能企业数字化转型和规模化运营。

自 KubeSphere v4.0 起，引入扩展机制，推出了全新的架构：**KubeSphere LuBan**，它构建在 link:https://kubernetes.io/zh-cn/docs/concepts/extend-kubernetes/[Kubernetes] 之上，支持高度可配置和可扩展。KubeSphere 在 KubeSphere LuBan 云原生可扩展开放架构的基础之上，能轻松实现应用的上下游联动、随时随地集成各类优质扩展组件，并提供无缝融合的业务能力与高度一致的产品体验。


== 新特性

KubeSphere v4.2.1 不仅提升了容器管理的效率和灵活性，还通过引入新的功能和优化现有功能，为企业提供了一个更加强大和灵活的容器平台。

* **多集群管理优化**：提供 member 集群的一站式升级管理，支持快速更新至最新版本。通过直观易用的操作流程，显著降低升级复杂度，提升管理效率。同时，提供日志记录，完整追踪升级关键节点，为状态监控、问题排查与运营审计提供可靠依据。

* **网关优化**：提供集群级网关的一键升级与批量升级功能，旨在简化网关管理流程并提升操作效率。用户可以通过直观的界面，轻松实现单个或多个网关实例的快速升级，无需复杂的手动干预。

* **弹性伸缩**：支持容器水平扩容（HPA）、垂直扩容（VPA）、事件驱动伸缩（KEDA），简化了自动扩容策略，提高了资源利用率。

* **算力设备管理**：用于在 Kubernetes 集群中统一纳管 NVIDIA GPU、Ascend NPU 等多种异构计算设备。该扩展组件通过提供资源共享与隔离、智能调度、实时监控与告警，以及算力设备配额管理，提高设备利用率并简化 AI 集群的运维与调度复杂度。

* **Volcano**：是 Kubernetes 上专为批处理与高性能计算（HPC）场景打造的高性能工作负载调度器。它扩展了 Kubernetes 原生调度能力，引入队列（Queue）、组调度（Gang Scheduling）、资源配额、优先级与抢占等高级机制，确保计算密集型任务能够高效、成组地调度运行，显著提升集群资源利用率和任务执行效率。

* **节点组**：一个专为简化 Kubernetes 集群节点管理而设计的扩展组件。它通过直观的图形化界面，允许管理员根据节点的硬件属性、业务角色或环境逻辑，灵活地对集群内大量异构节点进行可视化分组与标记。

* **对象存储加速**：Fluid 通过将远端对象存储中的数据抽象为 Kubernetes 可调度的资源，在计算集群内自动构建分布式缓存层。该缓存层对应用透明，能将热点数据缓存在计算节点本地，并通过数据亲和性调度，让计算任务就近访问数据，从而显著降低访问延迟、提升 I/O 性能并减少对后端存储的直接依赖与带宽成本。

* **NFS 加速**：Fluid 支持为 Kubernetes 环境中的网络文件系统（NFS）提供加速功能。该组件通过在集群内构建高效的分布式缓存层，实现将热点数据缓存至各节点本地，从而增强了数据的本地访问速度。Fluid 结合了 Alluxio 的先进缓存机制与智能调度策略，有效减轻了后端 NFS 服务器的负载，显著降低了网络延迟，优化了整体的输入/输出（I/O）性能。

link:https://kubesphere.cloud/docs/kse/release-notes/v4.2.1[点击此处]查看当前版本的更新详情，包括新特性、功能增强以及问题修复。



