---
title: "DescribeVxnetInstances"
description: 获取私有网络中的{instance_product_name_cn}。
keywords: VPC, 私有网络
weight: 6
draft: false
---
获取私有网络中的{instance_product_name_cn}。

可通过{instance_product_name_cn} ID，镜像 ID，{instance_product_name_cn}配置类型，{instance_product_name_cn}状态作为过滤条件进行筛选。

== 请求参数

|===
| 参数 | 参数类型 | 描述 | 是否必选

| vxnet
| String
| 私有网络ID
| Yes

| instances.n
| String
| {instance_product_name_cn}ID
| No

| instance_type
| String
| {instance_product_name_cn}配置类型
| No

| status
| String
| {instance_product_name_cn}状态
| No

| image
| String
| 镜像ID
| No

| offset
| Integer
| 数据偏移量，默认为 0
| No

| limit
| Integer
| 返回数据长度，默认为 20，最大 100
| No

| zone
| String
| 区域 ID，注意要小写
| Yes
|===

link:../../../introduction/parameters/[公共参数]

== 返回数据
[cols="1,1,3"]
|===
| 参数 | 参数类型 | 描述

| action
| String
| 响应动作

| instance_set
| Array
| JSON 格式的私有网络的{instance_product_name_cn}列表，每项数据详见 <<responseitemtype,ResponseItemType>>

| total_count
| Integer
| 根据过滤条件得到的{instance_product_name_cn}总数

| ret_code
| Integer
| 执行成功与否，0 表示成功，其他值则为错误代码
|===

[[responseitemtype]]*ResponseItemType*

[cols="1,1,3"]
|===
| 参数 | 参数类型 | 描述

| vxnet_id
| String
| 私有网络 ID

| instance_id
| String
| {instance_product_name_cn}ID

| instance_name
| String
| {instance_product_name_cn}名称

| description
| String
| {instance_product_name_cn}描述

| instance_type
| String
| {instance_product_name_cn}类型。

| vcpus_current
| Integer
| {instance_product_name_cn}CPU核心数目。

| memory_current
| Integer
| {instance_product_name_cn}内存大小，单位为MB。

| status
| String
| {instance_product_name_cn}状态，有效值为pending, running, stopped, suspended，terminated, ceased。 +
pending： 等待被创建 +
running： 运行中 +
stopped： 已关机 +
suspended： 由于欠费，已被暂停使用 +
terminated： 已被删除，但处于此状态的{instance_product_name_cn}在2小时之内仍可以被恢复为 running 状态 +
ceased： 已被彻底删除，处于此状态的{instance_product_name_cn}无法恢复

| transition_status
| String
| {instance_product_name_cn}过渡状态，有效值为creating、starting、stopping、restarting、suspending、resumin、terminating、recovering、resetting。 +
creating： 创建中，由 pending 状态变成 running 状态 +
starting： 启动中，由 stopped 状态变成 running 状态 +
stopping： 关闭中，由 running 状态变成 stopped 状态 +
restarting： 重启中 +
suspending： 欠费暂停中，由 running/stopped 状态变成 suspended 状态 +
resuming： 恢复中，由 suspended 状态变成 running 状态 +
terminating： 删除中，由 running/stopped/suspended 状态变成 terminated 状态 +
recovering： 恢复中，由 terminated 状态变成 running 状态 +
resetting： 操作系统重置中

| create_time
| TimeStamp
| {instance_product_name_cn}创建时间，为UTC时间，格式可参见 http://www.w3.org/TR/NOTE-datetime[ISO8601]。

| status_time
| TimeStamp
| {instance_product_name_cn}最近一次状态变更时间，为UTC时间，格式可参见 http://www.w3.org/TR/NOTE-datetime[ISO8601]。

| image_id
| String
| {instance_product_name_cn}的模板ID。

| dhcp_options
| Dict
| 私有网络中针对该{instance_product_name_cn}的 DHCP 配置。

| private_ip
| String
| {instance_product_name_cn}的位于该私有网络的IP。
|===

== 示例

*请求示例：*
[source]
----
https://api.domain.com/iaas/?action=DescribeVxnetInstances
&vxnet=vxnet-ytuyg2q
&status=running
&limit=1
&COMMON_PARAMS
----

*返回示例：*
[source]
----
{
  "action":"DescribeVxnetInstancesResponse",
  "instance_set":[
    {
      "vcpus_current":1,
      "instance_id":"i-syx7qtud",
      "image_id":"centos64x64",
      "vxnet_id":"vxnet-ytuyg2q",
      "sequence":0,
      "sub_code":0,
      "transition_status":"",
      "instance_name":"",
      "instance_type":"small_b",
      "create_time":"2013-08-30T09:13:37Z",
      "status":"running",
      "private_ip":"192.168.1.2",
      "description":null,
      "status_time":"2013-08-30T09:13:37Z",
      "nic_id":"52:54:5b:e3:69:f4",
      "dhcp_options":{
        "val2":"domain-name-servers=8.8.8.8",
        "router_static_id":"rtrs-jak6z5nx"
      },
      "memory_current":1024
    }
  ],
  "ret_code":0,
  "total_count":1
}
----
