---
title: "View disks"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, images, list, view"
description: "Describes how to view disks in the {ks_product} web console."
weight: 02
logo: ""
downloadUrl: ""
---

// :ks_include_id: 851fe8387a3144048e8c6b727b2b199f
:ks_xref_id: ba080e32060345289e4d82d71cc368b9
:ks_comp: ../../../components/
:ks_title: View disks
:ks_description: Describes how to view disks in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, images, list, view
:ks_weight: 02
:ks_logo:
:ks_download_url:


This topic describes how to view disks in the {ks_product_abbr_full} web console.

include::../../../_custom-en/disks/disk-view-limits.adoc[]

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Procedurelink:[id=b1e0eb3eb9d548e0bed1e6792e51f20a]

include::../../../_custom-en/disks/disk-steps.adoc[]

+

--
You can view all disks in the project.  The following table describes the parameters.

[cols="1a,4a"]
|===
|Parameter |Description

|Name
|The custom name of the disk.

include::../../../_custom-en/vms/vm-naming-convention.adoc[]

|ID
|The universally unique identifier (UUID) of the disk in the system.

|Status
|The status of the disk.

|Size
|Th size of the disk.

|VM
|The VM to which the disk is mounted.

|Project
|The project name in which the disk is created.

|Created by
|The username that is used to create the disk.
|===
--

. (Optional) Click the search box above the disk list and set query conditions to search for disks by name or ID.  For example, use **Name:ab** to search for disks whose name contains the string **ab**.
. (Optional) In the upper-right corner of the page, click image:/images/ksv/en/icons/refresh-light.svg[refresh,15] to refresh data.