---
title: "Resize disk resources"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, disks, resources, resize"
description: "Describes how to resize disk resources in the {ks_product} web console."
weight: 05
logo: ""
downloadUrl: ""
---

// :ks_include_id: 9942a5c749a94b96a5b9701b0f904b67
:ks_xref_id: f9b8d6252e07442b9dd7d8f740a89f88
:ks_comp: ../../../components/
:ks_title: Resize disk resources
:ks_description: Describes how to resize disk resources in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, disks, resources, resize
:ks_weight: 05
:ks_logo:
:ks_download_url:


This topic describes how to resize disk resources in the {ks_product_abbr_full} web console.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=ad0f8959995346a4890d7032e3b91d7c]


:relfileprefix: ../../../

include::../../../_custom-en/disks/disk-manage-prerequisites.adoc[]

:relfileprefix: ./


ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Resize from the list of diskslink:[id=423c50e25d6944b49e447bd15a2614e5]

include::../../../_custom-en/disks/disk-steps.adoc[]

. Find the disk that you want to resize, click image:/images/ksv/en/icons/more.svg[operation-menu,13] on the right side, and then select **Resize** from the drop-down list.
. In the dialog box that appears, modify the disk size and click **OK**.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Resize from the disk details pagelink:[id=aba2624963d346719603fbf3cc2a6508]

include::../../../_custom-en/disks/disk-steps.adoc[]

. On the **Disks** page, click the name of the disk that you want to manage. The details page of the disk appears.
. On the left side of the disk details page, click **Resize**.
. In the dialog box that appears, modify the disk size and click **OK**.