---
title: "Restore a disk from snapshots"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, disks, snapshots, restoration"
description: "Describes how to restore a disk from snapshots in the {ks_product} web console."
weight: 07
logo: ""
downloadUrl: ""
---

// :ks_include_id: 852e45151e194c4da3e2044943b5f4d4
:ks_xref_id: 849b5fed965b41469580fe50c294f1cb
:ks_comp: ../../../components/
:ks_title: Restore a disk from snapshots
:ks_description: Describes how to restore a disk from snapshots in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, disks, snapshots, restoration
:ks_weight: 07
:ks_logo:
:ks_download_url:


This topic describes how to restore a disk from snapshots in the {ks_product} web console. After a disk is created, if you have created snapshots for the disk, you can restore the disk from snapshots.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=61d9e39d1a1545cc88f343931b65bf6e]


:relfileprefix: ../../../

include::../../../_custom-en/disks/disk-manage-prerequisites.adoc[]

:relfileprefix: ./


ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Procedurelink:[id=58244af7f74e4d598af15ef0ee5a479d]

include::../../../_custom-en/disks/disk-steps.adoc[]

. On the **Disks** page, click the name of the disk that you want to manage. The details page of the disk appears.
. On the **Snapshots** tab, find the snapshot from which you want to restore the disk, click image:/images/ksv/en/icons/more.svg[operation-menu,13], and then select **Restore Disk** from the drop-down list.
. In the dialog box that appears, set **Name** and **Description** for the restoration record.
+
--
[cols="1a,4a"]
|===
|Parameter |Description

|Name
|The name of the restoration record.

include::../../../_custom-en/networks/naming-convention.adoc[]

|Description
|The description of the restoration record.

include::../../../_custom-en/networks/description-convention.adoc[]
|===
--
. Click **OK**.