---
title: "Edit a disk snapshot"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, disks, snapshots, edit"
description: "Describes how to edit a disk snapshot in the {ks_product} web console."
weight: 08
logo: ""
downloadUrl: ""
---

// :ks_include_id: e9aaa86af2e24af496fbdfe16ad64931
:ks_xref_id: ed8ddae651524c2b95ccbac5e4504762
:ks_comp: ../../../components/
:ks_title: Edit a disk snapshot
:ks_description: Describes how to edit a disk snapshot in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, disks, snapshots, edit
:ks_weight: 08
:ks_logo:
:ks_download_url:


This topic describes how to edit a disk snapshot in the {ks_product} web console. The edit operation allows you to modify the name and description of a snapshot.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=73fe697a50bb4ee9ab82057d325b39f2]


:relfileprefix: ../../../

include::../../../_custom-en/disks/disk-manage-prerequisites.adoc[]

:relfileprefix: ./


ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Procedurelink:[id=da767e1b7d804ad2acc6409220a942d7]

include::../../../_custom-en/disks/disk-steps.adoc[]

. On the **Disks** page, click the name of the disk that you want to manage. The details page of the disk appears.
. On the **Snapshots** tab, find the snapshot that you want to edit, click image:/images/ksv/en/icons/more.svg[operation-menu,13], and then select **Edit** from the drop-down list.
. In the dialog box that appears, set **Name** and **Description** for the snapshot.
+
--
[cols="1a,4a"]
|===
|Parameter |Description

|Name
|The name of the snapshot.

include::../../../_custom-en/disks/disk-snapshot-naming-convention.adoc[]

|Description
|The description of the snapshot.

include::../../../_custom-en/networks/description-convention.adoc[]
|===
--
. Click **OK**.