---
title: "弹性裸金属云服务器"
weight: 25
keywords: 云计算, 青云, QingCloud, 云服务器,专业级云服务器,弹性裸金属
---

== 产品介绍

{platform_name_cn} 弹性裸金属服务器服务，提供高性能、资源独享、安全隔离的专属弹性裸金属服务器群组，满足各类核心应用对高性能及稳定性的需求，同时提供完整的设备管理权限及运维服务。 用户可以像使用其他云资源一样，快速、灵活的部署及管理弹性裸金属服务器，并可按需弹性购买。

== 产品优势

* **承载核心业务**
+
独享物理隔离的硬件资源，释放极致性能，匹配 VPC 网络赋予的完整控制能力， 满足核心业务对性能、可靠性及安全合规的苛刻需求。

* **高效的资源交付**
+
10 分钟完成 OS 部署上线，自动化配置，秒级操作响应，兼容所有云服务器系统镜像及用户自有镜像，助您轻松完成基础架构部署。

* **灵活简便的使用体验**
+
VPC 网络直连，提供与云服务器一致的使用方式，支持弹性伸缩、按需秒级计费及 API 自动化管理，赋予弹性裸金属服务器弹性、灵活与敏捷的云端特性。


== 实例规格

弹性裸金属云服务器采用第三代英特尔®至强®可扩展处理器（代号：Ice Lake）和 DPU 架构，通过引入智能网卡，实现存储、网络等数据处理功能卸载，让用户可**独享 CPU 计算资源**，实现裸金属服务器的完整算力保留，以极致性能满足各类核心业务需求。

弹性裸金属 BM3 *同时具备云服务器的弹性、敏捷性、灵活性与高可用*，支持按需使用，且用户业务应用可直接访问处理器和内存，无任何虚拟化开销。其特点：

* 第三代英特尔®至强®可扩展处理器（Ice Lake），主频：2.6GHz，睿频：3.4GHz。
* 具有 128 核、512G 内存的超强算力。
* 通过在服务器侧引入智能网卡，将网络、存储、操作系统中不适合由 CPU 支持的高性能数据处理功能卸载到智能网卡中执行。
* I/O 优化。
* 支持 VPC 私有网络和基础网络。
* 系统盘支持增强型 SSD 和通用型 SSD。

弹性裸金属包括的实例规格和性能指标如下，仅在北京三区或宁夏一区可创建弹性裸金属服务器。

[options="header",cols="3,2,2,2,2"]
|===
| 实例类型 | CPU | 内存 | 内网带宽 |所在区域

| bm3
| 128 核
| 512G
| 32 Gbps
| 北京 3 区

|bm1
|128 核
|1024G
|50 Gbps
|宁夏 1 区
|===
