---
title: "产品功能"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, 功能"
description: ""
weight: 03
logo: ""
downloadUrl: ""
---

// :ks_include_id: b0da22133b0d4be38ad042b0f355cb80
:ks_xref_id: aef708967db24f519476e8a893b93468
:ks_comp: ../../components/
:ks_title: 产品功能
:ks_description:
:ks_keywords: {ks_product_full}, {ks_product}, 功能
:ks_weight: 03
:ks_logo:
:ks_download_url:


{ks_product_right}提供便捷、灵活、易用的 Web 控制台，帮助您以极高的效率和极低的成本快速实现计算、网络、存诸资源的虚拟化。

{ks_product_right}提供以下四大核心功能：

* 实时资源监控：提供集群资源和虚拟资源的概览信息、每类资源的汇总列表和单个资源详情，帮助您实时掌控基础设施环境计算、网络、存储资源的使用情况以及{ks_product_both}平台各类虚拟资源的实时状态。
* 便捷资源管理：提供便捷的资源管理界面，帮助您快速创建、删除、复制、迁移各类资源，并支持在 KSV 平台上直接对虚拟机进行远程操控。
* 运维管理：提供定时器、监控告警和日志管理功能，帮助您建立快速响应并适应企业业务环境和业务发展的 IT 运维模式。
* 灵活分权分域：提供多租户功能，支持按项目隔离用户和虚拟资源，根据用户的角色控制用户的权限。

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== 实时资源监控link:[id=38a80f5282f24efea86214a5950e292c]

{ks_product_right}Web 控制台的概览功能从虚拟机、磁盘、网络、物理节点、CPU、内存等维度实时展示集群中的资源情况。

您可以通过平台总览页面实时获取以下资源信息：

* 虚拟机、磁盘、网络和告警：分别查看集群中各状态的虚拟机和磁盘数量，虚拟子网、VPC 网络和物理子网数量，以及系统中存在的告警信息。
* 虚拟资源：查看 CPU、内存和存储资源用量情况。
* 物理节点：查看集群中的控制节点和工作节点总数、各状态节点的数量以及集群超卖比。
* 物理资源使用情况：查看集群中物理节点的 CPU、内存和磁盘用量情况。
* 系统组件：查看集群中各系统组件的运行情况。
* CPU 使用率 Top 5、内存使用率 Top 5和节点使用率 Top 5：分别查看集群中特定资源用量最高的 5 台虚拟机和节点的名称及资源用量情况。

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== 便捷资源管理link:[id=52375288593c40188b4eb0b11480f536]

您可以通过{ks_product_both}Web 控制台管理以下**物理资源**：

* 物理节点：节点是{ks_product_both}集群中的基础服务器，在集群节点上可以创建虚拟机。节点管理功能提供物理节点、物理硬盘、物理网卡的汇总列表以及各物理节点、物理硬盘、物理网卡的详情，帮助您快速获取物理节点的实时状态。
* 物理网络：通过配置物理网络，您可以直接给容器分配物理网络中的地址资源，也可以利用物理网络的连通性达到更好的性能。
* 物理子网：您可以将物理网络划分为多个物理子网，各物理子网间逻辑上相互隔离。同一物理子网中的虚拟机互联互通。
* 弹性网络：弹性 IP 为您提供独立的公网 IP 资源，包括公网 IP 地址。您可以通过配置弹性网络指定弹性 IP 使用的物理网段范围。

您可以通过{ks_product_both}Web 控制台管理以下**虚拟资源**：

* 项目：项目用于对资源进行分组管理。您可以将用户分配到项目中，并指定用户的角色以控制用户在项目中的权限。
* 虚拟机：具有独立 IP 地址的虚拟机实例，可以访问公共网络，运行应用服务。
* 虚拟机模板：包含了虚拟机的具体配置，如客机操作系统、CPU、内存、系统盘、数据盘和网络等配置。您可以使用虚拟机模板创建虚拟机，也可以将现有虚拟机转化为模板。
* 虚拟机镜像：虚拟机的一种标准交付物，用于打包虚拟机相关配置及其依赖的环境。不同的镜像可以包含不同的操作系统配置，如 Fedora、CentOS 和 Ubuntu 等。
* 磁盘：为虚拟机提供的块级别的虚拟存储资源，以文件夹的形式存在于宿主机上。
* VPC 网络：云上私有网络，不同的 VPC 之间逻辑上完全隔离。
* 子网：VPC 内的 IP 地址范围。
* 弹性 IP：互联网上的合法静态 IP 地址，支持与虚拟机灵活的绑定或解绑。
* 安全组：一种虚拟防火墙，用于控制与其关联资源的入流量和出流量，从而提高关联资源的安全性。
* SSH 密钥：通过加密算法生成一对密钥，由公钥和私钥组成，默认采用 RSA 加密方式。

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== 运维管理link:[id=ac7a44df20f245c08e22b2384af4e875]

{ks_product_right}提供以下运维工具，帮助您实时监控用户应用及相关云资源，让您一站式完成云上运维：

* 定时器：用来定期执行一系列任务，比如定时开关主机、创建备份等。您可以通过定时策略定义执行周期，任务可以在指定的周期重复执行，也可仅执行一次。
* 监控告警：用于监控集群资源。您可以创建告警策略，并在告警策略触发后查看告警消息。
* 包括系统日志和操作日志，系统日志收集系统中的日志数据，操作日志可以用于查看用户的操作记录。

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== 灵活分权分域link:[id=26acdd6800fb498790595b864cb04f8c]

{ks_product_right}支持多租户功能，可实现根据项目和用户角色对资源进行分权分域管理。

* 用户管理： {ks_product_right}提供在平台上具有最高权限的默认 **admin** 用户。您可以使用 **admin** 用户在{ks_product_both}平台上创建多个普通用户，并指定普通用户的登录信息、项目和项目角色。普通用户根据其项目角色在特定项目中拥有不同的资源管理权限。
* 项目管理：在{ks_product_both}平台上可创建多个项目用于对虚拟机、镜像和磁盘等资源进行分组管理。每个项目可以包含多个用户，项目中的用户根据其项目角色具有不同的资源管理权限。
+
--
KSV 提供以下默认项目角色类型：

[cols="1a,3a"]
|===
|角色 |权限

|管理员
|项目管理员，可以管理项目中的所有资源。

|操作员
|项目操作员，可以管理项目中除用户和角色之外的资源。

|观察员
|项目观察员，可以查看项目中所有的资源。
|===
--