---
title: '获取指定租赁合同信息（GetLeaseContracts）'
weight: 11
---

== 基本信息

=== Path
/iaas

=== Method
GET

== 请求参数
[cols="1,1,1,2", options="header"]
|===
| 参数名 | 类型 | 是否必须 | 描述

| contracts
| Array
| false
| 合同ID
|===

== 返回数据
此接口除以下返回参数外，还包含公共响应头。关于公共响应头的更多信息，请参见link:../../../../overview/#_api_返回结构[前文内容]。
[cols="1,1,1,2", options="header"]
|===
| 参数名 | 类型 | 是否必须 | 描述

| lease_contract_set
| Object
| false
| 返回的

| lease_contract_set.auto_renew
| Integer
| false
| 用户设置合同到期后的续费时长

| lease_contract_set.charge_mode
| String
| false
| 计费模式

| lease_contract_set.console_id
| String
| false
| 控制台ID

| lease_contract_set.contract_id
| String
| false
| 合同ID

| lease_contract_set.create_time
| String
| false
| 合同创建时间

| lease_contract_set.discount
| Integer
| false
| 合同折扣

| lease_contract_set.duration
| String
| false
| 合同周期

| lease_contract_set.end_time
| String
| false
| 合同结束时间

| lease_contract_set.long_resource_id
| String
| false
| 

| lease_contract_set.next_charge_mode
| String
| false
| 用户设置合同到期转换的计费模式

| lease_contract_set.price
| String
| false
| 合同价格

| lease_contract_set.price_info
| Object
| false
| 合同配置

| lease_contract_set.price_info.TODO
| String
| false
| 待定义（动态结构，参考示例）

| lease_contract_set.product_id
| String
| false
| 合同使用的促销ID

| lease_contract_set.resource_id
| String
| false
| 资源ID

| lease_contract_set.start_time
| String
| false
| 合同开始时间

| lease_contract_set.zone_id
| String
| false
| 区域ID
|===

== 请求示例
[,javascript]
----
{
  "action": "GetLeaseContracts",
  "contracts": [
    "ct-PyrRmzpS"
  ]
}
----

== 返回示例
[,javascript]
----
{
  "action": "GetLeaseContractsResponse",
  "contracts": [
    "ct-PyrRmzpS"
  ],
  "lease_contract_set": {
    "ct-PyrRmzpS": {
      "auto_renew": null,
      "charge_mode": "elastic",
      "console_id": "qingcloud",
      "contract_id": "ct-PyrRmzpS",
      "create_time": "2020-11-24T11:48:14",
      "discount": 100,
      "duration": 3600,
      "end_time": null,
      "group_id": "1",
      "long_resource_id": null,
      "next_charge_mode": null,
      "price": 0,
      "price_info": {
        "aid": "app-00r26u27",
        "avv": "public",
        "cid": "cl-lns2nvdi",
        "eid": "appe-rgowerow",
        "md": {
          "nd": [
            {
              "cnt": 0,
              "r": "proxy"
            }
          ]
        },
        "pts": [
          "cluster"
        ],
        "stat": "active",
        "zone": "gd2a"
      },
      "product_id": null,
      "resource_id": "clv-lns2nvdi",
      "start_time": "2020-11-24T11:51:15",
      "zone_id": "gd2"
    }
  },
  "ret_code": 0
}
----
