---
title: 查询用户的所有租赁信息（GetLeasingResources）
weight: 14
---

== 基本信息

=== Path
/iaas

=== Method
GET

== 请求参数
[cols="1,1,1,2", options="header"]
|===
| 参数名 | 类型 | 是否必须 | 描述

| console
| String
| false
| private

| excluded_user
| String
| false
| private

| limit
| Integer
| false
| private

| offset
| Integer
| false
| private

| reverse
| Integer
| false
| private

| root_user
| String
| false
| private

| status
| String
| false
| private

| user
| String
| false
| private

| zone
| String
| false
| private
|===

== 返回数据
此接口除以下返回参数外，还包含公共响应头。关于公共响应头的更多信息，请参见link:../../../../overview/#_api_返回结构[前文内容]。
[cols="1,1,1,2", options="header"]
|===
| 参数名 | 类型 | 是否必须 | 描述

| auto_renew
| Integer
| false
| 用户设置合同到期后的续费时长

| charge_mode
| String
| false
| 计费模式

| console_id
| String
| false
| 控制台ID

| duration
| String
| false
| 合同周期

| group_id
| String
| false
| 

| lease_time
| String
| false
| 租赁开始时间

| price
| String
| false
| 合同价格

| price_info
| String
| false
| 合同配置

| renewal_time
| String
| false
| 租赁到期时间

| resource_id
| String
| false
| 资源ID

| root_user_id
| String
| false
| 主用户ID

| status
| String
| false
| 租赁状态

| status_time
| String
| false
| 租赁状态变更时间

| unlease_time
| String
| false
| 解除租赁时间

| user_id
| String
| false
| 用户ID

| zone_id
| String
| false
| 区域ID
|===

== 请求示例
[,javascript]
----
{
  "action": "GetLeasingResources",
  "excluded_user": "",
  "limit": 20,
  "offset": 0,
  "root_user": "",
  "status": [],
  "user": "usr-Kz8eMmMv",
  "zone": "test"
}
----

== 返回示例
[,javascript]
----
{
  "action": "GetLeasingResourcesResponse",
  "leasing_resource_set": [
    {
      "auto_renew": null,
      "charge_mode": "elastic",
      "console_id": "qingcloud",
      "duration": 3600,
      "group_id": "1",
      "lease_time": "2021-10-25T12:51:22Z",
      "price": "0",
      "price_info": "{\"md\":{\"nd\":[{\"c\":1,\"g\":0,\"m\":1024,\"cnt\":1,\"stor\":4,\"repl\":1,\"sc\":100,\"hpvr\":\"kvm\",\"gcls\":0,\"cls\":101}]},\"stat\":\"active\",\"zone\":\"sh1b\",\"cid\":\"cl-co1k92ui\",\"avv\":null,\"aid\":\"app-qingcloud-appcenter-metadata\",\"pts\":[\"cluster\"]}",
      "renewal": "auto",
      "renewal_time": "2021-11-01T13:51:22Z",
      "resource_id": "cl-co1k92ui",
      "root_user_id": "usr-Kz8eMmMv",
      "status": "active",
      "status_time": "2021-10-25T12:52:29Z",
      "unlease_time": null,
      "user_id": "usr-Kz8eMmMv",
      "zone_id": "sh1"
    }
  ],
  "total_count": 32
}
----
