---
title: "配置 BOSS 邮件告警"
weight: 60
---

配置邮件后，找回密码、二次认证、密码过期通知、告警通知和生成日报表等功能才能正常使用。

== 前提条件

* 已准备好邮件服务器地址、用户名和密码。
* 以下节点IP 开通到邮件服务器和 DNS 的网络策略。
 ** dnsmaster0/1
 ** boss0/1
 ** proxy0/1

== 配置步骤

1. 登录 FirstBox。
2. 执行以下命令，修改配置文件 boss2.yaml.ZONE_ID。
+
[source]
----
vim /pitrix/conf/variables/boss2/boss2.yaml.ZONE_ID 
----
+
**参数说明**：
+
[cols='1,3'] 
|===
| 参数 | 说明 

| host | SMTP 邮件 服务器地址。
| user | 邮件服务器用户名。
| password | 邮件服务器密码。
| port | SMTP 邮件服务器端口，默认为 25。无需修改。
| use_localtime | false。
| encrypt | 选择加密方法，支持 SSL、TLS。None 表示不加密。
| ssl_keyfile | 若加密方法选择 SSL，需要配置 keyfile。 
| ssl_certfile | 若加密 方法选择 SSL，需要配置 certfile。
| timeout | 邮件超时时长。null 表示不超时。
| subject_prefix | 邮件标题前缀，可设置为 `[BOSS2]`。
| from_user | 邮件的发件人名字（不是邮箱地址）。
| from_addr | 邮件的发件地址，可保持和邮件的账号一致以免被退信。
|===
+
**配置示例**：
+
[source,yaml]
----
email:
  host: '10.1.188.82'
  user: 'lixiang@cebbank.com' 
  password: 'L0fXAIRGac33+N4HoeSL5w==' 
  port: 25
  use_localtime: false 
  encrypt: '' 
  ssl_keyfile: null 
  ssl_certfile: null
  timeout: null
  subject_prefix: '[BOSS2-cebdaas2a]' 
  from_user: 'BOSS2-cebdaas2a' 
  from_addr: 'lixiang@cebbank.com'
----
+

include::../../../../_components/note.adoc[]
配置完成后，若没有生效，请检查 BOSS 主机上的日志文件 /pitrix/log/*。

include::../../../../_components/table_footer.adoc[]

3. 执行以下命令，下发 boss2.yaml 配置。
+
[source]
----
/pitrix/build/build_pkgs.py -p pitrix-ks-boss2-conf
/pitrix/upgrade/update.sh boss pitrix-ks-boss2-conf
/pitrix/upgrade/exec_nodes.sh boss 'supervisorctl restart boss2_manager'
----

== 功能测试

**方式一：发送测试邮件**

1. 登录 FirstBox。
2. 执行如下命令，发送一封测试邮件，检验配置是否正常。
+
[source]
----
Boos2 send_email <收件邮箱>
----
+
邮件发送是异步任务，若收件邮箱成功收到告警邮件，则配置成功。

**方式二：API 接口邮件测试方法（参考）**

1. 登录 FirstBox 。
2. 执行如下操作。
+
[source]
----
curl -X POST	http://<proxy vip>:<port>/alert_receiver/nf/	-H 'Content-Type: application/json'	-H 'cache-control: no-cache'	-d '{
"action": "PushAlert",
"data": {
  "alertList": [
    {
      "alertDesc": "[<zone id>] [<zone id>] has alerts |@@|=== test.log.wf ===|@@|this is a test alert",
      "alertTime": ""
    }
  ]
}
}'
----
+
**参数说明**：
+
[cols='1,3'] 
|===
| 参数 | 说明 

| proxy vip | proxy 的虚拟 IP 地址。请根据实际环境进行修改。
| port | 端口号，固定为 6777 。
| zone id | 可用区 ID 。请根据实际环境进行修改。
| alertTime | 告警时间，根据实际情况修改。接近当前时间即可。
|===
+
**配置示例**：
+
[source]
----
curl -X POST	http://10.200.5.172:6777/alert_receiver/nf/	-H 'Content-Type: application/json'	-H 'cache-control: no-cache'	-d '{
"action": "PushAlert",
"data": {
  "alertList": [
    {
      "alertDesc": "[cebdaas2b] [tr02n12] has alerts |@@|=== test.log.wf ===|@@|this is a test alert",
      "alertTime": "2020-06-08 23:44:44"
    }
  ]
}
}'
----
3. 返回值如下。
 ** 返回值为 0 ，表示配置成功。
+
[source]
----
{"task": "81889d13-2a7e-4edd-95ba-168476f7a0f4", "ret_code": 0, "action": "Boss2RecvNfAlertResponse"}
----
 ** 返回值为非 0 ，表示配置失败。
+
[source]
----
{"action": "Boss2RecvNfAlertResponse", "ret_code": 1100, "message": "no available alert to process"}
----