---
title: "Uninstall KubeSphere Enterprise Only"
keywords: "Kubernetes, KubeSphere Enterprise, Uninstall KubeSphere Enterprise Only"
description: "This section explains how to uninstall KubeSphere Enterprise. The Kubernetes running in the current cluster will not be uninstalled."
weight: 01
---


This section explains how to uninstall {ks_product-en}. The Kubernetes running in the current cluster will not be uninstalled.

// Warning
include::../../../../_ks_components-en/admonitions/warning.adoc[]

* Although Kubernetes will not be uninstalled, the uninstallation may still cause service interruption if the business running in the current cluster relies on the functionalities provided by KubeSphere.

* The uninstallation is irreversible. Please proceed with caution.


include::../../../../_ks_components-en/admonitions/admonEnd.adoc[]


== Prerequisites

include::../../../_custom-en/installationAndUpgrade/installationAndUpgrade-prer-backUpData.adoc[]

== Uninstall Extensions

. Log in to any cluster node and run the following command to view all installed extensions in the cluster.
+
[,bash]
----
kubectl get installplan
----

. Uninstall specific extensions or all extensions.

* Uninstall specific extensions.
+
--
[,bash]
----
kubectl delete installplan {InstallPlan Name}
----
[.admon.note,cols="a"]
|===
|Note

|
You can get the `InstallPlan Name` of the extension according to the command from the first step.
|===

If the following information is displayed, it indicates that the uninstallation of the extension is successful.

[,bash]
----
installplan.kubesphere.io "{InstallPlan Name}" deleted
----
--

* Uninstall all extensions.
+
--
[,bash]
----
kubectl delete installplan --all
----

The output should be as follows:

[,bash]
----
installplan.kubesphere.io "devops" deleted
installplan.kubesphere.io "dmp" deleted
installplan.kubesphere.io "gatekeeper" deleted
installplan.kubesphere.io "gateway" deleted
installplan.kubesphere.io "kubeedge" deleted
installplan.kubesphere.io "kubefed" deleted
installplan.kubesphere.io "metrics-server" deleted
installplan.kubesphere.io "network" deleted
installplan.kubesphere.io "openpitrix" deleted
installplan.kubesphere.io "opensearch" deleted
installplan.kubesphere.io "springcloud" deleted
installplan.kubesphere.io "storage-utils" deleted
installplan.kubesphere.io "tower" deleted
installplan.kubesphere.io "vector" deleted
installplan.kubesphere.io "whizard-alerting" deleted
installplan.kubesphere.io "whizard-auditing" deleted
installplan.kubesphere.io "whizard-events" deleted
installplan.kubesphere.io "whizard-logging" deleted
installplan.kubesphere.io "whizard-monitoring" deleted
installplan.kubesphere.io "whizard-notification" deleted
installplan.kubesphere.io "whizard-telemetry" deleted
installplan.kubesphere.io "whizard-telemetry-ruler" deleted
----

Run the following command again. If it outputs "No resources found", it means that all extensions have been uninstalled.

[,bash]
----
kubectl get installplan
----
--


== Uninstall ks-core

Before uninstalling ks-core, make sure that all extensions in the cluster have been uninstalled, that is, executing the `kubectl get installplan` command shows "No resources found".

. Run the following command to uninstall ks-core.
+
[,bash]
----
helm del -n kubesphere-system ks-core
----

. Run the following command. If the output is empty (as shown below), it means that {ks_product-en} has been successfully uninstalled.
+
--
[,bash]
----
root@xxx:~# helm list -n kubesphere-system
NAME    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART           APP VERSION
----
--