---
title: 查询IAM用户（DescribeIAMUsers）
weight: 7
---

== 基本信息

=== Path
/iaas

=== Method
GET

== 请求参数
[cols="1,1,1,2", options="header"]
|===
| 参数名 | 类型 | 是否必须 | 描述

| limit
| Integer
| false
| 偏移量

| offset
| Integer
| false
| 起始坐标

| owner
| String
| false
| 所有者

| path
| String
| false
| 路径

| reverse
| Integer
| false
| 是否降序查询

| root_user
| String
| false
| 根账号ID

| search_word
| String
| false
| 搜索关键字

| sort_key
| String
| false
| 排序使用的列

| users
| Array
| false
| IAM用户ID列表
|===

== 返回数据
此接口除以下返回参数外，还包含公共响应头。关于公共响应头的更多信息，请参见link:../../../../overview/#_api_返回结构[前文内容]。
[cols="1,1,1,2", options="header"]
|===
| 参数名 | 类型 | 是否必须 | 描述

| iam_users
| Object
| false
| IAM用户详情集合

| iam_users.change_passwd_first_login
| Integer
| false
| 第一次登录是否需要修改密码

| iam_users.console_access
| Integer
| false
| 允许控制台访问

| iam_users.console_id
| String
| false
| 控制台ID

| iam_users.full_user_name
| String
| false
| IAM用户名称全拼

| iam_users.owner
| String
| false
| 所有者

| iam_users.passwd
| String
| false
| 登录密码

| iam_users.passwd_status_time
| String
| false
| 最后一次密码修改时间

| iam_users.path
| String
| false
| 路径

| iam_users.programmatic_access
| String
| false
| 允许编程访问

| iam_users.qrn
| String
| false
| IAM用户资源唯一标识

| iam_users.root_user_id
| String
| false
| 根用户ID

| iam_users.user_id
| String
| false
| IAM用户ID

| iam_users.user_name
| String
| false
| IAM用户名称
|===

== 请求示例
[,javascript]
----
{
  "action": "DescribeIAMUsers",
  "limit": 20,
  "offset": 0,
  "owner": "usr-ZiEgnuY1",
  "reverse": 1,
  "sort_key": "create_time"
}
----

== 返回示例
[,javascript]
----
{
  "action": "DescribeIAMUsersResponse",
  "ret_code": 0,
  "total_count": 1,
  "user_set": [
    {
      "change_passwd_first_login": 0,
      "console_access": 1,
      "console_id": "testingcloud",
      "create_time": "2023-03-02T16:11:15",
      "full_user_name": "iamtest@wangcw.onqingcloud.com",
      "last_login_time": "2023-03-02T16:11:15",
      "owner": "usr-ZiEgnuY1",
      "passwd": "$2b$12$PKslOSqYQf52K3dEfKlkkuoBXvzXHS1uC76MckCZp9PY2ZzPFJJTe",
      "passwd_status_time": "2023-03-02T16:11:15",
      "path": "/",
      "programmatic_access": 1,
      "qrn": "qrn:qingcloud:iam::usr-ZiEgnuY1:user/iamu-ssqasbx8",
      "root_user_id": "usr-ZiEgnuY1",
      "user_id": "iamu-ssqasbx8",
      "user_name": "iamtest"
    }
  ]
}
----
