---
title: "KubeSphere Cloud Native Product Family"
linkTitle: "{ks_title}"
keywords: ""
description: ""
weight: 01
logo: "{ks_logo}"
downloadUrl: "{ks_download_url}"
---

// :ks_include_id: 09d9782e732642678646eaf8fb225f73
:ks_xref_id: 9e6d2d645b654d23b0403d1d589ae37d
:ks_comp: ../../components/
:ks_title: KubeSphere Cloud Native Product Family
:ks_description:
:ks_keywords:
:ks_weight: 01


Powered by KubeSphere, QingCloud supplies a wide array of cloud native services to set up a product family. By delivering end-to-end cloud native services, KubeSphere helps enterprises migrate their business to clouds and digitalize their business.

The following figure shows the cloud native product family of KubeSphere.

image::{ks_image}{94c3927a8dcb4b00910241fb3dd021a5}[]

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Overviewlink:[id=99a3ddde0a37487a8f3ab3800ae41ca6]

On top of KubeSphere, QingCloud has built a complete set of cloud native products and services, providing end-to-end service capabilities to help enterprise customers achieve cloud native advancement and accelerate digital transformation.

The following content lists the products and services that belong to the KubeSphere cloud native product family.

* **KubeSphere (open source)**
+
--
Out-of-the-box container platform built on top of Kubernetes.
--
* **KubeSphere Enterprise**
+
--
Enterprise-grade container platform powered by the open source KubeSphere, a distribution edition for commercial use.
--
* **KubeSphere Cloud**
+
--
One-stop software as a service (SaaS) platform for Kubernetes, covering services such as KubeSphere Backup, KubeSphere Inspector, and KubeSphere Lite.
--
* **KubeSphere Virtualization (KSV)**
+
--
Lightweight VM management platform powered by KubeSphere.
--
* **OpenFunction**
+
--
Knative-based open source function as a service (FaaS) platform in an event-driven architecture. This project has been accepted to CNCF at the sandbox level.
--
* **OpenELB**
+
--
Open source distributed load balancer. This project has been accepted to CNCF at the sandbox level.
--
* **KubeEye**
+
--
Fine-grained automated inspection tool for Kubernetes clusters.
--
* **OpenPitrix**
+
--
Full lifecycle management platform for cloud-native applications.
--
* **KubeOcean**
+
--
Fast creation and management of lightweight Kubernetes clusters.
--
* **KubeKey**
+
--
Efficient and flexible deployment tool for Kubernetes clusters.
--
* **RadonDB**
+
--
Data management platform (DMP) for container databases, which supports various engines such as MySQL, PostgreSQL, ClickHouse, Redis, MongoDB, OpenSearch, and Kafka.
--
* **QingCloud Kubernetes Engine**
+
--
Low-cost and easy O&M container service, which frees you from worrying about the build and maintenance of Kubernetes clusters.
--

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Roadmaplink:[id=41160b79c08f41b4937d56c37342c8ec]

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
=== 2018link:[id=0f93765571a4417eab8acc9b6018bd02]

In April, we open sourced our KubeSphere project and wrote down the first line of the code.

In July, KubeSphere 1.0 was released.

In December, we acquired our first customer, the People's Insurance Company of China (PICC).

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
=== 2019link:[id=ca914cc6df804d6d9ce9ee85001467ee]

In April, KubeSphere 2.0 was released, with new features of multi-tenant logging, alerting, and microservice governance.

In June, we attended KubeCon in China, and three of our topics were selected.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
=== 2020link:[id=ad29a1ef1c014c6faf79ae5888f3966b]

In August, KubeSphere 3.0 was released, witnessing the opening of a hybrid cloud era. In KubeSphere 3.0, multi-cluster management is supported.

In November, the number of KubeSphere downloads worldwide exceeded 100,000, with more than 4,500 GitHub stars.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
=== 2021link:[id=cee8406c23194b0fbd0effb9c622dfb9]

In January, we partnered with Amazon Web Services (AWS), DigitalOcean and Civo Cloud.

In April, KubeSphere 3.1 was released, with new features of metering and billing, support for KubeEdge, etc.

In July, we donated Fluentbit Operator to the upstream Fluent community.

In September, KubeSphere 3.2 released, with new features of GPU management, auto scaling across clusters, and cluster gateways.

In November, our OpenELB project entered the CNCF sandbox.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
=== 2022link:[id=7af480966eea41f78c710ff3af775a0e]

In April, our OpenFunction project entered the CNCF Sandbox.

In June, KubeSphere 3.3.0 was released, with Argo CD integration and improved DevOps capabilities.

In June, we had more than 300 community contributors, with over 1,000,000 global downloads and 10,000 GitHub stars.

In November, KubeSphere Enterprise 3.3.1 was released, offering the observability center, improved cluster monitoring, tag-based cluster management, and enhanced platform security.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
=== 2023link:[id=6009b7f24b5947039700aea7fb33b2dd]

KubeSphere Enterprise 4.0 is on the way, adopting an open pluggable architecture. In this architecture, developers can build their own applications based on specific standards and then seamlessly integrate them into the KubeSphere platform.