---
title: 获取用户联系方式（DescribeNotificationItems）
weight: 3
---

== 基本信息

=== Path
/iaas

=== Method
GET

== 请求参数
[cols="1,1,1,2", options="header"]
|===
| 参数名 | 类型 | 是否必须 | 描述

| console
| String
| false
| 控制台

| limit
| Integer
| false
| 查询数量

| notification_item_type
| String
| false
| 联系方式类型

| notification_items
| Array
| false
| 联系方式id

| notification_list
| String
| false
| 通知列表id

| offset
| Integer
| false
| 查询偏移量

| owner
| String
| false
| 所属用户id

| root_user_id
| String
| false
| 根用户id
|===

== 返回数据
此接口除以下返回参数外，还包含公共响应头。关于公共响应头的更多信息，请参见link:../../../../overview/#_api_返回结构[前文内容]。
[cols="1,1,1,2", options="header"]
|===
| 参数名 | 类型 | 是否必须 | 描述

| notification_item_set
| Array
| false
| public

| notification_item_set[].content
| String
| false
| 联系方式

| notification_item_set[].create_time
| String
| false
| 创建时间

| notification_item_set[].notification_item_id
| String
| false
| 通知列表项id

| notification_item_set[].notification_item_type
| String
| false
| 联系方式类型

| notification_item_set[].remarks
| String
| false
| 备注
|===

== 请求示例
[,javascript]
----
{
  "action": "DescribeNotificationItems",
  "notification_items": [
    "ni-xxxxxxxx"
  ]
}
----

== 返回示例
[,javascript]
----
{
  "action": "DescribeNotificationItemsResponse",
  "notification_item_set": [
    {
      "console_id": "testingcloud",
      "content": "86-133****8888",
      "create_time": "2022-03-21T08:24:25Z",
      "notification_item_id": "ni-xxxxxxxx",
      "notification_item_type": "phone",
      "owner": "usr-xxxxxxxx",
      "remarks": "",
      "root_user_id": "usr-xxxxxxxx",
      "verification_code": "",
      "verify_time": "2022-03-21T08:24:25Z"
    }
  ],
  "ret_code": 0,
  "total_count": 1
}
----
