title: "首页"

markup:
  asciidocExt:
    attributes:
      toc:
      toclevels: 2
      file_output_type: html
      # 全局变量
      platform_name_cn: 云平台
      company_short_name: 青云
      brand_full_name: 青云QingCloud
      brand_name_cap: QingCloud
      brand_name_low: qingcloud
      # 产品变量
      qingstor_cap: QingStor
      qingstor_low: qingstor
      k8s_engine_fullname: 容器引擎 QKE
      k8s_engine_shortname: QKE
params:
  description: "这是文档模板中心"
  favicon: "/images/favicon.ico"
  keywords: "青云,QingCloud,云平台,云计算"
  logo: "/images/qingcloud-logo.svg"
  logoInfo: "文档模板"
  logoLink: "/"
  disableVersions: true

  # PDF 配置
  pdf:
    pdf_projectName: 产品名称
    pdf_docVersion: 01
    pdf_copyright: 版权所有 © 北京青云科技股份有限公司（内部公开）
    pdf_legalInfo: 版权所有 © 北京青云科技股份有限公司 2023。保留所有权利。
    pdf_projectVersion: v6.1
#    pdf_releaseDate: 2023-03-01
    pdf_companyFullName: 北京青云科技股份有限公司
    pdf_companyName: 青云
    pdf_companyUrl: https://www.qingcloud.com
    pdf_companyIcon: /images/pdf/qingcloud-logo-icon.png
    pdf_coverDocName: 产品名称 产品版本
    pdf_coverDocLogo: /images/pdf/qingcloud-logo-color.png
    pdf_coverDocImage: /images/pdf/cover_doc_image.svg
    toclevels: 3
    sectnumlevels: 5
