---
title: "Offline Upgrade from v4.1.x to v4.2.0"
keywords: "Kubernetes, KubeSphere Enterprise, installation, upgrade KubeSphere Enterprise"
description: "This guide describes how to upgrade KubeSphere Enterprise."
weight: 04
---

This section describes how to perform an offline upgrade from {ks_product-en} v4.1.2 to {ks_product-en} v4.2.0 without Internet access.

== Prerequisites

* Contact the KubeSphere Enterprise support team to get the KubeSphere Enterprise v4.2.0 installation package and license.

* Ensure current {ks_product-en} version is v4.1.2 or v4.1.3.
* Ensure current Kubernetes version is v1.23.x to v1.32.x.
* For extensions with special configurations, back up extension configurations by downloading files from the "Extension Config" dialog.
* {empty}
include::../../../_custom-en/installationAndUpgrade/installationAndUpgrade-prer-backUpData.adoc[]


== Attention

. If you customized the nodeShell image in v4.1.x, specify the nodeShell image in the upgrade configuration file `kse-v4.2.0-host-custom-values.yaml` as shown below:
+
--
Example configuration in v4.1.x:

[source,yaml]
----
nodeShell:
  image:
    registry: ""
    repository: kubesphereio/kubectl
    tag: "v1.27.12"
    pullPolicy: IfNotPresent
----

Configure in `kse-v4.2.0-host-custom-values.yaml` as:

[source,yaml]
----
terminal:
  kubectl:
    enabled: true
    image:
      registry: ""
      repository: kubesphereio/kubectl
      tag: "v1.33.1"
      pullPolicy: IfNotPresent
  node:
    enabled: true
    image:
      registry: ""
      repository: kubesphereio/kubectl
      tag: "v1.33.1"
      pullPolicy: IfNotPresent
  pod:
    enabled: true
    uploadFileLimit: "100Mi"
    uploadFileEnabled: true
    downloadFileEnabled: true
----
--

. Starting from v4.1.3, cluster role and host cluster name configurations in ks-core chart have changed. When upgrading from v4.1.2, configure as shown below (v4.1.3 unaffected):
+
[source,yaml]
----
multicluster:
  # Cluster role name
  role: ""
  # Host cluster name (priority: direct specification > reading from kubesphere-config > default name host)
  hostClusterName: ""
----

. Starting from v4.1.3, the following parameter is deprecated. Remove it or set to `false` in `kse-v4.2.0-host-custom-values.yaml`:
+
[source,yaml]
----
upgrade:
  enabled: false
----


== Preparation

=== 1. Unpack the Installation Package

. Transfer the {ks_product-en} installation package to the cluster node to be upgraded and log in to that node.

. Run the following command to unpack the v4.2.0 installation package (replace <package name> with the actual package name).
+
--
[source,bash]
----
tar -zxvf <package name>
----

[.admon.attention,cols="a"]
|===
|Attention

|Ensure that the directory has sufficient available space, preferably greater than 100 GB.
|===
--

. Enter the directory generated after unpacking the installation package.
+
--
[source,bash]
----
cd <directory>
----
--

=== 2. Push Images

. In the v4.2.0 directory, edit the **config-sample.yaml** file created during the installation and modify the **registry** section within it.
+
--
[,yaml]
----
    privateRegistry: "dockerhub.kubekey.local/kse" # Replace with the actual image registry address
        auths:
          "dockerhub.kubekey.local":  # Replace with the actual image registry address
              username: admin           # Replace with the username of the image registry
              password: Harbor12345     # Replace with the password of the image registry
              skipTLSVerify: true
              plainHTTP: true   # Set this parameter to true if the image registry uses http
----
--

. Push the images to the image registry.
+
[source,bash]
----
./kk artifact images push -f config-sample.yaml -a kubekey-artifact.tar.gz
----

== Upgrade {ks_product-en}

{ks_product-en} v4.1 and later versions use the helm chart method to upgrade ks-core.

=== Upgrade Host Cluster

. Verify the current cluster is the target host cluster for upgrade:
+
[source,bash]
----
kubectl get node -o wide
----

. {ks_product-en} v4.1.3 removed `kse-extensions-publish` and integrated it into the ks-core chart. For v4.1.2 to v4.2.0 upgrades, you should patch extension resources created by {ks_product-en} previous versions:
+
[.admon.attention,cols="a"]
|===
|Note

|This step only applies to v4.1.2 → v4.2.0 upgrades. Skip for v4.1.3 → v4.2.0.
|===
+
[source,bash]
----
# Use the extension-resources-patch.sh script located in the tools directory of the installation package
bash tools/extension-resources-patch.sh
----

. Check the current cluster's ks-core configuration.
+
--
[source,bash]
----
helm get value -n kubesphere-system ks-core
----
--

. Create the upgrade configuration file with the following content:
+
--
If there are other parameters besides the image registry, image version, cloud, and upgrade in the previous step, please add them to the following configuration file.

[source,bash]
----
cat <<EOF > kse-v4.2.0-host-custom-values.yaml

# Specify image registry for ks-core and extensions
# Modify according to actual environment
global:
  imageRegistry: dockerhub.kubekey.local/kse
extension:
  imageRegistry: dockerhub.kubekey.local/kse

# Cluster role parameter changed from role to multicluster.role
multicluster:
  role: host

# Enable HA for ks-core components (ks-apiserver, ks-controller-manager, ks-console)
# Configure according to cluster status
ha:
  enabled: false

# Enable Redis HA (required for ks-apiserver HA)
# If set to false, single-replica Redis will be deployed in kubesphere-system
redisHA:
  enabled: false
EOF
----
--

. Run the following command to start the upgrade.
+
--
[source,bash]
----
helm upgrade --install ks-core charts/ks-core -n kubesphere-system -f kse-v4.2.0-host-custom-values.yaml --wait --debug
----

[.admon.attention,cols="a"]
|===
|Attention

|
Replace `charts/ks-core` with the actual path of the `ks-core` chart in the current environment.
|===
--

. Verify the host cluster upgrade status.
+
--
Run the following command. The pods should be in Running state as shown below.

[source,bash]
----
root@xxx:~# kubectl get pod -n kubesphere-system
NAME                                         READY   STATUS      RESTARTS   AGE
extensions-museum-85f846dbbd-6xtst           1/1     Running     0          16h
helm-install-ks-console-embed-tnwmf7-wcfjf   0/1     Completed   0          16h
ks-apiserver-7f875b8654-zvhrd                1/1     Running     0          16h
ks-console-997fc9658-dnrqr                   1/1     Running     0          16h
ks-console-embed-775f757548-9vd2s            1/1     Running     0          16h
ks-controller-manager-5f69675d48-qnxv7       1/1     Running     0          16h
----
--

. Access the {ks_product-en} v4.2.0 web console using the original IP address, administrator username and password.

. Check whether all functions and data in the host cluster are working properly.


=== Upgrade Member Cluster

The member cluster upgrade process is similar to the host cluster, with special attention to member-specific parameters.

. Verify the current member cluster is the target for upgrade:
+
[source,bash]
----
kubectl get node -o wide
----

. Check member cluster's ks-core configuration:
+
--
[source,bash]
----
helm get values -n kubesphere-system ks-core
----
--

. Get the member cluster's jwtSecret:
+
[source,bash]
----
kubectl -n kubesphere-system get cm kubesphere-config -o yaml | grep -v "apiVersion" | grep jwtSecret
----

. Create the upgrade configuration file with the following content:
+
====
If the previous step shows parameters beyond image registry, image version, cloud and upgrade, include them in this configuration file.

[source,bash]
----
cat <<EOF > kse-v4.2.0-member-custom-values.yaml

# Specify image registry for ks-core
# Modify according to actual environment
global:
  imageRegistry: dockerhub.kubekey.local/kse

# Replace with member cluster's jwtSecret value
authentication:
  issuer:
    jwtSecret: <REPLACE_ME>

# Cluster role parameter changed from role to multicluster.role
multicluster:
  role: member
EOF
----
====


. Run the upgrade command:
+
--
[source,bash]
----
helm upgrade --install ks-core charts/ks-core -n kubesphere-system -f kse-v4.2.0-member-custom-values.yaml --wait --debug
----

[.admon.attention,cols="a"]
|===
|Attention

|
Replace `charts/ks-core` with the actual path of the `ks-core` chart in the current environment.
|===
--

. Verify the member cluster upgrade status.
+
--
Run the following command; the `ks-agent` pod should be in the running state as shown below.

[source,bash]
----
root@xxx:~# kubectl get pod -n kubesphere-system
NAME                          READY   STATUS      RESTARTS        AGE
ks-agent-5dc5b57977-4x6mf     2/2     Running     0               59m
----
--

. If you added custom configurations (e.g., `--set a=b`) in the above upgrade command, you need to add the custom configurations for the member cluster in the web console.
+
--
Method: On the **Cluster Management** page, click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the member cluster you want to edit, and then select **Edit Configuration** from the dropdown list. In the pop-up window, enter `a: b`.

[.admon.note,cols="a"]
|===
|Note

|If you did not include custom configurations in the upgrade command, you do not need to add cluster configurations in the web console.
|===
--

=== Upgrade Extensions

include::../../../_custom-en/installationAndUpgrade/installationAndUpgrade-oper-updateExtensions.adoc[]

include::../../../_custom-en/installationAndUpgrade/installationAndUpgrade-oper-updateExtensionList_v420.adoc[]