---
title: 性能指标
description: 
weight: 1
---



存储性能有三个指标，如：IOPS、吞吐量以及访问时延。本章节将对这三个概念进行解释与说明，并对三者之间的关系进行说明。

== IOPS

IOPS：I/Os Per Second，即每秒输入输出次数，是指单位时间内设备能处理的 I/O 请求数量，一般以每秒处理的 I/O 请求数量为单位，是衡量磁盘性能的主要指标之一。

常用的 IOPS 指标包括顺序操作和随机操作，如下所示。

[cols="1,3", options="header"]
|===
| 指标 | 描述

|总 IOPS
|每秒执行的 I/O 操作总次数

|随机读 IOPS
|每秒执行的随机读 I/O 操作的平均次数

|随机写 IOPS
|每秒执行的随机写 I/O 操作的平均次数

|顺序读 IOPS
|每秒执行的顺序读 I/O 操作的平均次数

|顺序写 IOPS
|每秒执行的顺序写 I/O 操作的平均次数

|===


== 吞吐量

吞吐量 Throughput，是指单位时间内可以成功传输的数据数量，单位为 MB/s。如果知道每个 I/O 的平均大小，以及每秒钟的 I/O 数量，那么就可以算出这些 I/O 总共产生了多大的数据量，即带宽：Bandwidth。


因此，IOPS * I/O size = Bandwidth。

== 访问时延

访问时延是处理一个 I/O 需要的时间，单位为 s、ms 或者 μs。过高的时延会导致应用性能下降或报错。

== 总结

* 随机读写频繁的应用，如小文件存储，OLTP 数据库、邮件服务器等，关注的是随机读写性能，IOPS 就是关键衡量指标。

* 顺序读写频繁的应用，传输大量连续数据，如电视台的视频编辑，视频点播 VOD，关注的是连续读写性能。数据吞吐量是关键衡量指标。


** 读取 10000 个 1KB 文件，用时 10秒，则：Throught = 1MB/s，IOPS = 1000，此时追求的是高 IOPS。
** 读取 1 个 10MB 文件，用时 0.2秒，则：Throught = 50MB/s，IOPS = 5，此时追求的是高吞吐量。

* 在测试过程中，IOPS 数值会受到很多因素的影响，包括 I/O 负载特征，如：读写比例，顺序和随机，工作线程数，队列深度，数据记录大小等，以及硬件配置，如：系统配置、操作系统、磁盘驱动等等。因此对比 IOPS 时，必须在同样的测试基准下进行，即便如此也会产生一定的随机不确定性。


