---
title: "FAQ"
description: 介绍 CDN 服务的常见问题及解决办法。
keywords: 网络, CDN, 常见问题
draft: false
weight: 81
---

== 创建 CDN 服务后，用户在 DNS 服务器设置 CNAME 不生效

确认一下客户是否在 DNS 服务器配置该域名的其他记录，如 `MX` 等。部分 DNS 厂商不支持 CNAME 和其他记录共存，这种情况建议向 DNS 厂商反馈。


== 创建 CDN 时提示余额不足

创建 CDN 服务时，账户需要有 10 元以上的余额。如果余额不足，请到费用中心充值。



== 创建 CDN 服务是否需要备案

创建 CDN 服务需要备案，但是可以不用在青云进行备案，只要域名已经备案即可。

== CDN 节点类型无法修改

建议用户可以先删除原 CDN 服务，等一个小时后，再创建 CDN 服务，并重新选择节点类型。

== 使用 CDN 后无法访问

可参考如下流程进行操作。

. 查看创建的域名记录，dig 该域名，是否 CNAME 到域名后缀 `qingcache.com`。
. 查看该域名的源站，确定源站访问是否正常。
. 若用户配置的是域名回源，指定源站访问时，确定 `host` 填回源域名是否可以正常访问。若能正常访问，则建议修改 CDN 的 `Origin Host` 为回源域名。

== 没有域名配额

一般是用户没有实名认证，建议用户先进行实名认证。

== 无法删除域名记录

确认域名记录是否绑定证书，如果绑定证书后，需要先解除证书绑定，才能删除域名记录。

== 多个帐号如何添加相同的主域名

暂时不支持多个帐号添加相同的主域名。

== 创建 CDN 服务后为什么没有监控数据

确认域名记录是否 CNAME 到域名后缀 `qingcache.com`，且已经被访问。一般需要等十分钟后才有监控数据。

== 创建 CDN 需要多久生效

一般十分钟以内。

== 使用 CDN 后如何获取用户真实 IP

用户可以尝试通过获取 header 中的 `X-Forwarded-For` 和 `cdn-src-ip` 来获取真实 IP。


== CDN 创建完成后该如何使用

去您域名的 DNS 服务商将加速域名做 CNAME 解析。将加速域名 CNAME 到青云 CDN 详情页提供的 CNAME 地址上即可完成。

== 开启 HTTPS 后如何让通过 HTTP 访问的用户跳转到 HTTPS

在创建域名记录时，选择 `强制 HTTPS 服务`。

== 如果改变协议类型，会如何计费

青云的计费会在每天凌晨进行扣费，按照 0 时的协议类型，扣去昨天的消费。比如在 23:50，协议类型从 `HTTP` 切换到了 `HTTPS`，则凌晨的扣费也会按照 HTTPS 进行计费。

== 为什么我无法改变服务/协议类型

因为协议或者服务类型的切换，会设涉及到大量的资源调度，所以青云会限制该操作的频率，目前在 24 小时内只允许切换一次。

== 如何理解加速域名与回源域名的关系

加速域名是您最终要直接暴露给用户访问的域名，回源域名仅用作 CDN 解析到服务器 IP。如果使用 Nginx 作为 WEB 服务器，则 `server_name` 应该是 `加速域名` 而不是 `回源域名`。

== 域名回源与 IP 回源的区别是什么

域名回源通过解析出域名背后的 IP 然后通过 IP 进行回源，您可以在 DNS 处任意更改域名的 A 记录来切换源站，而 IP 回源需要在青云切换 IP 源站。




== 暂不支持自助配置，需要提工单进行人工配置的功能

* 设置回源鉴权策略
* 设置跨域规则
* 设置大文件切片
