---
title: "CLI 使用说明"
weight: 9
---

qingcloud-cli 是管理{platform_name_cn} 资源的命令行接口 (Command Line Interface)， 可以通过它对资源进行查看、创建和操作。目前支持 Linux, Mac 及 Windows。

include::../../../../_components/note.adoc[]
* qingcloud-cli 的使用受 API 访问配额的限制，具体请查看 link:../precondition/[前置条件] 中的 “API 请求配额限制”
* 您需要满足前提条件：系统已经安装 python 和 pip。
* 目前只支持虚拟资源类的 API 使用 CLI。
include::../../../../_components/table_footer.adoc[]

== 安装 CLI

可使用 pip 安装：

[,shell]
----
$ pip install qingcloud-cli
----

$ sudo pip install qingcloud-cli

[,shell]
----
$ sudo pip install qingcloud-sdk
----

如果你已安装 qingcloud-cli 并需要更新到最新版本，则可以：

[,shell]
----
$ pip install --upgrade qingcloud-cli
----

== 命令自动补全

qingcloud-cli 包含命令自动补全功能 (目前不支持 Windows 系统)。

如果补全功能没有自动生效，请手动激活一下：

[,shell]
----
$ source ~/.bashrc
----

如果还不行，则输入 complete 命令：

[,shell]
----
$ complete -C qingcloud_completer qingcloud
----

并可将这条命令加到你的启动脚本中 (如 ~/.bash_profile) 方便以后使用。

== 修改配置

使用 qingcloud-cli 必需一个配置文件，配置你自己的 qy_access_key_id、qy_secret_access_key、zone、API 服务器、端口、协议。比如：

[,shell]
----
qy_access_key_id: 'QINGCLOUDACCESSKEYID'
qy_secret_access_key: 'QINGCLOUDSECRETACCESSKEYEXAMPLE'
zone: 'test'
host: 'api.domain.com'
port: 80
protocol: http
----

配置文件默认放在 ~/.qingcloud/config.yaml ，也可在每次执行命令时以参数 -f /path/to/config 方式来指定，例如：

[,shell]
----
qingcloud iaas describe-instances -f '/root/qingcloud_config.yaml'
----

如果只是输入 qingcloud 并回车，会列出所有支持的命令， 每个命令都有帮助文档，可以通过 -h 参数打印出来，如：

[,shell]
----
qingcloud iaas run-instances -h
----

== 输入参数

qingcloud-cli 的参数只有 int 和 string 类型。如果参数支持传递列表，则多个值之间以 英文逗号 ”,” 分隔。如：

[,shell]
----
qingcloud iaas describe-keypairs -k 'kp-bn2n77ow,kp-b2ivaf15' -L 2
----

有时参数需要是 JSON 格式的字符串，如：

[,shell]
----
qingcloud iaas add-router-statics -r rtr-ba2nbge6 -s '[{"static_type":1,"val1":"80","val2":"192.168.99.2","val3":"8000"}]'
----

== 命令输出

Command 的返回结果为 JSON 结构。例如 describe-keypair 的返回结果：

[,json]
----
{
  "action":"DescribeKeyPairsResponse",
  "total_count":2,
  "keypair_set":[
    {
      "description":null,
      "encrypt_method":"ssh-rsa",
      "keypair_name":"kp 1",
      "instance_ids":[
        "i-ogbndull"
      ],
      "create_time":"2013-08-30T05:13:50Z",
      "keypair_id":"kp-bn2n77ow",
      "pub_key":"AAAAB3..."
    },
    {
      "description":null,
      "encrypt_method":"ssh-rsa",
      "keypair_name":"kp 2",
      "create_time":"2013-08-31T05:13:50Z",
      "keypair_id":"kp-b2ivaf15",
      "pub_key":"AAAAB3..."
    }
  ],
  "ret_code":0
}
----