---
title: "Edit a VM template"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, VMs, templates, edit"
description: "Describes how to edit a VM template in the {ks_product} web console."
weight: 04
logo: ""
downloadUrl: ""
---

// :ks_include_id: 20178533534d4aff99e5104d6836ab98
:ks_xref_id: 144a179049ef4d1d842df2ff917d1f63
:ks_comp: ../../../../components/
:ks_title: Edit a VM template
:ks_description: Describes how to edit a VM template in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, VMs, templates, edit
:ks_weight: 04
:ks_logo:
:ks_download_url:


This topic describes how to edit a VM template in the {ks_product_abbr_full} web console. The edit operation allows you to modify the name, description, and sharing feature of a VM template. If you want to resize resources for a Vm template, see link:../07-resize-vm-template-resources/[Resize VM template resources].

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=21e057850a204e43a9c8fc8d80418374]

include::../../../../_custom-en/vms/vm-template-manage-prerequisites.adoc[]

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Edit from the list of VM templateslink:[id=0e7c253dd21242aa947f6c09f5c1f43c]

include::../../../../_custom-en/vms/vm-template-steps.adoc[]

. Find the VM template that you want to edit, click image:/images/ksv/en/icons/more.svg[operation-menu,13] on the right side, and then select **Edit** from the drop-down list.
. In the dialog box that appears, modify the name, description, and sharing feature of the VM template, and click **OK**.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Edit from the VM template details pagelink:[id=f4ad9649a6ce49f6a00f11eafdcaace5]

include::../../../../_custom-en/vms/vm-template-steps.adoc[]

. On the **Templates** page, click the name of a VM template to view its details.
. On the left side of the details page, click image:/images/ksv/en/icons/more.svg[operation-menu,13] and select **Edit** from the drop-down list.
. In the dialog box that appears, modify the name, description, and sharing feature of the VM template, and click **OK**.