---
title: 基本概念
weight: 20
---

使用平台前，请先了解如下基本概念。

== 虚拟化平台

虚拟化平台是为云桌面提供基础设施资源的 IaaS 平台，是云桌面运行的基础环境。

== 用户

用户是云桌面使用者的身份标识，可通过用户帐号登录终端并使用云桌面。用户的设备操作权限通过策略控制。从用户类型分，用户可分为本地用户和域用户。

* 通过管理平台创建和通过用户模板导入的用户为本地用户。本地用户的认证及信息管理均在管理平台进行。
* 通过 AD/LDAP 帐户导入的用户为域用户。域用户本身的信息及域用户的认证在域服务器端管理，域用户对云桌面资源的使用权限在管理平台进行。

== 用户组

用户组是多个用户的集合，用户组支持分级管理。用户组可以与桌面池绑定，绑定后，用户组下的直属用户拥有桌面池中云桌面的使用权。

用户组包括**根用户组**、**默认用户组**和**自定义用户组**：

* **根用户组**：用户和用户组的根路径，在管理平台中显示为 ``root``。
* **默认用户组**：根用户组下的默认用户组，路径为 ``root/default``。
* **自定义用户组**：管理员根据企业的组织架构在管理平台中创建的用户组。

== 云桌面

云桌面是指运行在物理主机中的虚拟桌面计算机系统，具备完整硬件系统功能，可运行 Windows、Linux 等操作系统。用户可通过终端登录云桌面并开展业务。

== 桌面池

桌面池是一组分配给用户组的云桌面资源的集合，用户组中的直属用户可以从桌面池中申请桌面并使用。

桌面池分为**专属桌面池**和**还原桌面池**。

* **专属桌面池**中的桌面与用户绑定后，用户将独享该桌面的所有资源，直至桌面与用户解绑。用户可在桌面中安装应用程序并进行个性化设置，桌面关机或者重启后系统不还原。

* **还原桌面池**中的桌面开机或者硬重启后，系统盘将被还原至初始状态，数据盘中的数据不会还原。
+
还原模式下，可设置桌面池的共享模式：

** 开启共享模式后，还原桌面与用户非持久关联，用户通过终端登录时随机占用池中的桌面，用户退出登录后，桌面与用户解除关联，并且该桌面被删除。
** 关闭共享模式后，还原桌面与用户持久关联，用户退出登录后，桌面与用户依旧关联。

== 区域

区域是一组虚拟化平台、云桌面、用户等资源的组合，是组合内资源管理的边界。

每个区域都有对应的区域管理员，超级管理员默认为所有区域的区域管理员，可自定义区域的其他区域管理员。

== 角色

角色是一组操作权限的组合，当管理员与角色绑定后，便拥有了该角色中包含的权限。

系统默认提供如下六个角色：

* **高级管理员角色**：日志管理所有权限，虚拟化平台管理所有权限，桌面池管理所有权限，桌面管理所有权限，用户组管理所有权限，终端组管理所有权限，终端管理所有权限，配置管理所有（除了更新密码策略）权限，系统管理所有（除了备份恢复管理，系统升级管理）权限。
* **普通管理员角色**：桌面池管理所有权限，桌面管理所有权限，用户组管理所有权限，用户管理所有权限。终端管理所有权限，同步 AD/LDAP 权限，工单管理权限。
* **一线管理员角色**：桌面开机/关机、桌面重启、远程协助、暂停/恢复桌面、终端开机/关机、终端重启和禁用设备。
* **系统管理员角色**：用户组管理、用户管理、配置管理和系统管理。
* **安全管理员角色**：查看日志，更新桌面池策略、桌面策略、用户组策略、用户策略和终端组策略。
* **审计管理员角色**：能够对系统管理员和安全管理员的操作日志进行查看并导出的管理员。

== 管理员

管理员是 {product_name}使用者的标识，可通过管理员帐号登录并使用系统。管理员可分为**超级管理员**和**区域管理员**。

* **超级管理员**：拥有系统所有的操作权限，并且为所有区域的区域管理员。
* **区域管理员**：可通过绑定角色自定义管理权限并绑定区域。作为区域管理员，管理员只能与一个角色绑定，可绑定并管理多个区域。区域管理员不可进行管理员管理。

== 资源

资源是指 {product_name}对桌面、桌面池、用户、用户组等的统称，例如：专属桌面池也可称为专属桌面池资源。

== 策略

策略定义了用户或者用户组的设备访问操作权限和桌面访问策略及协议传输参数等，可分为桌面策略、终端策略和用户策略。

* 桌面策略
+
桌面策略定义了桌面的开关机计划、屏幕水印、USB 设备、数据访问等策略。桌面策略有三种，分别为全局桌面策略，桌面池私有策略和桌面私有策略。
全局策略可对所有桌面池和桌面生效，桌面池策略可对池内所有桌面生效，桌面也可定义私有桌面策略。

* 终端策略
+
终端策略定义了终端的分辨率、登录壁纸和终端开机动画等。终端策略有两种，分别为全局终端策略和终端组策略。
全局策略可对所有终端生效，终端组策略可对终端组内终端生效。

* 用户策略
+
用户策略定义了用户的自动注销策略和自动退出桌面连接策略。用户组策略可分为全局用户策略、用户组策略和用户私有策略。
+
全局策略可对所有用户组和用户生效，用户组策略可对用户组内所有用户生效，用户也可以自定义私有策略。

== 终端

终端是指能连接到 {product_name}中，使用管理员创建的云桌面的终端设备。云计算中，业务的使用和展现通过终端实现。

终端根据架构和展现形式主要有如下两种类型：

[cols='1a,5a'] 
|===
| 类型 | 描述 

| 瘦客户端
| 瘦客户端 TC（ThinClient）是一种终端设备，用于将用户接入数据中心，并处理虚拟桌面协议。它通过网络直接使用 {product_name}中的云桌面资源，无硬盘、光驱。TC 体积小巧、耗电低、使用寿命长。

瘦客户端通常需要安装基于 Linux 的操作系统，因此也称为 Linux 客户端。

瘦终端根据架构分为以下两种：

* ARM 终端
+
ARM 终端采用嵌入式芯片，搭载 Linux 内核、体积小、功耗低，如 A2000、A2001 和 A3000、A3001 型号的终端。

* X86 终端
+
X86 终端自身有 CPU、内存、硬盘等，可安装独立操作系统，如 X2000 型号的终端。

| 软终端
| 软客户端（Software Client）是指按照在 PC 或移动设备上（包括便携笔记本、上网本、平板电脑、智能手机等）的软件客户端，需要单独安装。用户通过软终端使用  
 {product_name}中的云桌面资源。

根据安装平台的不同，软终端分为以下五种：

* WinClient
+
WinClient 是指在 Windows 操作平台中运行的软终端，如 S1000-W 型号的终端。

* MacClient
+
MacClient 是指在 Mac OS 中运行的软终端，如 S1000-M 型号的终端。

* LinuxClient
+
LinuxClient 是指在客户Linux操作系统中安装对应的客户端，如 S1000-L 型号的终端。目前支持 Ubuntu和 Debian。其他操作系统可以进行定制化。

* Android Client
+
Android Client 是指在 Android 系统的移动设备上安装的 Client APP，如 S1000-A 型号的终端。

* IOS Client
+
IOS Client 是指在 IOS 系统的移动设备上安装的 Client APP，如 S1000-I 型号的终端。
|===

