---
title: "应用场景"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, 应用, 场景, 介绍"
description: "介绍{ks_product_both}的应用场景。"
weight: 02
logo: "{ks_logo}"
downloadUrl: "{ks_download_url}"
---

// :ks_include_id: 0a5788f952dd48618d3736bc3cd0edaf
:ks_xref_id: f8d43f8a947e405980760ba2222611d9
:ks_comp: ../../components/
:ks_title: 应用场景
:ks_description: 介绍{ks_product_both}的应用场景。
:ks_keywords: {ks_product_full}, {ks_product}, 应用, 场景, 介绍
:ks_weight: 02


{ks_product_abbr_full_right}具有广泛的应用场景。作为企业级虚拟化平台，{ks_product_right}可支撑个人用户、中小团队和大型企业的多种虚拟化业务需求，为边缘计算、虚拟化资源池、容器化应用混合部署、国产化替代提供解决方案。

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== 边缘计算link:[id=480e42018716457b9dff42f571a35482]

对于边缘站点多、资金有限的企业虚拟化需求，{ks_product_right}提供轻量级虚拟化平台，支持单节点 4 核 8 GB 的最小化配置，极大地为您降低了业务基础设施部署、管理和运维成本。

此外，{ks_product_right}提供良好的兼容性，支持 PC、工控机、服务器利旧。对业务分布广，强依赖网络的业务需求，{ks_product_right}提供多节点部署安装，实现就近计算、实时响应，可广泛应用于⼯业物联⽹、智慧城市、智慧交通等⾏业数据采集、实时数据分析应⽤场景。

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== 虚拟化资源池link:[id=d6821f052382414a8a246f3464e4eea6]

作为自主研发云原⽣虚拟化平台，{ks_product_right}完美适配国产芯⽚和操作系统，支持对接第三方存储，大幅提高资源利用率，可广泛应用于国产化替代、虚拟化建设、测试环境、实训课堂等场景。

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== 容器虚拟机混合部署link:[id=5711fbc6ffe64d1d9cd7d894f2dfac68]

{ks_product_right}是基于 Kubernetes 构建的超融合基础架构软件，支持虚拟机和容器逻辑并存。通过 KubeSphere 和{ks_product_both}混合部署，您可以在前端统一资源申请界面上申请虚拟机资源或容器资源，从而简化基础设施和提高运维效率。

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== 国产化替代link:[id=7ed4dc8494464d7ca8154ce5b363d94a]

基于超融合基础架构的优势，{ks_product_right}实现无缝兼容异构芯片，为您提供软硬解耦的中立虚拟化解决方案。目前，{ks_product_right}兼容主流的 x86 和 ARM 架构，配备国产云管理平台，可用于支撑生产环境的虚拟化业务需求。
