---
title: "Remove Cluster Nodes"
keywords: "Kubernetes, KubeSphere Enterprise, delete cluster node"
description: "Introduce how to delete KubeSphere Enterprise cluster nodes."
weight: 02
---


This section describes how to delete KubeSphere Enterprise cluster nodes.

The open-source tool KubeKey will be used during the process. For more information about KubeKey, please visit link:https://github.com/kubesphere/kubekey[GitHub KubeKey repository].

// Note
include::../../../../_ks_components-en/admonitions/note.adoc[]

The node deletion method described in this section is only applicable to Kubernetes installed through KubeKey. If your Kubernetes is not installed via KubeKey, please refer to link:https://kubernetes.io/zh/docs/concepts/architecture/nodes/[Kubernetes documentation] to delete nodes.

include::../../../../_ks_components-en/admonitions/admonEnd.adoc[]


include::../../../../_ks_components-en/admonitions/warning.adoc[]

* Do not delete control plane nodes, otherwise the cluster may encounter errors.

* Please ensure that after node deletion, the remaining resources in the cluster are still sufficient to run existing services. Otherwise, service interruption may occur after the node is deleted.

include::../../../../_ks_components-en/admonitions/admonEnd.adoc[]


== Prerequisites

* Contact the KubeSphere Enterprise support team to obtain the KubeSphere Enterprise v4.2.0 installation package.

* You should get the installation configuration file **config-sample.yaml** and transfer it to the cluster node where you will perform this action. For more information, refer to link:../../02-install-kubesphere/[Install {ks_product-en}].
+
include::../../../../_ks_components-en/admonitions/warning.adoc[]

If you are unable to get the installation configuration file **config-sample.yaml**, you need to refer to link:../../02-install-kubesphere/[Install {ks_product-en}] to recreate the **config-sample.yaml** file. When recreating the file, make sure that the cluster information in the file matches the current state of the cluster. Otherwise, the uninstallation process may encounter errors.

include::../../../../_ks_components-en/admonitions/admonEnd.adoc[]



== Steps

// ifeval::["{file_output_type}" == "html"]
// include::../../../_custom-en/installationAndUpgrade/installationAndUpgrade-oper-downloadKubekey.adoc[]
// endif::[]

// ifeval::["{file_output_type}" == "pdf"]
include::../../../_custom-en/installationAndUpgrade/installationAndUpgrade-oper-decompressInstallationPackage_new.adoc[]
// endif::[]

. Run the following command to get the name of the node that needs to be deleted:
+
--
// Bash
include::../../../../_ks_components-en/code/bash.adoc[]

kubectl get node

include::../../../../_ks_components-en/code/codeEnd.adoc[]
--

. Run the following command to evict the pods running on the node that needs to be deleted to other nodes (replace <node name> with the name of the node that needs to be deleted):
+
--
// Bash
include::../../../../_ks_components-en/code/bash.adoc[]

kubectl drain <node name>

include::../../../../_ks_components-en/code/codeEnd.adoc[]
--

+

include::../../../_custom-en/installationAndUpgrade/installationAndUpgrade-oper-transferConfig.adoc[]

+

. Run the following command to start deleting nodes:
+
--
// Bash
include::../../../../_ks_components-en/code/bash.adoc[]

 ./kk delete node <node name> -f config-sample.yaml

include::../../../../_ks_components-en/code/codeEnd.adoc[]
--

. Run the following command to view the current cluster nodes:
+
--
// Bash
include::../../../../_ks_components-en/code/bash.adoc[]

kubectl get node

include::../../../../_ks_components-en/code/codeEnd.adoc[]

If the deleted node is not displayed, it means the node is deleted successfully.
--