title: EdgeWize 边缘计算平台 # 此为学习路径上面的 title
markup:
  asciidocExt:
    attributes:
      toc: null
      toclevels: 2
      file_output_type: html
      relfilesuffix: /
      ks_product:  KubeSphere 企业版
      ks_product_left:  KubeSphere 企业版
      ks_product_right: KubeSphere 企业版
      ks_product_both:  KubeSphere 企业版

params:
  disableVersions: false # 此为是否显示版本索引
  description: 这是 EdgeWize 文档页面
  favicon: /images/favicon.ico
  keywords: 云计算,青云,QingCloud,文档,EdgeWize,KubeSphere
  logo: /images/qingcloud-logo.svg
  logoInfo: EdgeWize # 此为最上方版本索引左边的 title
  logoLink: /
  disablePdf: true
  pdf:
    toclevels: 4
    sectnumlevels: 6
    pdf_timeout: 60
    pdf_projectName: EdgeWize
    pdf_docVersion: '01'
    pdf_copyright: 版权所有 © 北京青云科技股份有限公司
    pdf_legalInfo: 版权所有 © 北京青云科技股份有限公司 2024。保留所有权利。
    pdf_companyFullName: 北京青云科技股份有限公司
    pdf_companyName: 青云
    pdf_companyUrl: https://www.qingcloud.com
    pdf_companyIcon: /images/pdf/qingcloud-logo-icon.png

    pdf_coverDocLogo: /images/pdf/qingcloud-logo-color.png
    pdf_coverDocImage: /images/pdf/cover_doc_image.svg
