title: KubeSphere Enterprise  # 此为学习路径上面的 title
markup:
  asciidocExt:
    attributes:
      toc: null
      toclevels: 2
      file_output_type: html
      relfilesuffix: /
      ks_product: KubeSphere 企业版
      ks_product_left:  KubeSphere 企业版
      ks_product_right: KubeSphere 企业版
      ks_product_both:  KubeSphere 企业版
      ks_product_full: KubeSphere 企业版
      ks_product-en: KubeSphere Enterprise
      ks_product_ver: "v3.4.0"

params:
  disableVersions: false # 此为是否显示版本索引
  description: 这是 KubeSphere 企业版文档页面
  favicon: /images/favicon.ico
  keywords: 云计算,青云,QingCloud,文档,KubeSphere 企业版,KubeSphere
  logo: /images/qingcloud-logo.svg
  logoInfo: KubeSphere Enterprise # 此为最上方版本索引左边的 title
  logoLink: /
  disablePdf: true
  navLink:
    - title: 中文文档
      url: https://docs.kubesphere.com.cn/

  pdf:
    toclevels: 4
    sectnumlevels: 6
    pdf_timeout: 60
    pdf_projectName: KubeSphere Enterprise
    pdf_docVersion: '01'
    pdf_copyright: Copyright © Beijing QingCloud Technology Group Co., Ltd 2025
    pdf_legalInfo: Copyright © Beijing QingCloud Technology Group Co., Ltd 2025. All rights reserved.
    pdf_companyFullName: Beijing QingCloud Technology Group Co., Ltd
    pdf_companyName: QingCloud
    pdf_companyUrl: https://www.qingcloud.com
    pdf_companyIcon: /images/pdf/qingcloud-logo-icon.png
    pdf_coverDocName: KubeSphere Enterprise
    pdf_coverDocLogo: /images/pdf/qingcloud-logo-color.png
    pdf_coverDocImage: /images/pdf/cover_doc_image.svg
