---
title: 产品概述
weight: 01
---


青云云原生产品基于不断创新的云原生技术、DevOps 理念以及业内最佳实践，提供完整生命周期的云原生安全防护，实现统一的安全策略管控和快速的入侵响应。

青云科技目前有以下云原生产品和服务，分别是 KSE 企业级容器平台、QKE 容器引擎、KSV 容器虚拟化、云原生备份容灾服务、KubeEye 云原生集群巡检服务。

== KSE 企业级容器平台

KSE（KubeSphere 企业版）容器平台是基于 Kubernetes 内核的分布式多租户商用云原生操作系统。在开源能力的基础上，在多云集群管理、微服务治理、应用管理等多个核心业务场景进行功能延伸。商用扩展中心实现高度模块化，满足不同场景业务需求。以强大的企业级云原生底座，完善的专家级解决方案和服务支持，赋能企业数字化转型和规模化运营。

其丰富的可观测性使得用户能够跨集群进行多维度监控，并深度集成各类监控面板，为不同角色提供个性化的监控维度。同时， 深度集成多种开源项目，提供多渠道、多配置的监控告警，使得日志、事件、审计等信息得以全方位记录和分析。提供 Solo 和 Federation 双模式集群管理⽅式，⽀持联邦应⽤框架，提供多租⼾的业务资源隔离管理、多层级的权限控制体系。

在安全方面，KubeSphere 企业版提供了开箱即用的安全加固能力，全链路覆盖云原生产品的生命周期，包括安全编译、系统加固、应用安全、敏感数据保护和运维安全等领域。通过深度整合 Istio，内置微服务流量拓扑图，支持微服务链路追踪，无需手动配置。此外，KubeSphere 企业版采用 KubeEdge 进行边缘节点管理，结合多云多集群功能，实现了“云、边、端”一体化管控。这一综合性的安全架构使得企业能够更好地抵御各类安全威胁，保障业务的可靠性和数据的安全性。

通过提供丰富的可观测性、微服务治理、集群与多租户管理、边缘节点支持、DevOps、应用全生命周期管理、容器化数据库服务、云原生数据库管理平台等特性，KubeSphere 企业版助力企业构建高效、灵活、安全的云原生架构，迈向数字化转型的新时代。


== QKE 容器引擎

容器引擎 QKE 是在云平台上构建的企业级分布式多租户的 Kubernetes 容器服务管理平台，集成了云平台的云服务器、存储、网络等资源，可一键部署高可用、高性能的 Kubernetes 集群，支持可视化界面、多集群管理、自动伸缩、运维监控、CI/CD、微服务治理、应用管理、服务与网络管理等业务场景，让您轻松高效地在云端运行 Kubernetes 容器化应用。

容器引擎 QKE 相对于自建 Kubernetes 集群，在易用性、可靠性、性能、可扩展性、成本投入以及可维护性等多方面都具备独特的优势，能最大限度满足企业构建容器服务的各种需求。

== KSV 容器虚拟化

KSV 云原生虚拟化（KSV）是由 KubeSphere 衍生的轻量化虚拟机管理平台，⽀持单节点部署和多节点部署，可⽀撑个⼈⽤户和企业⽤户多种场景下的虚拟化业务需求。KSV 可帮助您减少前期的硬件投入，使用 KSV 创建所需数量的虚拟机，快速开发和部署应用。

KSV 基于 Kubernetes 云原⽣架构，相较于传统虚拟化服务更加轻量、灵活、开放，并且能够实现服务自愈、快速弹性伸缩、灵活调度等能力。



== 备份容灾服务

云原生备份容灾是青云科技针对混合云场景推出的 Kubernetes 备份容灾即服务。用户无需构建备份容灾的基础架构，登录 KubeSphere Cloud 即可对 Kubernetes 集群中的容器进行备份和恢复。

KubeSphere Cloud 云原生备份容灾服务提供简单易用的操作界面，简化备份和恢复的操作流程，帮助用户快速建立备份计划和恢复计划，提高容灾能力。

云原生备份容灾服务适用于以下场景：

- 系统或硬件设施发生故障
+
云原生备份容灾服务能够有效降低因故障而导致的业务中断风险，保障 Kubernetes 集群中核心业务的连续性。

- 开发测试中出现环境变更
+
云原生备份容灾服务能够在开发、测试等过程出现环境变更、配置调整时，及时恢复任何时期、任意仓库中备份的数据。

- 遭遇恶意破坏或不当操作
+
云原生备份容灾服务能够通过数据的备份和恢复，避免恶意破坏或不当操作造成的数据丢失，保障数据的完整可用。

- 多集群、多存储协同保护
+
云原生备份容灾服务能够跨集群、跨云服务商、跨存储区域，轻松实现基础设施间多地、按需的备份恢复、容灾保护。

- 容器应用数据的云上迁移
+
云原生备份容灾服务提供了一种便利的数据迁移方式，让企业灵活、自主地选择或更换云服务商，避免基础设施绑定。

== 集群巡检服务

基于开源工具 KubeEye 提供的集群巡检服务可以对集群进行漏洞扫描和安全加固，发现集群中潜在的风险，确保 Kubernetes 集群安全、稳定、高效运行。

集群巡检服务适用于以下场景：

- 保障 Kubernetes 安全
+
消除 Kubernetes 安全漏洞和盲点，安全扫描有助于 DevSecOps 确保 Kubernetes 和容器的安全。

- 满足合规和安全审计需求
+
当您的项目需要通过专业评审机构安全审计时，可以先通过集群巡检服务发现容器漏洞以及检查集群安全配置、权限管理是否合规，及时规避评测问题。

- 集群异常诊断
+
及时发现集群运行中的问题，从而优化集群使其始终稳定、高效地运行。

- 优化成本
+
通过统计资源数据，提供应用程序资源优化建议，从而避免资源过度配置、节约成本。
