---
title: "为依赖项缓存设置 CI 节点"
linkTitle: "{ks_title}"
keywords: "Kubernetes, {ks_product}, DevOps 项目, 使用 DevOps"
description: "介绍如何管理 DevOps 项目，以及如何在 DevOps 项目中管理流水线和 DevOps 项目设置。"
weight: 04
layout: "second"
icon: ""
---

// :ks_include_id: 552fb0944e6d4d7da9daf24f48ab8deb
:ks_xref_id: e2d673893bae46dbb2d83f3a7fa4af38
:ks_comp: ../../../../components/
:ks_title: 为依赖项缓存设置 CI 节点
:ks_keywords: Kubernetes, {ks_product}, DevOps 项目, 使用 DevOps
:ks_description: 介绍如何管理 DevOps 项目，以及如何在 DevOps 项目中管理流水线和 DevOps 项目设置。
:ks_weight: 04
:ks_icon:


通常情况下，构建应用程序的过程中需要拉取不同的依赖项。这可能会导致某些问题，例如拉取时间长和网络不稳定，这会进一步导致构建失败。要为您的流水线提供更可靠和稳定的环境，您可以配置一个节点或一组节点，专门用于持续集成 (CI)。这些 CI 节点可以通过使用缓存来加快构建过程。

本教程演示如何设置 CI 节点，以便{ks_product_both}将流水线的任务以及 S2I/B2I 构建的任务调度到这些节点。


== 准备工作link:[id=5759917d04724328b60edfc60195d91b]

您需要一个具有**集群管理**权限的帐户。例如，您可以直接以 **admin** 身份登录控制台或者创建一个具有该权限的新角色并将该新角色其分配给一个用户。


== 标记 CI 节点link:[id=f83b8e8817944c35a14ff485d438163c]

. 点击左上角的**平台管理**，然后选择**集群管理**。

. 如果您已经启用多集群功能并已导入成员集群，那么您可以选择一个特定集群以查看其节点。如果尚未启用该功能，请直接参考下一步。

. 转到**节点**下的**集群节点**，您可以在其中查看当前集群中的现有节点。

. 从列表中选择一个节点用来运行 CI 任务。点击节点名称以转到其详情页面。点击**更多操作**，然后选择**编辑标签**。

. 在弹出的对话框中，您可以看到一个标签的键是 **node-role.kubernetes.io/worker**。输入 **ci** 作为此标签的值，然后点击**保存**。
+
--
// Note
include::../../../../../_ks_components/admonitions/note.adoc[]

您也可以点击**添加**来按需添加新标签。

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]
--


== 给 CI 节点添加污点link:[id=10d7362ef8de4ed3ab469fbda4ef100e]

流水线和 S2I/B2I 工作流基本上会根据link:https://kubernetes.io/zh/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity[节点亲和性]调度到该节点。如果要将节点专用于 CI 任务，即不允许将其他工作负载调度到该节点，您可以在该节点上添加link:https://kubernetes.io/zh/docs/concepts/scheduling-eviction/taint-and-toleration/[污点]。

. 点击**更多操作**，然后选择**编辑污点**。

. 点击**添加污点**，然后输入键 **node.kubernetes.io/ci** 而不指定值。您可以根据需要选择 **阻止调度**、**尽可能阻止调度**或**阻止调度并驱逐现有容器组** 。

. 点击**保存**。{ks_product_right}将根据您设置的污点调度任务。您现在可以回到 DevOps 流水线上进行操作。
