---
title: "Extension Management"
keywords: "Kubernetes, KubeSphere, Install extensions, KubeSphere extensions"
description: "Introduction to installing and managing extensions."
weight: 06
---

This section explains how to install and manage extensions.

KubeSphere extensions are built on KubeSphere LuBan to extend and enhance the capabilities of KubeSphere products, further meeting the diverse business needs of enterprises. After the installation of {ks_product-en}, only the core components are enabled by default. Please install extensions in the Extensions Center to fully utilize the capabilities of {ks_product-en}.


ifeval::["{file_output_type}" == "pdf"]

== Product Version

This document is applicable to {ks_product-en} v4.1.2.

== Target Readers

This document is primarily intended for the following readers:

* {ks_product-en} users
* Delivery engineers
* Operations engineers
* Post-sales engineers

== Revision History

[%header,cols="1a,1a,3a"]
|===
|Document Version |Release Date |Description

|01
|{pdf_releaseDate}
|Initial release.
|===
endif::[]