---
title: "Scenarios"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, apps, scenarios, introduction"
description: "Describes the scenarios of {ks_product}."
weight: 02
logo: "{ks_logo}"
downloadUrl: "{ks_download_url}"
---

// :ks_include_id: 0a5788f952dd48618d3736bc3cd0edaf
:ks_xref_id: f8d43f8a947e405980760ba2222611d9
:ks_comp: ../../components/
:ks_title: Scenarios
:ks_description: Describes the scenarios of {ks_product}.
:ks_keywords: {ks_product_full}, {ks_product}, apps, scenarios, introduction
:ks_weight: 02


{ks_product_abbr_full} is applicable to a variety of scenarios. {ks_product} provides a platform for individual users and enterprises of all sizes to virtualize resources. This service also offers a solution to edge computing, resource pooling, hybrid deployment of containerized apps, and replacement of commercial services with the ones self-developed by Chinese vendors.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Edge computinglink:[id=480e42018716457b9dff42f571a35482]

If you have a large number of edge data centers but limited budgets for virtualization, {ks_product} provides a lightweight virtualization platform that supports a minimum specification of 4 CPU cores and 8 GB memory. This helps you significantly reduce the costs of the deployment and O&M of the infrastructure.

{ks_product} also provides excellent compatibility and supports the reuse of legacy hardware such as PCs, industrial PCs, and servers. If your business is deployed across regions and strongly dependent on network performance, {ks_product} allows you to deploy multiple nodes so that business logic can be computed on the nodes that are nearest to your users. This helps you achieve real-time response. {ks_product} can apply to various scenarios, such as data gathering in industrial internet of things (IIoT), smart cities, and smart transportation and real-time analytics.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Resource poolinglink:[id=d6821f052382414a8a246f3464e4eea6]

{ks_product} is a cloud-native virtualization platform self-developed by QingCloud. This service is fully compatible with chips developed by Chinese vendors and can connect to third-party storage devices. {ks_product} can help you improve resource usage and apply to a range of scenarios, such as replacement of commercial services, construction of virtual infrastructures, testing environments, and practical training.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Hybrid deployment of containers and VMslink:[id=5711fbc6ffe64d1d9cd7d894f2dfac68]

Built on top of Kubernetes, {ks_product} is a hyper-converged infrastructure (HCI) that allows you to deploy VMs and containers in hybrid mode. You can adopt a hybrid deployment of KubeSphere and {ks_product}. This way, you can apply for VM or pod resources in a unified console. This simplifies your infrastructure and improves O&M efficiency.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Replacement of commercial serviceslink:[id=7ed4dc8494464d7ca8154ce5b363d94a]

{ks_product} inherits the benefits of the HCI and supports full compatibility with heterogeneous chips. This service offers you a neutral virtualization solution that decouples hardware and software. {ks_product} is compatible with major architectures such as x86 and ARM, and also provides a self-developed cloud management platform to meet business requirements of virtualization in production environments.