---
title: "Editions"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, editions"
description: "Describes the editions of {ks_product}."
weight: 03
logo: "{ks_logo}"
downloadUrl: "{ks_download_url}"
---

// :ks_include_id: 30cde42a5fb94daeb8c357edf2cdebd8
:ks_xref_id: 7380f54441404ccabd94b37339318894
:ks_comp: ../../components/
:ks_title: Editions
:ks_description: Describes the editions of {ks_product}.
:ks_keywords: {ks_product_full}, {ks_product}, editions
:ks_weight: 03


To meet diverse business requirements, {ks_product_abbr_full} provides the following types of editions: Basic, Developer, and Enterprise. The Basic Edition provides a virtualization service free of charge and allows you to deploy up to three nodes and nine VMs. You can enjoy all features of {ks_product}. To deploy more nodes or VMs, you can subscribe to {ks_product} Developer or Enterprise Edition based on business requirements. To obtain more information, visit link:https://kubesphere.cloud/en/ksv/[{ks_product} official website].

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Editionslink:[id=1de63bd9564044588403fe6f2b34ff01]

The following table compares the service capabilities provided by the Basic, Developer, and Enterprise editions of {ks_product}.

[cols="1a,1a,1a,1a"]
|===
|Edition |Billing method |Pricing |Capability

|Basic
|License
|Free of charge
|
* Up to three nodes
* Up to nine VMs
* Community support

|Developer
|License
|Subscription
|
* Up to 10 nodes
* Up to 90 VMs
* Community support

|Enterprise
|License
|Subscription
|
* Unlimited number of nodes
* Unlimited number of VMs
* One-year free software upgrade
* Community support
* Technical support for eight-hour workdays
|===