---
title: "Edit an alert policy"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, alert policies, edit"
description: "Describes how to edit an alert policy in the {ks_product} web console."
weight: 06
logo: ""
downloadUrl: ""
---

// :ks_include_id: 44e95c878df947cbb40583cc7b977d44
:ks_xref_id: f22aa8e9906449d8b62e1987f43c4d83
:ks_comp: ../../../components/
:ks_title: Edit an alert policy
:ks_description: Describes how to edit an alert policy in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, alert policies, edit
:ks_weight: 06
:ks_logo:
:ks_download_url:


This topic describes how to edit an alert policy in the {ks_product_abbr_full} web console. You can edit an alert policy to modify its basic information and alert rule.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=cd60b64e62e7432695933ac3b954f242]

User **admin** can edit all alert policies in your cluster. Project administrators and operators can edit the alert policies created on their own, and project viewers cannot edit alert policies.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Edit from the list of alert policieslink:[id=093e715346dd404e888d9090295d4aa0]

include::../../../_custom-en/alerts/alert-steps.adoc[]

. On the **Alert Policies** tab, find the alert policy that you want to edit, click image:/images/ksv/en/icons/more.svg[operation-menu,13], and then select **Edit** from the drop-down list.
. In the dialog box that appears, modify the basic information and rule of the alert policy, and click **OK**.  For more information about parameters, see link:../02-create-alert-policy/[Create an alert policy].

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Edit from the alert policy details pagelink:[id=db831b7693ea44f09ec7db97b8dd8f5e]

include::../../../_custom-en/alerts/alert-steps.adoc[]

. On the **Alert Policies** tab, click the name of the alert policy that you want to edit. The details page of the alert policy appears.
. On the details page of the alert policy, click **Edit** in the upper-left corner.
. In the dialog box that appears, modify the basic information and rule of the alert policy, and click **OK**.  For more information about parameters, see link:../02-create-alert-policy/[Create an alert policy].