---
title: "Enable and disable logging"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, logging, enabling, disabling"
description: "Describes how to enable and disable logging for a {ks_product_abbr_full} cluster."
weight: 01
logo: ""
downloadUrl: ""
---

// :ks_include_id: 277c1c37dc8a45c2b19717b4026aa603
:ks_xref_id: 969895688f7a41cea40fc332b59a4734
:ks_comp: ../../../components/
:ks_title: Enable and disable logging
:ks_description: Describes how to enable and disable logging for a {ks_product_abbr_full} cluster.
:ks_keywords: {ks_product_full}, {ks_product}, logging, enabling, disabling
:ks_weight: 01
:ks_logo:
:ks_download_url:


The **Logs** module is encapsulated into the main installation package of {ks_product}. If you want to use the logging feature, you can use the CLI tool to enable logging without the need to download a separate feature package. If logging is no longer needed, you can disable this feature.  This topic describes how to enable and disable logging for {ks_product}.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=48293c4afd6a43c5863751adc257413c]


:relfileprefix: ../../../

include::../../../_custom-en/alerts/feature-enable-prerequisites.adoc[]

:relfileprefix: ./


ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Procedurelink:[id=5634d537014c4a4584ec819a6753c2bd]

. Log in to the server node on which {ks_product} is installed as user **root**.  If you install {ks_product} in multi-node mode, log in to one of the server nodes on which {ks_product} is installed.
. Run the following command to enable logging:
+
--
// Bash

include::../../../../_ks_components/code/bash.adoc[]

kubectl -n kubesphere-system patch cc ks-installer --type merge --patch '{"spec":{"logging":{"enabled":true},"auditing":{"enabled":true}}}'

include::../../../../_ks_components/code/codeEnd.adoc[]
--
. If logging is no longer needed, run the following command to disable this feature:
+
--
// Bash

include::../../../../_ks_components/code/bash.adoc[]

kubectl -n kubesphere-system patch cc ks-installer --type merge --patch '{"spec":{"logging":{"enabled":false},"auditing":{"enabled":false}}}'

include::../../../../_ks_components/code/codeEnd.adoc[]
--