---
title: "View operation logs"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, operation logs, list, view"
description: "Describes how to view operation logs in the {ks_product} web console."
weight: 02
logo: ""
downloadUrl: ""
---

// :ks_include_id: 087132021e3a4060a6df4585bafe4d5e
:ks_xref_id: ab96b2ebfaa642859c855bcdbe9ca0b2
:ks_comp: ../../../components/
:ks_title: View operation logs
:ks_description: Describes how to view operation logs in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, operation logs, list, view
:ks_weight: 02
:ks_logo:
:ks_download_url:


This topic describes how to view operation logs in the {ks_product_abbr_full} web console. By default, logs are retained for 7 days.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=d5f190f80cfe4e11b8acd5bb1cb05c5a]

User **admin** can view all operation logs in your cluster. Common users such as project administrators, operators, and viewers can view the operation logs in the projects to which they belong.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Procedurelink:[id=e8355bb1515a48bc90f7921eb8289a36]

include::../../../_custom-en/logs/logs-steps.adoc[]

. On the **Operation Logs** tab, view operation logs.
+
--
You can view all operation logs in the system. The following table describes the parameters.

[cols='1a,4a']
|===
|Parameter |Description

|Time
|The time when the operation log entry was generated.

|Operation
|The operation performed on the resource.

|Status
|The server response status to the browser's request.

|Project
|The project in which the resource was operated.

|Resource Type & Name
|The type and name of the resource that was operated.

|Operator
|The user who performed the operation on the resource.
|===
--
. (Optional) In the upper-right corner of the page, click image:/images/ksv/en/icons/refresh-light.svg[refresh,15] to refresh data. For example, use **Project:default** to search for operation logs in the **default** project.
. (Optional) In the upper-right corner of the page, click image:/images/ksv/en/icons/refresh-light.svg[refresh,15] to refresh data.