---
title: "View system logs"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, system logs, list, view"
description: "Describes how to view system logs in the {ks_product} web console."
weight: 04
logo: ""
downloadUrl: ""
---

// :ks_include_id: 387e26cbde0146408f4f93d42ba3e58a
:ks_xref_id: 46ddaa261ece45d5bb3801c1b7e4d27f
:ks_comp: ../../../components/
:ks_title: View system logs
:ks_description: Describes how to view system logs in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, system logs, list, view
:ks_weight: 04
:ks_logo:
:ks_download_url:


This topic describes how to view system logs in the {ks_product_abbr_full} web console. By default, logs are retained for 7 days. By default, logs are retained for 7 days.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=70342127712c49828331dc3eb1c56bbf]

User **admin** can view all system logs in your cluster. Common users such as project administrators, operators, and viewers can view the system logs in the projects to which they belong.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Procedurelink:[id=8cf12168e5594a90a65f0d90bffdaf2b]

include::../../../_custom-en/logs/logs-steps.adoc[]

. On the **System Logs** tab, view system logs.
+
--
You can view all system logs in the system. The following table describes the parameters.

[cols='1a,4a']
|===
|Parameter |Description

|Component
|The name of the component in {ks_product}.  This includes the project components in the {ks_product} web console and back-end system components.

|Time
|The time when the log entry was generated.

|Message
|The log message returned by each component.
|===
--
. (Optional) Click the search box above the system log list and specify a condition to search for system logs by keyword, component, or time range.  For example, use **Keyword:error** to search for log entries that contain the string **error**.
. (Optional) In the upper-right corner of the page, click image:/images/ksv/en/icons/refresh-light.svg[refresh,15] to refresh data.