---
title: "应用场景"
draft: false
weight: 10
---
== CI/CD

当前 IT 行业发展日益快速，面对海量需求必须具备快速集成的能力。通过持续集成与持续交付，极大提高软件发布效率，才能保证不间断的补全用户体验，提升服务质量，为业务创新提供源源不断的动力。

QKE 可帮助用户实现快速迭代，统一交付，同时可以灵活定制、编排流水线，并有细粒度的审计功能。

* 基于微服务化框架的 CI/CD 模块，原生支持 Kubernetes 平台，内建主流语言可框架模板，降低“编译-测试-部署”的复杂度，同时允许自定义 Pipeline。

* 代码直达镜像仓库（Source to Image）、二进制文件直达镜像仓库（Binary to Image）的方式构建 Docker 镜像，开发人员无需关注 Dockerfile 或 Docker 镜像的配置，即点即生成 Docker 镜像。

* 无需配置 Jenkins，可视化编辑 CI/CD 流水线，并内置 10+ 种 CI/CD 流水线模版，降低 CI/CD 学习成本，有效推动企业 DevOps 落地。

* 独立 DevOps 工程，基于凭证打通多集群，提供访问可控、安全隔离的 CI/CD 操作空间。

* 代码质量控制与流水线结合，持续提升项目质量，支持同时运行多条流水线，流水线复制。

== 微服务治理

微服务架构适用于构建复杂的应用，将单体式应用从不同维度拆分成多个微服务，每个微服务应用使用一个容器进行部署管理，可以独立开发、部署和伸缩。您只需迭代每个微服务应用，由 QKE 提供调度、编排、部署和灰度发布等能力。

* 基于微服务治理模块，可以为开发、测试和运维人员提供更强大的 DevOps 功能。比如在不侵入代码的情况下，通过故障注入检验服务的健壮性，可以将 Kubernetes 的服务进行更细力度的拆分，并完成加密、权限管控等功能，能够实现端到端的全程可视化监控等诸多功能。

* 构建微服务架构，能够实现灵活控制灰度版本的使用。通过参数分流、流量染色等功能，支持设置指定用户或者流量比例试用灰度版本，待灰度版本成熟后，再切换到灰度版本。

* 构建微服务架构，实现流量治理。应对随时增长的应用流量，随时可能遇到热点事件和活动时的流量激增，通过负载均衡、流量控制、熔断降级等服务治理手段有效保护关键服务，降低系统性风险发生。

== 多集群运维管理平台


针对在多地、多云上有多个 K8s集群的大型金融企业、电商、物流等行业客提供 solo 和 federation 两种模式的多集群统一管理，支持通过 OpenPitrix 进行多云环境下的应用统一管理，轻松为用户实现运维一体化。


* 容灾备份：将业务同时部署在多个云的容器服务上，保证业务高可用，在某个云出现事故时，通过统一流量分发的机制，自动的将业务流量切换到其他云上。

* 安全隔离：将生产环境部署在公有云上，而将开发环境或敏感数据业务部署在本地的 IDC，不仅保证了安全性，并能够实现弹性扩展和集群的统一管理，达到云上云下资源和能力的共享。

* 优化成本：享受不同云厂商的服务特性使，避免单一厂商绑定，合理优化成本。

== 应用分发运营平台

针对有多家软件提供商及分支机构的需要计量计费的大型企业，QKE 集成 KubeSphere 可以提供集应用管理和运营为一体的统一管理平台 OpenPitrix，支持多云平台、多应用类型、多打包规范、高度扩展和可插拔、应用全生命周期管理和商业运营。

== 云边协同

针对需要充分利用边缘节点计算能力的客户，QKE 内置KubeSphere 为客户提供基于 KubeEdge 的边缘节点纳管能力，完美支持 ARM 与 x86 架构，将云原生的技术应用到边缘计算，实现云边协同。


