---
title: "产品概述"
keywords: "Kubernetes, {ks_product}, RadonDB, 数据库应用, DMP, 数据库管理"
description: "介绍 RadonDB DMP 数据库管理平台。"
weight: 01
---

// RadonDB DMP 是一个面向云原生、容器化的数据库管理平台，提供企业级数据库产品及服务。覆盖 MySQL、PostgreSQL、Redis、MongoDB 等数个全球主流数据库，支持可视化 Web 操作界面和跨平台部署，为用户解决多种数据库的跨云部署、多云管理难题。⽤⼾仅需专注于业务层逻辑开发，⽆需关注集群⾼可⽤选型、管理和运维等复杂问题，帮助⽤⼾⼤幅度提升业务开发与价值创新的效率。

// RadonDB DMP 数据库管理平台可基于容器平台交付，不仅提供覆盖多场景的数据库产品解决方案，而且提供专业的集群管理和自动化运维能力。主要功能特性包括：高可用主从切换、数据强一致性、读写分离、一键安装部署、多维指标监控与告警、弹性扩容与缩容、横向自由扩展、自动备份与恢复等。

RadonDB DMP 是青云科技全新发布的企业级云原生数据库管理平台。在 KubeSphere LuBan 云原生可扩展开放架构之上，RadonDB DMP 能轻松实现多类型主流数据库的跨云部署、多云管理、智能观测与统一运维等，并完整构建围绕高性能、高可用、业务追踪、数据流转等场景下的生态闭环，助力客户真正实现数据库即服务。

RadonDB DMP 提供一站式、可视化的云原生数据库全生命周期管理。支持一键部署数据库，统一管理所有数据库实例，快速定位潜在风险和故障，并即时监测全局指标状态，提高数据库管理效率。

== 启用 RadonDB DMP

在{ks_product_left} v4.0 及之后的版本中，RadonDB DMP 数据库管理平台是一个独立的扩展组件。

使用 RadonDB DMP，您需要：

. 安装{ks_product_left} v4.0 或更高版本。

. 在扩展市场 https://kubesphere.com.cn/marketplace/extensions/dmp/[KubeSphere Marketplace] 中订阅并安装 **RadonDB DMP**。

更多相关信息，请参阅{ks_product_left}使用文档的link:https://docs.kubesphere.com.cn/v4.0/06-extension-user-guide/[扩展组件管理]章节。

== 版本介绍

RadonDB DMP 中各数据库/中间件产品的包版本以及内核版本如下：

[%header,cols="1a,1a,4a"]
|===
|数据库名称 |包版本 |数据库内核

|MySQL
|3.0.0
|5.7

8.0

|OpenSearch	
|2.0.25
|2.8.0

|Redis Cluster
|1.3.1	
|7.0.4

|Redis Sentinel	
|1.3.1	
|7.0.4

|MongoDB	
|1.1.10
|5.0.10

|PostgreSQL	
|1.2.4	
|12.12 

13.8

14.5

15.3

|Kafka	
|0.2.0	
|3.2

|RabbitMQ	
|2.2.2	
|3.11.13

|===


