---
title: "AddRouterStatics"
description: 增加一条或多条 VPC 网络规则。
keywords: VPC,  VPC 网络, 路由规则
weight: 12
draft: false
---
增加一项或多项 VPC 网络规则，规则类型包括：端口转发、VPN 、DHCP 、隧道、过滤控制。

include::../../../../../_components/note.adoc[]
在增加 VPC 网络规则后，你需要执行 link:../update_routers/[_UpdateRouters_] 才能使之生效。
include::../../../../../_components/table_footer.adoc[]

== 请求参数
[cols="2,1,3,1"]
|===
| 参数 | 参数类型 | 描述 | 是否必选

| router
| String
| 需要增加规则的 VPC 网络ID
| Yes

| statics.n.router_static_name
| String
| 规则名称
| No

| vxnet
| String
| vxnet id
| Yes only in VPC

| statics.n.static_type
| Integer
a| 第n条规则的类型。支持的规则类型有： 

* static_type=1：端口转发规则 +
* static_type=3：DHCP 选项 +
| Yes

| statics.n.val1
| String
a| 第n条规则的 val1 值，会根据规则类型的不同，代表不同含义： 

* 端口转发：val1 表示源端口 +
* DHCP 选项：val1 表示 DHCP {instance_product_name_cn}ID +
| Yes

| statics.n.val2
| String
a| 第n条规则的 val2 值，会根据规则类型的不同，代表不同含义：

* 端口转发规则：val2 表示目标 IP  +
* DHCP 选项：val2 表示 DHCP 配置内容，格式为key1=value1;key2=value2，例如："domain-name-servers=8.8.8.8;fixed-address=192.168.1.2" +
| No

| statics.n.val3
| String
a| 第n条规则的 val3 值，会根据规则类型的不同，代表不同含义： 

* 端口转发规则：val3 表示目标端口号。
| No

| statics.n.val4
| String
a| 第n条规则的 val4 值，会根据规则类型的不同，代表不同含义： 

* 端口转发规则：val4 表示端口转发协议，默认为 "tcp" ，目前支持 "tcp" 和 "udp" 两种协议 +
| No

| zone
| String
| 区域 ID，注意要小写
| Yes
|===

link:../../../introduction/parameters/[公共参数]

== 返回数据

|===
| 参数 | 参数类型 | 描述

| action
| String
| 响应动作

| router_statics
| Array
| 新增加的 VPC 网络规则ID列表

| ret_code
| Integer
| 执行成功与否，0 表示成功，其他值则为错误代码
|===

== 示例

*请求示例：*
[source]
----
https://api.domain.com/iaas/?action=AddRouterStatics
&statics.1.static_type=1
&statics.1.val1=8080
&statics.1.val2=192.168.1.12
&statics.1.val3=8080
&statics.1.val4=tcp
&statics.3.static_type=3
&statics.3.val1=i-m163jcqw
&statics.3.val2=domain-name-servers=8.8.8.8
&COMMON_PARAMS
----

*返回示例：*
[source]
----
{
  "action":"AddRouterStaticsResponse",
  "ret_code":0,
  "router_statics":[
    "rtrs-qihmd2vb",
    "rtrs-b3epyxu5"
  ]
}
----
