---
title: "存储架构"
weight: 10
---



////
SDS 模式
+
SDS 模式是指使用物理服务器上的内置硬盘存储来构建云平台的的存储资源池，并通过青云自研的软件定义存储技术实现的一种分布式存储架构。
+
SDS2.0 与 SDS1.0 统称为 SDS 模式，两者实现原理不同，但部署架构相同。SDS2.0 计算存储节点性能高于 SDS1.0 计算存储节点。

SDS 模式为存算融合部署架构，即，整个企业云平台中不再有单独的计算节点与存储节点，而是使用计算存储节点，用于对外同时提供计算与存储能力。

SDS 模式为企业云平台早期存储架构方案，本文不做详细阐述。推荐使用 SANC 模式。
////

////



== SDS1.0

* 支持全 SAS 化硬盘和 SSD+SAS 的混插存储。
* 针对 SAS 盘进行了高度性能优化。
* 支持节点级的副本策略，默认支持两副本，不支持自定义副本。
* 支持多种同步模式，提供强一致性同步。
* 灾难恢复影响在1分钟内。
* 支持全虚拟化主机。
* 适合超大范围的环境存储实现。

Hyper 节点与其镜像节点通过 DRBD （Distributed Replicated Block Device，分布式复制块设备）实现节点之间块设备内容的存储复制。

DRDB 是一个同步协议，通过网络来镜像整个磁盘设备或磁盘分区，将一个节点的数据通过网络实时的传送到另一个远程节点。

图片

当某个 SDS1.0 计算存储节点宕机时，并不影响用户的业务与数据，与此同时，云平台的虚机迁移机制被触发，系统会寻找其他 SDS1.0 计算存储节点用于当前节点上的块设备内容的存储与复制。当平台中互为镜像的两个 SDS1.0 计算存储节点同时宕机时，处于该宕机节点上的业务与数据均会受到影响。

== SDS2.0


Hyper 节点与其镜像节点通过 ZFS（Zettabyte File System）实现节点之间块设备内容的存储复制。

ZFS 用存储池的概念来管理物理存储空间，其副本不再局限于镜像节点，在整个网络里面可以根据策略在资源比较充足的节点生成副本。

图片

当某个 SDS2.0 计算存储节点宕机时，并不影响用户的业务与数据，与此同时，云平台的虚机迁移机制被触发，系统会寻找其他 SDS2.0 计算存储节点用于当前节点上的数据内容的存储与复制。当平台中，用作备份的两个 SDS2.0 计算存储节点同时宕机时，处于该宕机节点上的业务与数据均会受到影响。因此，云平台提供高可用的架构设计供用户选择，以此确保核心业务与数据永不丢失。


* 支持全闪存储，针对PCIE SSD进行优化
* 支持资源级副本自定义配置，最大支持同数据中心 4副本，或者同数据中心 3 副本+异地数据中心 1 副本
* 同步时间自定义配置，最小颗粒度 1 秒
* 支持压缩， 最大压缩 80%， 平均压缩 50%
* 热迁移切换时间更短，3 秒内
* 同时支持容器主机和全虚拟化主机
* 灾难恢复影响时间更短，30 秒内
* 适合超大范围的环境存储实现 
////