---
title: 安装简介
weight: 1
---


== 概述

从实施角度，我们可以将{product_name}的搭建过程分为环境规划、硬件准备、软件安装、环境配置以及交付验收几个步骤。{product_name}的安装部署文档，将环境规划与硬件准备归纳为前期准备工作，并着重介绍**软件安装**操作步骤以及安装后的**环境配置**操作内容。



环境规划、操作系统的安装以及交付验收的内容，{product_name}均有相应的文档覆盖，实施人员可以参考具体文档了解详细内容。


现将整个流程的简要说明如下。


== 流程
=== 前期准备

在该阶段，实施人员需根据实际情况，对待部署环境进行清晰的需求分析、服务范围界定，并输出详细的解决方案。方案中需包含环境规模、部署架构、网络规划、硬件配置以及服务内容。

本文将不对该部分内容进行详细描述。

完成环境规划后，实施人员需提前准备好相应的安装包，并对各物理硬件进行安装配置，使其达到一个 Ready 的状态，便于后期使用 Intaller 脚本进行{product_name}的安装部署。


=== 安装云平台


根据前期规划，修改相关配置文件后，使用 Intaller 脚本完成{product_name}安装包的安装。

//脚本成功执行完成后，{product_name}尚不能对外提供服务。实施人员需要


//并进行云平台的相关配置后，即可提供相应的云资源以及云服务。云平台默认提供的服务，可参考《{product_name}产品目录清单》。同时，{product_name}也开放增值服务，待{product_name}安装完成后，用户可根据需求，选择安装相应的增值服务。

=== 配置云平台

使用 Intaller 脚本完成{product_name}安装包的安装后，当前环境尚不能投入使用，还需对其进行计算节点初始化、云平台网络初始化、云服务器初始化等一系列配置操作后，才能对外正常提供服务。云平台默认提供的服务，可参考《{product_name}产品目录清单》。同时，{product_name}也开放增值服务，待{product_name}安装完成后，实施人员可根据需求，选择安装相应的增值服务。



=== 交付验证

云平台配置完成后，实施人员需依次登录 Console、BOSS 以及配置中心，确认各服务运行正常以后，才能将环境投入生产使用。详细内容可参考《{product_name}交付验收指南》。