// neonsan-settings.yaml 配置修改"


. 登录 FirstBox。
+
[source,shell]
----
ssh x.x.x.x -p 6023
----
+
include::../../../../../_components/note.adoc[]
* x.x.x.x 需替换为 FirstBox 所在宿主机的管理 IP。
* 用户名密码为 root/zhu88jie。

include::../../../../../_components/table_footer.adoc[]

. 拷贝示例文件至/root 目录下。
+
[source,shell]
----
cp /qingstor/install/test/yaml/neonsan-settings.yaml /root/
----

. 修改配置文件 neonsan-settings.yaml。
+
include::../../../../../_components/note.adoc[]
* 根据实际情况对配置文件进行修改，此配置文件包含混插和全闪环境配置内容，注意区分选择，可删除不需要的配置内容。其中，``use_icas`` 或 ``use_bcache`` 字段为 true 表示混插，均为 false 表示全闪。
* 针对混插环境，目前仅 ubuntu 18.04 arm 以及国产化平台（Kylin Hygon、Kylin Kunpeng）缓存软件使用 bcache，其他平台仍然使用 iCAS。
include::../../../../../_components/table_footer.adoc[]
+
[source,shell]
----
vi /root/neonsan-settings.yaml
----
+
[source]
----
repl_networks:
  - 172.20.0.0/24
  - 172.21.0.0/24
data_networks:
  - 172.22.0.0/24
neonsan_groups:
# 混插配置信息填写：
  - hosts:
      - 172.16.0.2
      - 172.16.0.3
      - 172.16.0.4
    # if empty, will be auto generated from node info
    ssd_disks:
      - sdb
    # if empty, will be auto generated from node info
    sata_disks:
      - sdc
      - sdd
    rg_name: HDD0
    use_bcache: true     
    use_icas: false
    failure_domain:
    
# 全闪配置信息填写：
  - hosts:
      - 172.16.0.5
      - 172.16.0.6
      - 172.16.0.7
      # if empty, will be auto generated from node info
    ssd_disks:
      - nvme0n1
      - nvme1n1
    rg_name: SSD0
    use_bcache: false          
    use_icas: false
    failure_domain:
----
+
**主要配置字段说明如下所示**，需根据实际情况进行修改。
+
[options="header",cols="1,3"]
|===
|字段	|说明
|repl_networks	
|只需要填写 repl_ip（NeonSAN 存储网络）所在的网段，配置之后，installer 会自动扫描并生成相关 IP 配置。 +
若是 spine-leaf 场景，则只填写 repl 的大网段即可，如示例文件中的格式。 +
实际生产环境中需每个节点需配置两个存储网络，故此次填写示例为多存储网络配置方式。对于小型 POC 测试环境中可根据实际情况填写一个网段即可。

|data_networks
|存储前端网络所处网段，用于配置三网独立部署，需根据实际情况进行修改。 +
配置之后，Installer 会自动扫描并生成相关的 IP 配置。若是 spine-leaf 场景，填写 data 的大网段即可，如示例文件中格式。 +
若不配置，默认将使用存储管理网。

|neonsan_groups	
|在同时有混插和全闪的环境或者部分节点配置有差异的部署需求中，通过根据 IP 分组节点的方式区分部署，且相同类型的磁盘需放在同一个 group 内。

|hosts	
|待配置节点的管理 IP。

|ssd_disks	
|填写要使用的 SSD 盘的盘符，若各节点的盘符不一致时，可选择清空内容，只保留该字段即可，Installer 会根据收集到的硬件信息自动生成。 +
若有多个磁盘，需根据示例格式采用一行一个的形式进行填写。

|sata_disks	
|混插配置中，手动填写要用的 SATA 盘的盘符，如果清空只保留该字段，会使用节点上全部未使用的 SATA 盘。如果为全闪配置，保持该配置项为空或者删除该配置项。

|rg_name	
|NeonSAN 集群的存储池名

|use_bcache	 
|表示是否使用 bcache，即是否开启 bcache 混插部署，ture 表示开启，false 表示关闭。

|use_icas	
|表示是否使用 intelcas，即是否开启 iCAS 混插部署，ture 表示开启，false 表示关闭。

|failure_domain	
|neonsan failure domain，不填写将会自动从主机名生成。 +
示例：sh1ar01n01→failure_domain: sh1ar01
|===
