title: KSV 云原生虚拟化文档中心
markup:
  asciidocExt:
    attributes:
      toc:
      toclevels: 2
      file_output_type: html
      relfilesuffix: /
      ks_product: KSV
      ks_product_left:  KSV
      ks_product_right: KSV 
      ks_product_both:  KSV 
      ks_product_full: KSV 云原生虚拟化
      ks_product_full_left:  KSV 云原生虚拟化
      ks_product_full_right: KSV 云原生虚拟化
      ks_product_full_both:  KSV 云原生虚拟化
      ks_product_abbr_full: KSV 云原生虚拟化（KSV）
      ks_product_abbr_full_left:  KSV 云原生虚拟化（KSV）
      ks_product_abbr_full_right: KSV 云原生虚拟化（KSV）
      ks_product_abbr_full_both:  KSV 云原生虚拟化（KSV）
      ks_product_low: ksv
      ks_product_ver: v1.6.1
params:
  description: 这是 KSV 云原生虚拟化文档页面
  favicon: /images/favicon.ico
  keywords: 云计算,青云,QingCloud,文档,KSV 云原生虚拟化
  logo: /images/qingcloud-logo.svg
  logoInfo: KSV 云原生虚拟化
  logoLink: /docs-zh/
  pdf:
    toclevels: 4
    sectnumlevels: 6
    pdf_projectName: KSV 云原生虚拟化
    pdf_docVersion: 1
    pdf_copyright: 版权所有 © 北京青云科技股份有限公司
    pdf_legalInfo: 版权所有 © 北京青云科技股份有限公司 2023。保留所有权利。
    pdf_projectVersion: v1.2.2
    pdf_companyFullName: 北京青云科技股份有限公司
    pdf_companyName: 青云
    pdf_companyUrl: https://www.qingcloud.com
    pdf_companyIcon: /images/pdf/qingcloud-logo-icon.png
    pdf_coverDocName: KSV 云原生虚拟化
    pdf_coverDocLogo: /images/pdf/qingcloud-logo-color.png
    pdf_coverDocImage: /images/pdf/cover_doc_image.svg
    pdf_timeout: 60

ignorefiles: [ ".*/_custom", ".*/_custom-en", ".*/_product_family" ]
