---
title: "Configure NFS"
weight: 05
---


This section describes how to configure Network File System (NFS) for the KubeSphere Enterprise cluster in a production environment.

// Note
include::../../../../../_ks_components-en/admonitions/note.adoc[]

NFS is incompatible with some applications (such as Prometheus), which may cause pod creation failure. If you do need to use NFS in a production environment, make sure you understand the risks or consult KubeSphere technical support at support@kubesphere.cloud.

include::../../../../../_ks_components-en/admonitions/admonEnd.adoc[]

== Build NFS Server

Before configuring NFS for KubeSphere Enterprise, you need to set up an NFS server first. If you already have an NFS server available, you can skip this step. The following uses the Ubuntu operating system and NFS Kernel Server as an example to introduce how to build an NFS server. For specific operations on other NFS servers and other operating systems, see the user guides for the NFS servers and operating systems.


=== Prerequisites

You need to prepare a Linux server (the Ubuntu operating system is used as an example below), which must be connected to the KubeSphere Enterprise cluster node network.


=== Steps

. Log in to the server used to build the NFS server and execute the following command to install the NFS Kernel Server:
+
--
//Bash
include::../../../../../_ks_components-en/code/bash.adoc[]

sudo apt update

include::../../../../../_ks_components-en/code/codeEnd.adoc[]

//Bash
include::../../../../../_ks_components-en/code/bash.adoc[]

sudo apt install nfs-kernel-server

include::../../../../../_ks_components-en/code/codeEnd.adoc[]
--

. Execute the following command to create a directory for use by KubeSphere Enterprise (replace <directory> with the actual directory path, such as **/mnt/demo**):
+
--
// Bash
include::../../../../../_ks_components-en/code/bash.adoc[]

sudo mkdir -p <directory>

include::../../../../../_ks_components-en/code/codeEnd.adoc[]
--

. Execute the following command to remove access restrictions on the directory (replace <directory> with the actual directory path, such as **/mnt/demo**):
+
--
//Bash
include::../../../../../_ks_components-en/code/bash.adoc[]

sudo chown nobody:nogroup <directory>

include::../../../../../_ks_components-en/code/codeEnd.adoc[]

// Bash
include::../../../../../_ks_components-en/code/bash.adoc[]

sudo chmod 777 <directory>

include::../../../../../_ks_components-en/code/codeEnd.adoc[]
--

. Execute the following command to edit the configuration file of NFS Kernel Server:
+
--
// Bash
include::../../../../../_ks_components-en/code/bash.adoc[]

sudo vi /etc/exports

include::../../../../../_ks_components-en/code/codeEnd.adoc[]
--

. Add the KubeSphere Enterprise cluster node information to the file to allow the server to access the NFS server, and save the file:
+
--
// Bash
include::../../../../../_ks_components-en/code/bash.adoc[]

<directory> <IP address>(rw,sync,no_subtree_check)

include::../../../../../_ks_components-en/code/codeEnd.adoc[]

Replace the following parameters with actual values:

[%header,cols="1a,4a"]
|===
|Parameters |Description

|<directory>
|The directory used by KubeSphere Enterprise, for example **/mnt/demo**.

|<IP address>
|The IP address of the KubeSphere Enterprise cluster node, for example 192.168.0.2.
|===

If there are multiple KubeSphere Enterprise cluster nodes, please set multiple configuration entries. You can also set <IP address> to a network segment so that all servers in the network segment can access the NFS server, for example **192.168.0.0/24**.
--

. Execute the following command to enable directory sharing:
+
--
// Bash
include::../../../../../_ks_components-en/code/bash.adoc[]

sudo exportfs -a

include::../../../../../_ks_components-en/code/codeEnd.adoc[]
--

. Execute the following command to restart the NFS server to make the configuration take effect:
+
--
// Bash
include::../../../../../_ks_components-en/code/bash.adoc[]

sudo systemctl restart nfs-kernel-server

include::../../../../../_ks_components-en/code/codeEnd.adoc[]
--

== Configure Cluster Nodes

After the NFS server is built, you need to install the client tool on the KubeSphere Enterprise cluster nodes and create a configuration file for subsequent installation of KubeSphere Enterprise. After KubeSphere Enterprise is installed, the NFS server specified in the configuration file will be used as persistent storage. The following uses the Ubuntu operating system to install NFS Common as an example to introduce how to install the NFS client and create a configuration file. For specific operations on other NFS clients and other operating systems, see the user guides for the NFS clients and operating systems.


=== Prerequisites

You should set up an NFS server. For more information, see link:#_build_nfs_server[Build NFS Server].


=== Steps

. Log in to all KubeSphere Enterprise cluster nodes and execute the following command to install nfs-common:
+
--
//Bash
include::../../../../../_ks_components-en/code/bash.adoc[]

sudo apt update

include::../../../../../_ks_components-en/code/codeEnd.adoc[]

// Bash
include::../../../../../_ks_components-en/code/bash.adoc[]

sudo apt install nfs-common

include::../../../../../_ks_components-en/code/codeEnd.adoc[]
--

. Log in to the cluster node used to perform the KubeSphere Enterprise installation and execute the following command to create the configuration file for NFS storage plugin:
+
--
// Note
// Bash
include::../../../../../_ks_components-en/code/bash.adoc[]

vi nfs-client.yaml

include::../../../../../_ks_components-en/code/codeEnd.adoc[]
--

. Add the following information to the configuration file and save the file for subsequent installation of KubeSphere Enterprise:
+
--
// YAML
include::../../../../../_ks_components-en/code/yaml.adoc[]

nfs:
 server: "<IP address>"
 path: "<directory>"
storageClass:
 defaultClass: true

include::../../../../../_ks_components-en/code/codeEnd.adoc[]

Replace the following parameters with actual values:

[%header,cols="1a,4a"]
|===
|Parameters |Description

|<IP address>
|IP address of the NFS server.

|<directory>
|The directory of NFS server used by KubeSphere Enterprise.
|===

The above configuration file only contains the parameters that must be set. To set other parameters, see link:https://github.com/kubesphere/helm-charts/blob/master/src/main/nfs-client-provisioner/values.yaml[NFS Client Configuration].
--