---
title: "Delete EIPs"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, EIPs, deletion"
description: "Describes how to delete EIPs in the {ks_product} web console."
weight: 08
logo: ""
downloadUrl: ""
---

// :ks_include_id: a40cf4be2777460cb9c9c7a6a84357e3
:ks_xref_id: b519763bee4c4c518d91e5b410d3ec32
:ks_comp: ../../../../components/
:ks_title: Delete EIPs
:ks_description: Describes how to delete EIPs in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, EIPs, deletion
:ks_weight: 08
:ks_logo:
:ks_download_url:


This topic describes how to delete elastic IP addresses (EIPs) in the {ks_product_abbr_full} web console.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=0f743366c65141d085012057a16ffb10]

include::../../../../_custom-en/networks/eip-manage-prerequisites.adoc[]

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Delete an EIPlink:[id=1926356447cd4e619d8ad4a45890ccd5]

include::../../../../_custom-en/networks/eip-steps.adoc[]

. Find the EIP that you want to delete, click image:/images/ksv/en/icons/more.svg[operation-menu,13] on the right side, and then select **Delete** from the drop-down list.
. Click **OK**.
+
--
// Warning

include::../../../../../_ks_components/admonitions/warning.adoc[]

The EIP cannot be restored after it is deleted. Exercise caution when you perform this operation.

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]

// Note

include::../../../../../_ks_components/admonitions/note.adoc[]

Make sure no resources are associated with the EIPs that you want to delete. Otherwise, the EIPs cannot be deleted.

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]
--

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Delete multiple EIPs at a timelink:[id=0810bb12bc6f407db16632f5a4bb46a9]

include::../../../../_custom-en/networks/eip-steps.adoc[]

. On the **EIPs** page, select the check boxes next to the EIPs that you want to delete and click **Delete**.
. In the dialog box that appears, click **OK**.
+
--
// Warning

include::../../../../../_ks_components/admonitions/warning.adoc[]

The EIPs cannot be restored after they are deleted. Exercise caution when you perform this operation.

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]

// Note

include::../../../../../_ks_components/admonitions/note.adoc[]

Make sure no resources are associated with the EIP that you want to delete. Otherwise, the EIP cannot be deleted.

include::../../../../../_ks_components/admonitions/admonEnd.adoc[]
--