---
title: "服务商管理规范"
weight: 4
---

== 第一章 概述

第一条【目的及依据】为维护 KubeSphere Marketplace 平台的管理秩序，保障 KubeSphere Marketplace 服务商、用户的合法权益，依据《KubeSphere Marketplace 服务商入驻协议》等相关协议和规则，制定本规范。

第二条【适用范围】本规范适用于 KubeSphere Marketplace 的所有服务商。

第三条【效力级别】本规范是《KubeSphere Marketplace 服务商入驻协议》（“入驻协议”）的下位规则。入驻协议中已有规定的，从其规定，未有规定或本规范有特殊规定的，按照本规范执行。

== 第二章 定义

第四条 KubeSphere Marketplace ：是由北京青云科技股份有限公司（下称“青云”）搭建的云原生应用扩展市场（网址：https://kubesphere.com.cn/），KubeSphere Marketplace 服务商可通过 KubeSphere Marketplace 向用户推广、销售、提供自己的产品。
KubeSphere Marketplace 下设多个类目，青云可能会调整市场类目的种类、名称，以届时 KubeSphere Marketplace 的页面展示为准。青云可能会根据自身的经营发展情况，适时调整 KubeSphere Marketplace 名称、网址及其他展示要素，并通过公告、站内信、邮件及其他有效方式通知服务商及用户。该等调整不会影响青云与服务商在入驻协议及本规范项下的权利义务关系。

第五条 KubeSphere Marketplace 店铺（“店铺”）：是指服务商在 KubeSphere Marketplace 平台中展示产品、进行收费或免费售卖的虚拟场所，每家服务商入驻的同时都可获得店铺权限和店铺管理权限。

第六条 KubeSphere Marketplace 产品（“产品”）：指服务商独立开发或者依法获得相关权利人授权，通过 KubeSphere Marketplace 向用户提供的各种构建在 KubeSphere LuBan 之上、用以扩展并增强 KubeSphere 产品能力、进一步满足企业各类型业务需求的 KubeSphere 扩展组件或相应的技术支持服务；KubeSphere Marketplace 产品包括自营、代销及服务商自销产品。对于青云自营产品，青云同时对用户承担服务商应对用户承担的所有义务、责任，并享有相应权利。

第七条 KubeSphere Marketplace 服务商（“服务商”）：是指接入并通过 KubeSphere Marketplace ，向用户销售产品/服务或者实际提供产品/服务的独立软件开发商（Independent software vendor, ISV）或个人开发者。

第八条 KubeSphere Marketplace 用户（“用户”）：指通过 KubeSphere Marketplace 购买、使用服务商提供的产品或服务的个人、法人或其他组织。

== 第三章 入驻

第九条 【入驻】入驻 KubeSphere Marketplace ，服务商需要同时满足如下条件：

（一）有效的 KubeSphere Cloud 账号；

（二）通过青云实名认证；

（三）企业开发者还需要提供真实、有效的以下资料、信息：

1、《企业法人营业执照》副本及企业法人身份证复印件；

2、实际经营地（若有），联系人姓名及其联系电话、邮箱，服务商网址链接；

（四）登记服务信息：服务商需如实登记服务人员、服务时间、服务质保期；

（五）签署《KubeSphere Marketplace 服务商入驻协议》，以及与青云另行签署的线下协议（若有） ;

（六）缴纳入驻保证金：根据青云发布的保证金规则缴纳入驻保证金；

1、保证金的收取：在服务商入驻前需要根据产品售价以及服务商资质收取一定量的保证金；

2、保证金的扣除：当出现服务商违规或退款情况，青云有权先行扣除保证金中的金额赔付或退款给用户；

3、保证金的补足：当保证金不足时，服务商需在 3 个工作日内补足保证金，如果不予缴纳保证金，青云将在下一周期结算款中先行扣除保证金部分用于补足，如下一周期结算款中无法补足保证金，将关闭其在 KubeSphere Marketplace 中的所有展示权限包括店铺，直至保证金补足；

4、保证金追加：凡是 12 个月内累积超过 2 次保证金扣除，青云有权在下一年内要求服务商追加 1 万元保证金；

（七）青云要求的其他条件。

== 第四章 经营管理

第十条 【产品上架】服务商在上架产品时，需满足以下要求：

（一）上架的产品应当符合保障人身、财产安全的要求和环境保护要求，且经过青云安全审核；

（二）上架的产品必须提供以下文件或信息：

1、按照 KubeSphere Marketplace 的 link:https://dev-guide.kubesphere.io/extension-dev-guide/zh/packaging-and-release/[《KubeSphere 扩展组件打包发布》]要求提供所有信息；

2、向用户公示的明确的产品协议或服务条款；

3、提供产品下架的政策，如：如何保证已购用户的正常使用，如何转移权属；

（三）上架的产品不得含有以下信息：

1、侵犯第三方知识产权或其他合法权利的；

2、含有木马、黑客程序等有损网络安全的；

3、可能套取他人身份证、邮箱、手机号、银行账号、青云账号等个人或者企业隐私信息的；

4、其他违反法律法规、违反国家政策或违反青云各项规则的内容；

5、发布的产品或信息内容中不得使用 “唯一”、“最优”等夸大宣传或过度承诺的用语；

6、未经青云书面同意，上架的产品不允许内置未在 KubeSphere Marketplace 上架的产品/服务的售卖交易入口；对产品的续费必须通过 KubeSphere Marketplace 平台进行交易；

7、未经青云书面同意，上架的产品不得内置独立的用户管理系统并要求用户重新注册或录入用户信息；

（四）上架的产品标题、图片、属性、价格、服务描述等产品要素之间应当互相匹配对应，并且产品服务详情描述页面、案例等页面中无嵌入非青云网站的外部链接地址，不得故意抄袭其他已入驻 KubeSphere Marketplace 平台的服务商店铺及产品信息；

（五）凡在 KubeSphere Marketplace 平台上架的产品，服务商必须在其企业官网上有独立的产品展示页面；如青云要求，服务商应尽力配合注明与青云的合作关系，提供企业官网的产品购买入口，并链接到 KubeSphere Marketplace 对应的产品详情页上。

第十一条【服务商管理】

（一）服务商应当全面、真实、准确、及时的披露产品信息，保证用户的知情权和选择权。

（二）服务商需具有出售产品所需的全部资质，并对上架的产品具有合法的知识产权或相关权利人的授权；若涉及开源软件，应严格遵守开源软件相关授权规定。

（三）服务商不得销售或提供法律、行政法规禁止交易，损害国家利益和社会公共利益、违背公序良俗的产品。

（四）服务商不得发布不符合 link:https://dev-guide.kubesphere.io/extension-dev-guide/zh/architecture/[《KubeSphere 扩展组件》]的产品信息：包括但不限于违反国家规定的政治宣传和/或新闻信息；涉及国家秘密和/或安全的信息；封建迷信和/或淫秽、色情、下流的信息或教唆犯罪的信息；博彩有奖、赌博游戏；“私服”、“外挂”等非法互联网出版活动；违反国家民族和宗教政策的信息；妨碍互联网运行安全的信息；侵害他人合法权益的信息和/或其他有损于社会秩序、社会治安、公共道德的信息或内容。

（五）服务商在与用户交易过程中，不得引导用户在 KubeSphere Marketplace 之外进行交易，包括但不限于以下情形：

1、在服务过程中，通过青云以外的渠道主动跟最终用户收取额外费用（例如用户购买了云产品配置服务并已经付款，服务商以定价较低为由，要求用户缴纳额外费用才能启动服务等）；

2、用户在 KubeSphere Marketplace 平台已经提交购买的产品，服务商私自将最终用户引导至自已的渠道下单支付；

3、服务商为用户服务项目中，主动引导用户使用非青云产品的行为；

4、其他抢占用户资源的行为。

（六）服务商不得以下列方式，作虚假或者引人误解的商业宣传，欺骗、误导用户：

1、虚构交易、编造用户评价；

2、采用误导性展示等方式，将好评前置、差评后置或者不显著区分不同商品或者服务的评价等；

3、采用谎称现货、虚构预订、虚假抢购等方式进行虚假营销；

4、虚构点击量、关注度等流量数据，以及虚构点赞、打赏等交易互动数据。

（七）服务商不得实施混淆行为，引人误认为是他人商品、服务或者与他人存在特定联系。

（八）服务商不得编造、传播虚假信息或者误导性信息，损害竞争对手的商业信誉、商品声誉。

（九）服务商未经用户同意或者请求，不得向其发送商业性信息。发送商业性信息时，应该明示其真实身份及联系方式，并向用户提供显著、简便、免费的拒绝继续接收的方式。用户明确表示拒绝的，应当立即停止发送，不得更换名义后再次发送。

（十）服务商采取自动续展、自动续费等方式提供服务的，应当在用户接受服务前和自动展期、自动续费等日期前五日，以显著方式提请用户注意，由用户自主选择；在服务期间内，应当为用户提供显著、简便的随时取消或者变更的选项，并不得收取不合理费用。

第十二条 【平台服务保障】

服务商在提供产品的过程中应遵守本规范要求，使用户得到满意的服务体验。

（一）【无理由退货/退款】

1、就服务商在 KubeSphere Marketplace 内提供或销售的产品，服务商应按照以下约定向用户做出无理由退货并全额退款的承诺：

（1）应用类产品：自用户收到产品之日起七个自然日内享受无理由退货并全额退款，但 KubeSphere Marketplace 中的扩展组件按月订阅的不享受该政策；

（2）服务类产品：自用户付款之日起至服务确认完成之日前未使用的服务享受无理由退还对应的款项；

2、尽管有以上第 1 款之规定，在不违反相关法律法规规定的前提下，服务商在 KubeSphere Marketplace 上架的产品其在退货/退款问题上可以选择不适用上述“无理由退货”的规定；但服务商应在该等产品上架时除满足本规范第十条的约定外，还应向青云提前单独明示其退货/退款规则，且在向用户销售/提供产品的界面以显著的方式公示其退货/退款规则，以使用户能够清楚知晓并同意其所获取的产品不适用上述“无理由退货”的规定。

3、尽管服务商已明示不适用“无理由退货”，但在服务商与用户就“无理由退货”产生纠纷时，若依据相关法律、法规、规则或政策等规定应无理由退货的/退款的，服务商应予以无理由退货并全额退款。

（二）【质保期】

服务商在产品协议或服务协议中向用户做出质量保证承诺的期间为质保期。服务商在承诺的质保期内，必须为用户提供与所售卖的产品相关的质保服务，并遵守产品协议或服务协议中关于质保期的相关承诺。

第十三条 【售后服务】

服务商有权自行制定其提供产品的售后服务方案，并承诺采取合理措施，确保用户购买产品时知晓并同意其售后服务方案。
服务商对其在 KubeSphere Marketplace 提供的产品（无论是否收费）提供的售后服务应不低于以下标准：

（一）售后服务方式及时间：

1、服务商应在售出产品后，应当给用户提供产品售后支持；例如电话支持，技术支持，产品支持等。具体以该店铺服务协议中的内容为准；

2、服务商应在周一至周五工作时间（9:00-18:00）内提供实时在线服务；（注：按中国北京时间为准）

3、服务商应实时注意短信或邮件收到的用户工单申请，客服服务时间内不能出现用户工单无人回复，或联系电话、邮件无人响应等情形，以提升用户体验；

4、提供（收费或/及免费）产品的服务商，因产品不可用，服务商必须为用户提供替代方案、数据备份迁移服务等解决措施。

（二）【服务承诺】 在交易过程中，服务商应当按照相关约定（包括但不限于订单内容、服务全程监管、服务商自行向用户作出的服务承诺）向用户提供服务。

第十四条 【发票】

（一）KubeSphere Marketplace 中的服务商自销产品，服务商应向用户全额开具发票。

（二）服务商应就委托青云代销的产品，按照提供给青云的供应价，向青云开具相应金额的发票。

（三）服务商可就青云收取的平台服务费用（如有），向青云申请相应金额的发票。

== 第五章 用户退款管理

第十五条【退款】对于 KubeSphere Marketplace 产品，用户可能会因产品质量、服务不满意等原因发起退款要求。

（一）【无理由退款保证】

符合无理由退货情形的，服务商应自收到用户退款申请后 7 日内完成全额退款。若涉及产品为青云代销之产品，青云享有直接向用户进行全额退款的权利。

（二）【其他退款情形】

除无理由退款保证外，用户因以下原因要求服务商全部或部分退款的，服务商应予以支持；并自收到用户退款申请后 7 日内完成退款或向青云确认退款：

1、服务商产品质量造成客户损失，应予全额退款。

2、服务商在服务中出现人为拖沓致使服务未能按期完成的，应予部分或全额退款；

3、服务商宣称的产品功能及服务承诺与实际所提供的产品功能及服务质量不符的，应予全额退款；

4、服务商未能按与用户达成的约定交付商品或服务，或交付的商品或服务未能满足约定的要求的，应予全额退款；

5、服务商退出 KubeSphere Marketplace 且未提供经青云认可的善后方案的，应视商品或服务的交付程度，予以部分或全额退款；

6、服务商未完成服务/服务不符合约定，且预留联系电话、邮件、传真均无法联络到服务商，或用户对服务态度不满投诉超 3 次，或服务商公司破产或倒闭的，应视商品或服务的交付程度，予以部分或全额退款；

7、其他青云判断属于服务商责任，应当予以部分/全额退款的情形。

（三）服务商向用户退款后，青云与服务商已结算的部分，青云将向服务商追回或在青云同服务商最近一次的结算中扣除，如服务商最近一次的结算金额不足以抵扣退款金额，服务商须在两个月内补足差额。

== 第六章 平台运营管理

第十六条 【行为规范】服务商在 KubeSphere Marketplace 平台提供服务过程中，应遵守以下行为规范：

（一）提交或填写的所有入驻信息、材料应当真实、准确、有效，不得使用虚假资质或虚假信息进行入驻，入驻材料、信息的任何变更(或失效)应自变更(或失效)之日起三个工作日内向 KubeSphere Marketplace 平台报备，并应配合青云对相关文件、信息的定期核验；

（二）未经事先书面授权，不得以青云或青云其他关联公司等名义进行任何销售及宣传活动，包括但不限于电话，函件，邮件，文档等；

（三）不得损害青云品牌和形象，直接或间接仿冒产品；

（四）服务商不等擅自修改产品安全配置；

（五）服务过程中不得出现帐号提升权限、安装后门程序等主动危害系统安全的行为；

（六）服务过程中不得隐瞒其所发现的系统缺陷且恶意利用，应及时告知用户；

（七）不得辱骂、恐吓、威胁、欺诈用户；

（八）服务商应当仅获取为提供 KubeSphere Marketplace 服务而必要的信息，且服务商在服务过程中收集的信息仅可在为某一特定用户提供 KubeSphere Marketplace 服务过程中使用；服务商不得将收集的信息用于服务之外的任何目的，不得将信息出售、转让或向任何第三方披露，也不得超范围收集用户信息；前述信息包括但不限于用户会员名、手机号码、地址、产品账号密码、网站数据等；涉及个人信息收集、使用的，应遵循相关法律法规之规定，在相关产品的提供界面以显著的方式向用户告知并获得同意；

（九）服务商应积极对自身的产品进行更新或调整，保证所提供的产品安全、可用；

（十）产品有更新或调整的话，服务商应及时同步更新到 KubeSphere Marketplace ；

（十一）连续三个月零成交产品 KubeSphere Marketplace 有权下架；

（十二）服务商在服务过程中应做好数据备份等工作，完结后及时删除备份的数据，不得因人为失误造成用户损失：

1、产品维护或者数据迁移过程中因服务商错误操作导致数据丢失；

2、不同的青云最终用户数据因服务商工作失误造成混淆；

3、除以上列出的行为之外的其他导致数据丢失或混淆的情形。

（十三）当发生投诉时，服务商应积极配合 KubeSphere Marketplace 进行调查及取证工作，并在 30 分钟内响应，不得：

1、假冒用户致电，表示撤销投诉；

2、用户投诉后，虚构事实，隐瞒实情，阻碍青云正常调查；

3、除以上列出的行为之外的妨碍、阻止、影响 KubeSphere Marketplace 调查、取证的行为。

（十四）当服务商提供的产品因为版权问题（包括青云接到投诉或有合理理由判断的情况），被版权所有方追责，服务商应采取有效措施停止侵权：

1、下架该产品；

2、为已使用该产品的用户，提供替代该产品或其他解决方案，并负责为用户提供在此过程中所需要的数据迁移及其他相关服务及费用；

3、其他合理必要的措施。


== 第七章 违规处理

第十七条 【违规情形与处理】服务商出现违规情形后，KubeSphere Marketplace 按照附件一《KubeSphere Marketplace 服务商违规情形处理一览表》，依据相应的违规情形认定和处理流程，经认定属实后，进行相应的处理。另外违规情形之外的违规行为，青云保留根据事实进行判断处理的权利。

第十八条 【节点处理】KubeSphere Marketplace 对服务商进行独立的违规处理，处理的方式有如下措施：

1、扣分：依据服务商不同的违规行为予以扣分的方式并予以记录；

2、店铺冻结：指店铺及产品在一定期间内无法在 KubeSphere Marketplace 展现，但不影响已订购该店铺内产品的用户正常使用；

3、保证金扣除：指依据服务商不同的违规行为予以扣除部分或全部保证金的方式；

4、清退：服务商违规扣分累计达 24 分的，所有产品下架，服务商清退，保证金扣除；

5、依据法律法规政策、协议条款及管理规范的规定，青云有权采取的其他措施，包括但不限于展现方式降等、违规通报、追加保证金、限制产品类目等。

第十九条 【违规扣分】服务商违规所扣分数将在每个自然年十二月三十一日二十四时清零。若投诉须进行跨年度处理的，则所扣分值记录到下一个自然年中。

== 第八章 退出管理

第二十条 【合作终止退出】协议期限届满而双方决定不再续约，或出现由一方或双方提出的提前终止协议的情形时，服务商退出 KubeSphere Marketplace。

第二十一条 【主动退出】服务商有权根据自身的实际经营情况，申请退出 KubeSphere Marketplace。

第二十二条 【清退】服务商如出现以下任一情形，青云有权将其清退出 KubeSphere Marketplace：

1、服务商出现上文违规处理里所列的应被清退的情形；

2、不再符合相应的入驻条件；

3、服务商会员账户因违反青云网站的其他规范，已被青云列黑名单或清退的。

4、服务商在一个自然年度内违规扣分累计达 24 分；

5、其他青云认定服务商违规情形严重的行为。

第二十三条 【退出再申请】服务商主动退出 KubeSphere Marketplace 的，自退出之日起须间隔一年以上方可再次提交入驻申请；服务商被青云清退出 KubeSphere Marketplace 的，永久不得重新入驻。

第二十四条 【退出后业务处理】无论因何原因服务商退出时，对其与用户之间已经达成的交易，按如下方式处理：

（一） 购买该服务商的服务或产品的用户项目未交付或未启动的，应视产品或服务的交付程度，予以部分或全额退款；

（二） 服务商退出后 KubeSphere Marketplace 后，青云对其已经售出的产品，不再提供续费服务；

（三） 服务商退出后，其售出的 KubeSphere Marketplace 产品的相关售后服务，均由服务商自行与用户协商提供。对青云代销的产品，服务商同意青云可保留其保证金至所有该等产品质保期届满。质保期内未发生任何纠纷的，青云在该等质保期满 10 日内退还保证金。

第二十五条 服务商合作终止退出或主动退出 KubeSphere Marketplace 的，须提前 60 日发送电子邮件至 support@kubesphere.cloud 提交退出申请。KubeSphere Marketplace 审核通过后，服务商应提前三十日在其店铺主页的显著位置，持续公示终止销售公告的信息，并采取合利、必要、及时的措施保障用户和 KubeSphere Marketplace 的合法权益。

第二十六条 服青云将务商清退 KubeSphere Marketplace 的，青云将在其店铺主页的显著位置，持续公示终止销售公告的信息，并采取合利、必要、及时的措施保障用户的合法权益。

== 第九章 附则

第二十七条 本规范于北京时间 2023 年 10 月 10 日发布。自发布之日起生效。

第二十八条 青云有权根据市场环境、合作商合作体系发展状况等因素对本管理规范做相应的修订。修订后，将以公告、站内信、邮件及其他有效方式方式通知服务商。

== 附件：服务商违规情形处理一览表

[%header,cols="1,4,1,1,1"]
|===
|违规类型	|违规内容	|扣分	|处理类型	|保证金扣除

.5+|违反行为规范
|未经青云或其关联公司授权，服务商在其服务标识、服务标题、服务简介、服务详情、图片或其他页面服务中使用“青云”、“QingCloud”、 “KubeSphere”、“青云科技”或关联公司的名称、或上述品牌的附属标志及图案的任何变体、缩写或错误拼写；
|12	|服务冻结 15 天	|3000 元

|服务商向运营、生态合作经理等工作人员行贿等行为；	
|24	|清退	|全部扣除

|对于服务商引导 KubeSphere Marketplace 用户进行线下交易的行为，将采取零容忍政策，一经查证属实，将立即清退相关服务商，永久终止 KubeSphere Marketplace 业务合作。（服务商终止合作、产品下架等触发的未完成项目的退款除外。）详见：第十一条。	
|24	|清退	|全部扣除

|提供 KubeSphere Marketplace 禁止的服务或产品；详见：第十条、十一条	
|12	|服务冻结 7 天	|1000 元

|擅自出售、转让、向任何第三方泄露，或以其他方式违规使用青云的经营信息和运营数据，及/或用户的个人信息和相关数据的；	
|24	|清退	|全部扣除

.4+|违反诚信经营	
|服务未完成恶意引导用户提前验收，引起的用户投诉；
|6	|–	|1000 元

|对用户实施欺诈行为引起用户投诉，对用户造成严重损失的；	
|12	|服务冻结 15 天	|3000 元

|当接到投诉时，假冒用户向青云表示撤销投诉；	
|6	|服务冻结 7 天	|1000 元

|当接到投诉时，虚构事实，隐瞒实情，阻碍青云正常调查；	
|6	|–	|1000 元

.11+|服务或产品违规	
|辱骂、恐吓、威胁用户的行为；	
|12	|服务冻结 15 天	|3000 元

|当接到投诉时，服务商未在 30 分钟内及时响应；	|3	|–	|–

|店铺客服、电话在约定的服务时间内未能提供实时服务，或售后邮件、电话未能及时响应回复，导致用户投诉或者被 KubeSphere Marketplace 抽查发现的	
|3	|–	|–

|拒不履行双方已确认的服务承诺的，包括但不限于未完成的过度承诺引起用户投诉的；	
|6	|–	|–

|服务商在或开发过程中出现帐号提权、安装后门程序等主动危害系统安全的行为；	
|24	|清退	|全部扣除

|上架的产品含有木马、黑客程序等有损网络安全的；	
|24	|清退	|全部扣除

|上架的产品可能套取他人身份证、邮箱、手机号、银行账号、支付宝账号等个人或者企业隐私信息的；	
|24	|清退	|全部扣除

|服务商在服务过程中擅自修改用户云产品安全配置引起用户投诉的；	|12	|服务冻结 15 天	|3000 元

|上架的产品内置未在 KubeSphere Marketplace 上架的产品/服务的售卖交易入口，对产品的续费必须通过 KubeSphere Marketplace 进行交易；	
|12	|服务冻结 15 天	|3000 元

|上架的产品内置独立的用户管理系统并要求用户重新注册或录入用户信息	
|12	|服务冻结 15 天	|3000 元

|上架的产品侵犯第三方知识产权或其他合法权利的；	
|12	|服务冻结 15 天	|–

.2+|不正当竞争	
|服务商通过虚假交易等方式提高产品或服务的销量；	
|3	|–	|–

|服务商以恶意抄袭、评价、恶意投诉、诋毁、虚假订购等方式进行不正当竞争；	
|6	|服务冻结 7 天	|–

.2+|违法入驻规则	
|使用虚假资质或虚假信息进行入驻 KubeSphere Marketplace ；	
|24	|清退	|全部扣除

|服务商未在其企业官网上展示在 KubeSphere Marketplace 上架的产品，购买入口未链接到 KubeSphere Marketplace 对应的产品详情页上，以及未注明与青云的合作关系；	
|6	|–	|–

|===

注：

未在本表列举范围内的违规情形，青云有权依据管理规范所确定的原则进行相应的处理。

青云有权视违规行为的恶劣程度、影响范围、后果大小等，在本表基础上叠加适用其他必要的处罚措施。