---
title: Portal 操作指南
description: 本文将详细介绍如何使用 QingStor U10000 的 Portal 统一运维管理平台，以下简称 Portal。本文档适用于 QingStor U10000 V4.1 版本。
weight: 5
pdf_docVersion: '01'
---



Portal 是 {product_name} 给用户提供的界面形式的管理平台。用户通过该可视化图形界面实现对 {product_name} 的管理运维操作。


其功能模块包括但不限于以下内容：

* 存储资源管理
* 存储服务管理
* 运维管理

用户可在**存储资源**模块查看当前环境中各资源使用情况及其当前的健康状态。在**存储服务**模块，用户可使用文件存储与对象存储服务，并对其进行一些自定义的设置，如开启或关闭某项功能等。**运维管理**模块提供告警管理、用户管理等功能。

各模块详细内容及操作步骤，可参考后文描述。

== 软件版本

本操作示例使用如下软件版本，在实际操作时，请以实际软件版本为准。

* 支持的 {product_name} 版本为 v5.0。
* 支持的浏览器类型为：
** Chrome 73 及以上的版本
** Edge 79 及以上的版本
** Firefox 63 及以上的版本
** Safari 12.1 及以上的版本
** Opera 60 及以上的版本

== 读者对象

本文档适用于以下工程师：

* {product_name} 技术支持工程师。
* {product_name} 运维工程师。


== 相关资源

《{product_name} Console 用户指南》

《{product_name} 常见问题》

《企业云 v6.1 BOSS 用户指南》


== 名词解释

[cols="2,5", options="header"]
|===
| 名词 |解释

|全能节点 |该节点上同时部署有网关服务与存储服务。

|网关节点 |该节点上部署有网关服务。

|存储节点 |该节点上部署有存储服务。

|标准存储 |提供高可靠、高可用、高性能的对象存储服务，具有高吞吐和低延时的服务响应，能够支持频繁的热点数据访问。

|低频存储 |提供高可靠性，较低存储成本和较低访问时延的对象存储服务，适合长期保存不经常访问的数据。

|副本模式 |数据冗余采用多副本实现。

|EC 模式 |数据冗余采用纠删码的方式实现。

|集群 |针对 Zone 下所有物理资源，一个集群可划分为多个资源池。
|存储池 | 有关联关系的一组物理资源。
|资源池 |一组相同性能、相同用途或同类型硬件的存储池。如 `标准存储` 与 `低频存储` 分别对应不同的资源池。

|===

