---
title: "Edit a physical network"
linkTitle: "{ks_title}"
keywords: "{ks_product_full}, {ks_product}, web console, physical networks, edit"
description: "Describes how to edit a physical network in the {ks_product} web console."
weight: 04
logo: ""
downloadUrl: ""
---

// :ks_include_id: 122c7567c2dd4da8a3cb7a172ee2580d
:ks_xref_id: a934bafb661842f982c9ab8ca3c885d6
:ks_comp: ../../../../components/
:ks_title: Edit a physical network
:ks_description: Describes how to edit a physical network in the {ks_product} web console.
:ks_keywords: {ks_product_full}, {ks_product}, web console, physical networks, edit
:ks_weight: 04
:ks_logo:
:ks_download_url:


This topic describes how to edit a physical network in the {ks_product_abbr_full} web console. The edit operation allows you to modify the name and description of a physical network.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Prerequisiteslink:[id=f33bb0eda3d8442e8c2d6946bee7a833]

include::../../../../_custom-en/nodes/prerequisites-view.adoc[]

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Edit from the list of physical networkslink:[id=7066024f324c486ebf91eac331907442]

include::../../../../_custom-en/networks/physical-network-steps.adoc[]

. Find the physical network that you want to edit, click image:/images/ksv/en/icons/more.svg[operation-menu,13] on the right side, and then select **Edit** from the drop-down list.
. In the dialog box that appears, modify **Name** and **Description** of the physical network, and click **OK**.

ifeval::["{ks_output_type}" == "pdf"]
[discrete]
endif::[]
== Edit from the physical network details pagelink:[id=6a886389d79847f98f46433b0c70c51e]

include::../../../../_custom-en/networks/physical-network-steps.adoc[]

. On the **Physical Networks** page, click the name of the physical network that you want to view. The details page of the physical network appears.
. On the left side of the physical network details page, click **Edit** in the upper-left corner.
. In the dialog box that appears, modify **Name** and **Description** of the physical network, and click **OK**.