---
title: 常见问题
description: 云防火墙常见问题
draft: false
weight: 1
keywords: 云计算, 云防火墙常见问题
linkkey: security_cfw_firewall_faq
---

== 云防火墙各个版本的区别？

目前{platform_shortname}云防火墙一共有 5 个版本，主要区别在防护带宽范围、防护公网 IP 范围。

|===
| 版本 | 防护带宽范围/Mbps | 可防护公网 IP 数

| 试用版
| 10
| 10

| 专业版
| 10~50
| 20~50

| 高级版
| 50~200
| 50~200

| 企业版
| 100~1024
| 100~1024

| 旗舰版
| 300~2048
| 300~2048
|===


== 云防火墙的收费模式？

基础套餐按6个月、1年、2年、3年方式收费以及扩容包（扩展带宽50元/Mbps/月、扩展公网IP 50元/个/月）方式收费。


== 云防火墙可以防护哪些资产？

云上公网 IP。目前{platform_shortname}云防火墙在北京 3 区、上海 1 区上线，可防护 北京 3 区、上海 1 区的资产。

== 云防火墙在整个安全防御系统中的位置？

云防火墙一般部署于外网与内网边界，采用直连的方式接入用户网络，防止内网环境遭受外网的网络攻击。


== 云防火墙的价值？

* 云上资产集中监控安全防护无死角：自动同步云上资产，通过以资产为视角对各种安全事件进行关联分析统计，实现集中可视化监控。
* 安全策略及时更新未知风险可防护：不断更新安全策略库，推动管理员快速发现内网未知威胁、0day 攻击等，准确发现内部失陷资产，帮助管理员提前做好安全防范、快速进行攻击检测与响应。
* 多维度策略动态调整 更加贴合客户需求 ：提供黑/白名单、访问控制、入侵防御多种安全策略来保证用户资产的安全。用户可根据实际业务情况进行自定义调整。
* 提供日志审计功能事后回溯更清晰：记录通过云防火墙所有流量的日志，包括流量日志、事件日志和操作日志，对攻击事件进行取证溯源。帮助用户实时审计网络流量，并为可疑流量进行相应的处理提供依据。


== 云防火墙升级问题？

目前{platform_shortname}云防火墙仅支持横向升级即扩容包方式，不支持垂直升级即套餐版本。

== 防火墙开启防护时长？

开启防护全过程大概 3 分钟。


== 策略生效的顺序？

策略生效顺序将按照黑名单、白名单、访问控制策略、入侵防御策略执行。


== 各策略的配额问题？

* 地址簿：默认支持 100 条
* 服务端口：默认支持 100 条
* 访问控制策略：默认支持 100 条
* 流量控制策略：默认支持 100 条
* 黑/白名单：默认支持 4088 条


== 互联网防火墙的作用？

互联网防火墙可针对云上公网 IP 和互联网之间制定内访外和外访内的控制策略，满足云用户对于互联网流量访问控制的管理与安全防护需求。


== 未配置规则时，云防火墙默认规则是允许还是拒绝？

允许。

== 配置访问控制策略，需要多长时间才生效？

立即生效。

== 策略达到上限该怎么办？

删除不需要的策略或者提工单进行处理。

