title: "QingStor NeonSAN 文档中心"
contentDir: "content/@neonsan"

markup:
  asciidocExt:
    attributes:
      toc:
      toclevels: 2
      file_output_type: html
      product_name: NeonSAN

params:
  description: "这是 Qingstor NeonSAN 文档中心页面"
  favicon: "/images/favicon.ico"
  keywords: "青云,QingCloud,QingStor,NeonSAN,分布式存储,块存储,文档"
  logo: "/images/qingcloud-logo.svg"
  logoInfo: "NeonSAN"
  logoLink: "/v3.5.1" # 当前项目默认版本

  # PDF 配置
  pdf:
    toclevels: 4
    sectnumlevels: 6
    pdf_projectName: QingStor NeonSAN
    pdf_docVersion: v3.7
    pdf_copyright: 版权所有 © 北京青云科技股份有限公司
    pdf_legalInfo: 版权所有 © 北京青云科技股份有限公司 2024。保留所有权利。
    pdf_projectVersion: v3.5.1
    pdf_releaseDate: 2023-03-23
    pdf_companyFullName: 北京青云科技股份有限公司
    pdf_companyName: 青云
    pdf_companyUrl: https://www.qingcloud.com
    pdf_companyIcon: /images/pdf/qingcloud-logo-icon.png
    pdf_coverDocName: QingStor NeonSAN 分布式存储系统
    pdf_coverDocLogo: /images/pdf/qingcloud-logo-color.png
    pdf_coverDocImage: /images/pdf/cover_doc_image.svg
