---
title: "GPU 云服务器特性"
weight: 5
---

青云提供全新 GPU A100 云服务器，采用 GPU 直通方式与云服务器对接，省去虚拟化带来的损耗，全面释放物理 GPU 的计算加速能力。

== 性能优势

* 超高计算加速：大型模型上将 AI 训练的速度提升高达 3 倍，与 CPU 相比 AI 推理性能提升高达 249 倍。
* 物理直通方式连接：采用物理直通方式连接，消除虚拟化损耗，提供接近物理部署的计算性能。
* 极致网络性能：基于 Mellanox 100G HDR InfiniBand 解决方案，支持 InfiniBand 无限带宽技术，内网带宽最高可到 100Gb/s，具有极高的吞吐量和极低的延迟。

== 技术优势

* 功能：A100 的 新型流式多处理器（SM）显著提高了性能，除了引入 Volta 和 Turing 架构的功能之外，还增加了许多新功能和增强功能。
* 算力：相比于 Volta 和 Turing 每 SM 有 8 个 Tensor Core（每个 Tensor Core 每个时钟周期执行 64 个 FP16/FP32 FMA 操作，64*8=512），A100 每个 SM 包括 4 个第三代的 Tensor Core（每个 Tensor Core 每个时钟周期执行 256 个 FP16/FP32 FMA 操作，256*4=1024），与 Volt 和 Turing 相比 SM 的算力增加 2 倍。
* 共享内存：Ampere 架构的共享内存更大，块大小也就更大，这就减少了全局内存访问延迟。因此，Ampere 可以更好地利用 GPU 存储的总体内存带宽。这将提高约 2%~5% 的性能。对于大型矩阵矩阵，性能的提升尤其明显。
* 内存带宽：比较 Volta 和 Ampere 架构的 Tensor Core，在相同情况下 Ampere 架构仅需1/3的寄存器，这允许共享内存的每个 Tile 有更多 Tensor Core 活动。然而性能的瓶颈还是在于带宽，Ampere 的架构经过优化，它使用改进后的存储层次结构（从全局内存到共享内存块，再到张量核寄存器），使可用内存带宽更加有效，从而使实际的 TFLOPS 提高了大约 1%~3% 的性能。
* 与 V100 对比：相比 V100，A100 单精度浮点计算能力，从 15.7 TFLOPS 提升至 19.5 TFLOPS；而双精度浮点运算从 7.8 TFLOPS 提升至 9.7 TFLOPS。





